bluesky/bluesky

bluesky/hardware_checklist.py, bluesky/standard_config.py, bluesky/tests/test_hardware_checklist.py
This PR includes a hardware checklist that checks databases, servers, storage disks, and any important PVs.
More unrelated commits may be added to this PR as the night goes on. Currently we are still waiting for the sample to be found.
=> Sleepover: commits from the overnight at CSX

bluesky/run_engine.py
=> ENH: Include the scan type __name__ and args in Runstart

bluesky/register_mds.py
A follow-up to #177 with some docstring fixes I didn't catch in the review.
=> DOC: Update docstrings.

bluesky/examples.py
Turns out it was a trivial fix.
=> MNT: use syn detectors with any motor

bluesky/simple_scans.py
Sorry for the caps -- well, not really. This one line bug caused way more confusion than I'd like to admit.
=> FIX: SUB FACTORIES

bluesky/scientific_callbacks.py
=> ENH: rough draft at background subtraction

bluesky/callbacks.py, bluesky/global_state.py, bluesky/scans.py, bluesky/simple_scans.py, examples/raster_mesh.py
Added to `mesh`
Also this makes `gs.PLOT_Y` and `gs.MASTER_DET_FIELD` linked. See commit msg.
=> Subs factory for LiveRaster

bluesky/callbacks.py, bluesky/global_state.py, bluesky/simple_scans.py
`gs.OVERPLOT`, True by default
=> Make overplotting configurable through global switch.

bluesky/callbacks.py, bluesky/scans.py
Also only open the event bundle once.
=> FIX: only wait after starting all moves

bluesky/simple_scans.py
two simple fixes from rapid work this morning
=> Cleanup sloppiness

bluesky/simple_scans.py
Also added a couple docstrings regarding things that weren't immediately clear to me (these are almost definitely in the wrong spot)
=> Minor fix: _update_lists

bluesky/standard_config.py
Add more useful imports to the standard config. I still plan to move this out of the bluesky repo someday.
=> ENH: Add imports to standard_config.

bluesky/broker_callbacks.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_vertical_integration.py, doc/source/api_changes.rst
=> Api post run

bluesky/scans.py, bluesky/tests/test_scans.py
Straightforward fix to one issue in #225
=> FIX/TST: DeltaListScan should accept a list, not only an ndarray.

bluesky/run_engine.py
We keep finding this kind of bug. Based on some regex searches, this is the last one.
=> FIX: Another case of mutating during iteration.

bluesky/scans.py, bluesky/simple_scans.py
Tests pass, but I want to discuss the approach before merging.
=> REF: Make more things properties; .md is inspectable before run

bluesky/standard_config.py, bluesky/tests/test_examples.py, setup.py
=> MNT: make history optional

bluesky/examples.py, bluesky/global_state.py, bluesky/simple_scans.py, bluesky/tests/test_simple_api.py
Closes https://github.com/NSLS-II/wishlist/issues/79
=> Add gs.FLYERS

bluesky/callbacks.py, bluesky/simple_scans.py
closes https://github.com/NSLS-II/Bug-Reports/issues/61
attn @hanfeiyan
=> Enh gs fig management

bluesky/scans.py
Don't both reviewing this yet. More to come.
=> WIP: fixes for new ophyd

bluesky/callbacks/core.py, bluesky/callbacks/olog.py
This is how I customized the logbook entries at CHX.  I am confident that this is not what everyone else will want, but it does serve as a template with which others could modify this to suit their needs.  Thoughts?
=> ENH: Add example for customized Olog callback

bluesky/simple_scans.py, bluesky/spec_api.py
Might be more, but this is what I've found so far
=> FIX: scans->plans over-aggressive sed job

.travis.yml, bluesky/run_engine.py, bluesky/standard_config.py, bluesky/tests/test_examples.py, conda-recipe/meta.yaml, setup.py
Also, now that historydict is on PyPI, we can include it as a dependency.
=> history.History -> historydict.HistoryDict

.travis.yml, bluesky/hardware_checklist.py, bluesky/register_mds.py, bluesky/standard_config.py, bluesky/tests/test_hardware_checklist.py
I suspect that this can be simplified further to use lamdas instead of the wrapper function.
=> Mnt mds api

bluesky/callbacks/olog.py
Generalizing @ericdill's `OlogCallback` for use around the ring.
- Missing import (my fault!)
- Do not hardcode logbook name; make it required arg.
- Fail on __init__ if we are not in an IPython session.
=> FIX/API: Fix up OlogCallback

bluesky/callbacks/olog.py
This was never tested in the wild. Basic fixes.
=> FIX: Make new olog callback work.

bluesky/run_engine.py, bluesky/tests/test_examples.py
remove a checkpoint with out creating a new one
=> ENH: add clear_checkpoint message

bluesky/simple_scans.py
tested with @ambarb @cmazzoli yesterday
=> ENH: Add a sub factory for multi-point ct ("time scan").

bluesky/broker_callbacks.py, bluesky/tests/test_vertical_integration.py
Closes #22
This code was used in production at XPD last cycle. I reworded the error messages and added a test.
=> ENH: Callback verifies Documents and external files available.

bluesky/plan_tools.py
These should be a step up from just `list(plan)`
```python
from bluesky.examples import motor, motor1, det, det1
from bluesky.plans import OuterProductAbsScanPlan
plan = OuterProductAbsScanPlan([det, det1], motor, -1, 1, 10, motor1, -5, -3, 15, 1)
path_plotter(plan, 'motor', 'motor1', probe_size=.1)
```
A bunch of nicities missing (like axes labels, where the start is, legend, etc) but this gets the general idea across.
=> ENH: a few simple tools for inspecting plans

bluesky/register_mdc.py
but it registers metadataclient
This is dumb, but effective.
=> ENH: almost clone of register_mds

bluesky/simple_scans.py
Was raising due to motors having more than one data key
=> MNT: fix raster factory

bluesky/callbacks/__init__.py, bluesky/callbacks/core.py
=> FIX: Do not include image data in LiveSpecFile.

.travis.yml, bluesky/utils.py
The first key in describe is all we need
A version of this is source-installed (but not commited) at SRX
=> FIX: finish fixing first_key_hurestic

bluesky/suspenders.py
This gives the ability to disable (remove) a suspender.
attn @imrealkaren
=> ENH: add remove method to SuspenderBase

bluesky/run_engine.py
- We had fixed this issue for *pausing* by adding `self._bundling = False`
to the `resume` method, but we (I) missed it in `request_suspend`. To avoid
this error in the future, I refactored the common code into `_rewind`.
=> FIX/REF: Fix suspension during event bundling.

bluesky/callbacks/core.py, bluesky/tests/test_examples.py
Hopefully this will allow us to more quickly debug these problems in the future.  Looking specifically at nsls-ii/bug-reports#83
=> ENH: Keep a record of seeing the target key in LivePlot

bluesky/__init__.py, bluesky/examples.py, bluesky/run_engine.py, bluesky/tests/test_examples.py
This is a proof-of-concept commit.
This relies on @klauer refactoring of the status objects.
=> ENH: look at success state of status objects

bluesky/run_engine.py
The `insert` method on deque was added in 3.5
closes #353
=> MNT: python 3.4 compat

bluesky/scientific_callbacks.py
=> FIX: PeakStats.com should be a scalar.

bluesky/callbacks/core.py
=> FIX: Fix specfile formatting.

bluesky/examples.py, bluesky/plans.py
Notice that we are doing this is plans, so it is still *possible* tell the RunEngine to stage a subdevice (not its root) if for some reason we ever want to do this.
=> FIX: Stage ultimate parent device (root).

bluesky/plans.py
=> FIX: also do root-checking for unstage

bluesky/simple_scans.py
The idea is to insert by default the PLOT_Y to the LiveTable when using the SPEC-like API.
=> ENH: Add PLOT_Y to LiveTable by default.

bluesky/broker_callbacks.py
See https://github.com/NSLS-II/bluesky/issues/377
=> FIX: Allow calling LiveImage from another thread.

bluesky/run_engine.py, bluesky/tests/test_devices.py
=> ENH: Add monitor/unmonitor messages.

.travis.yml, bluesky/examples.py, bluesky/run_engine.py, bluesky/tests/test_devices.py, bluesky/tests/test_examples.py, bluesky/tests/test_vertical_integration.py, fuzz/README, fuzz/fuzz.py, run_tests.py
This PR is adding a module that can be used for fuzz testing (thanks for the i
term @cowanml!).  This module is attempting to break the RunEngine by throwing 
random messages at it and making sure it can recover into a usable state.  This
PR is still WIP because I am not using all possible message types yet.  I also
need to throw keyboard interrupts at random points too.
Things left to do in this PR:
Messages that are passed in to the RunEngine:
=> WIP: Fuzz testing!

bluesky/callbacks/core.py
This is to prevent clashes with 'time' as a data key.
=> FIX: do not use 'time' as a special magic key

bluesky/broker_callbacks.py
Related to https://github.com/NSLS-II/ophyd/pull/307
=> Restream convenience callbacks

bluesky/plans.py
=> FIX: try obj.position and fallback to obj.read

bluesky/plans.py, bluesky/run_engine.py
See commit msgs. This might never get used, but it seemed like a useful option to have.
=> ENH: Add option to emit events from RunEngine._collect in streaming fashion.

bluesky/run_engine.py
=> MNT: Make 'stop' an optional piece of the API.

bluesky/__init__.py, bluesky/plans.py, bluesky/spec_api.py, bluesky/tests/test_scans.py, bluesky/tests/test_simple_api.py, doc/source/plans.rst
This was a lot simpler when it was hidden in hxntools...
=> ENH/TST: add spiral and fermat spiral scans

bluesky/plans.py
=> FIX: fly_during block group + misc

bluesky/plans.py
Writing docstrings while I watch *Last Week Tonight*. Fun?
=> DOC: Add See Also section to more plan docstrings.

bluesky/plans.py, bluesky/tests/test_new_examples.py, bluesky/utils.py
The `md` kwargs of the generators is not accessible through the Plan classes. This fixes that.
=> Plan class md

bluesky/plans.py
This may fix an issue that @klauer reported.
I do not have a reproducible example to test this on.
=> FIX: address issues unfinalized generators

bluesky/plans.py, bluesky/run_engine.py
- Use ChainMap to give md from kwargs precedence over hard-coded md.
- Add 'plan_name' to everything.
- Add a couple 'plan_args' accidentally left out in the first pass.
=> ENH: Improve plan md.

bluesky/run_engine.py, bluesky/utils.py
Since @danielballan is heading off to the beautiful-yet-eternally-cloudy UK for a well-deserved vacation, here's a minor fix on #450 to (hopefully) get tests passing.
=> FIX: sanitize np

bluesky/plan_patterns.py, bluesky/plans.py, bluesky/tests/test_scans.py
=> ENH: add tilt angle option for all spiral scans

.travis.yml, bluesky/callbacks/olog.py, bluesky/callbacks/scientific.py, bluesky/tests/conftest.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_olog_cb.py
This allows customization based on the 'plan_name' field of the
RunStart.
attn @NSLS-II-CHX
=> ENH: pass mappings into logbook_cb_factory

bluesky/plans.py, bluesky/spec_api.py
These are all minor.
I couldn't find any problems with `mesh`, @klauer; [this metadata output](https://gist.githubusercontent.com/danielballan/a8b9b174166edd3867a38e1d05a4e4bb/raw/6e5a47c6f1da1a80aebe1a346830a94513e9ccc9/mesh.json) looks right to me. What I am missing?
=> SPEC API fixes

.travis.yml
=> CI: create sentinels for FS

bluesky/interactive.py
- Adds a base-class to handle the mpl related work
- Add one example of specializing to an outer_product_plan
attn @licode
=> ENH: add skeleton of interactive plan creation

bluesky/plans.py
Enjoy this rare @klauer single-issue cleanup PR
=> REF: reduce usage of single_gen as a test

bluesky/plans.py, bluesky/run_engine.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, bluesky/tests/utils.py, bluesky/utils.py
Do this by controlling if messages are cached or not.
Still needs tests.
=> ENH: add flag to control replay on resume

.travis.yml, bluesky/examples.py, bluesky/tests/test_examples.py, bluesky/tests/test_scans.py
- The SynGauss had a 0.05s sleep in it's trigger method, set to 0
- use fresh_RE on more tests
=> TST: tests are marginally faster by removing delay

bluesky/__init__.py, bluesky/plan_tools.py, bluesky/plans.py, bluesky/register_mds.py, bluesky/run_engine.py, bluesky/tests/test_generators.py, bluesky/tests/test_utils.py, bluesky/utils.py
Merge this after #504 as it includes all of the commits from that PR.
Pushing this up so we don't lose it.
=> Enh single msg ensure generator

bluesky/tests/test_simple_api.py
=> TST: allow smoke testing of peakstats with spec_api

bluesky/run_engine.py
=> MNT: clean up suspender messages at beginning of run

bluesky/run_engine.py
=> PERF: asyncio.sleep(0) is enough to relinquish control.

bluesky/utils.py
The hard part of this commit was written by @tacaswell.
attn @brunoseivam
Closes #538 
Partly addresses https://github.com/NSLS-II/Bug-Reports/issues/131
=> ENH: Add install_nb_kicker for LivePlot in notebooks.

bluesky/callbacks/core.py, examples/basic_raster_plot.py
fixes #544
Also adds missing documentation
=> FIX: add `aspect` kwarg to LiveRaster

bluesky/plan_patterns.py, bluesky/spec_api.py, bluesky/tests/test_ramp_plan.py
=> Fix spec spiral

bluesky/run_engine.py
The Msg is immutable, but the contents are.  Do not pop things off the
kwargs as it can be destructive if the Msg comes back via the msg_cache.
=> FIX: do not mutate the message

bluesky/run_engine.py, bluesky/tests/test_run_engine.py, doc/source/debugging.rst
for @Brudhu, with love
See the test in this PR for a demo.
=> Add state hook

bluesky/tests/test_ramp_plan.py
Maybe this will be more reliable on travis?
=> CI: tweak ramp plan test timings

bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py, doc/source/state-machine.rst
=> API: Remove three-control-Cs shortcut, making way for RE.halt.

bluesky/run_engine.py
Missed this when fixing the other cases
=> FIX: do not mutate the set message

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
This PR adds an attribute to the RunEngine, `preprocessors`, that holds a list of functions that will be applied to the plan before execution. It's a hook that could be used to add things like beamline-specific cleanup that should always be performed.
Since preprocessors see all of the messages, they can do conditional cleanup like, "If we see detector X in this plan, do the following to 'cleanup' for detector X."
I'm pretty sure this is a good idea, but just in case we discover it's bad idea and want to take it away, let's hold off on documenting it for now. The PR includes a test and a docstring update but no prose documentation.
Closes #568
=> ENH: Add preprocessors to the RunEngine.

bluesky/callbacks/core.py, bluesky/tests/test_callbacks.py, doc/source/callbacks.rst
* Test a multivariate model with LiveFit.
* Fix bugs exposed by that test.
* Document LiveFitPlot and add more examples.
=> LiveFit fixes

bluesky/examples.py, doc/source/callbacks.rst
@CJ-Wright This is a partial fix. The other FS Reader will have to fixed in a similar way, and we have to think about configuration_attrs as well. Would you push it across the finish line?
I discovered the problem writing this example (which works on this branch but does not work on master). https://gist.github.com/danielballan/e7474490fab2139ed2981b6ca156597d
cc @chiahaoliu
=> WIP: Fix FS-integrated Reader example.

bluesky/callbacks/core.py
Closes https://github.com/NSLS-II/wishlist/issues/122
=> Fix liveplot legendkeys default

bluesky/plans.py
Otherwise the motor position will not be in the document streams
=> FIX: always use read message in tweak

bluesky/tests/test_documents.py
=> TST: Test that event_model forbids dots in key names.

doc/source/conf.py, doc/source/cookbook/grid_in_grid.py, doc/source/cookbook/grid_in_grid.rst, doc/source/cookbook/index.rst, doc/source/cookbook/scan_gaussian.py, doc/source/cookbook/scan_gaussian.rst
An example inspried by Melinda's use case at XPD
Don't merge quite yet -- there is a sphinx problem.
=> DOC: Add grid-in-grid example.

doc/source/callbacks.rst
Long-overdue examples for the template dispatch in our olog callback
attn @yugangzhang who asked for this > 1 year ago
=> DOC: Add examples of olog template customization.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
These are my first stab at coming up with a `CONTRIBUTING.md` and templates for Pull Request and Isues. 
They are far from perfect, but I think that they are good enough to start the discussion.
=> Initial Contributing and issue/pr templates

bluesky/plans.py, bluesky/tests/test_callbacks.py
attn @gjwillms @ambarb 
The fix was smaller than I expected.
=> Fix stopped plans

bluesky/plans.py
I'm opening this PR from @cmazzoli's branch so we can have discussion in the PR rather than in the commit.
Delay in count was jiittering due to BS overhead.
Added a simple check in order to minimize the effect if specified delay is at least long enough (in finite plan only for the moment).
Left a comment for modification of delay array generation that I believe would be useful
@danielballan, @tacaswell how does it look like?
=> IMP to better track delay in count

.travis.yml, bluesky/run_engine.py, bluesky/tests/test_run_engine.py
=> FIX: key sequence number on both stream name and objects read

doc/source/conf.py
Closes https://github.com/NSLS-II/bluesky/issues/665
=> DOC: Add viewcode extension.

bluesky/plans.py
Carried over from discussion in #654
=> ENH: Try to check in advance that count 'delay' compatible with 'num'

bluesky/examples.py, bluesky/tests/test_new_examples.py
Support more of the expected API
Started working on this for testing MAIA stuff, but went down other rabbit holse.
needs tests + finishing
=> WIP: changes to synthetic detectors to support configuration

bluesky/plan_tools.py, bluesky/tests/test_plan_tools.py
Print a nice summary of the plan as it goes by.
=> ENH: add print_summary_wrapper

bluesky/run_engine.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_suspenders.py
- let pre/post plans be callabels
- never cache suspender related messages
This was found debugging some shutter + suspender related issues at SRX
Needs tests.
=> Enh suspenders

.travis.yml
=> CI: try to fix docs building

bluesky/plans.py
Plans like 'stage_context' and 'event_context' were an early experiment in
trying to make plan composition readable. These were never documented or widely
taught. They were superceded by the preprocessors that came later.
This PR adds warnings, adds '..deprecated:: 0.10.0' markup in docstrings, and
refactors two places where we still used these internally. This change should
not break any user code. No tests were changed.
=> API: Deprecate *_context plans that operated on 'plan_stacks'

doc/source/comparison-with-spec.rst, doc/source/index.rst
Distilling some thoughts that often come up verbally at tutorials
into a new page of the documentation.
=> DOC: Draft a comparison with SPEC with @prjemian.

bluesky/examples.py, bluesky/tests/test_examples.py
`ReaderWithFSHandler` -> `ReaderWithRegistryHandler`
=> API: rename ReaderWithFSHandler

bluesky/__init__.py, bluesky/plans.py, bluesky/tests/test_bec.py, bluesky/tests/test_supplemental_data.py, doc/source/api_changes.rst, doc/source/async.rst, doc/source/plans.rst
Closes #736
Note that this name change should not impact users becaues the entity
being renamed is new as of the upcoming release.
=> API: Rename DiagnosticPreprocessor -> SupplementalData.

bluesky/callbacks/broker.py, bluesky/examples.py, bluesky/run_engine.py, bluesky/suspenders.py, bluesky/tests/test_suspenders.py, doc/source/api_changes.rst
The SuspenderBase docstring was wrong which lead to confusion.  This fixes the docstring, adds a test to be sure and cleans up a couple of databroker related issues.
=> document and test that pre and post plans to suspends can be functions

bluesky/callbacks/broker.py, bluesky/tests/test_callbacks.py
Create base class for dealing with the databroker in callbacks.
Closes #717
=> Fill callback

bluesky/callbacks/best_effort.py, bluesky/callbacks/core.py, bluesky/tests/interactive/example.ipy, doc/source/callbacks.rst, doc/source/plans.rst
=> MNT: Make BestEffortCallback good enough to try at a beamline.

bluesky/callbacks/core.py
Allow LiveTable to re-direct to an arbitrary location.
The original implementation (reverted in the first commit) did notwork within sphinx (presumably due conflicting re-directs) 
Manual inspection of sphinx output.
=> Rev lt change

bluesky/callbacks/broker.py
Previously the field was gotten, now we just make certain the key exists. The filled part assures us that the data is loaded.
Ran on my computer.
@tacaswell @danielballan @stuartcampbell Urgent Fix
=> FIX: don't actually get the data just make sure the key is there

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
This is to support getting live updates out of a flyer.
@brunoseivam asked for it.
Added a test.
=> ENH/API: allow collect to be called multiple times

bluesky/examples.py, bluesky/magics.py, bluesky/tests/interactive/progress.ipy, bluesky/tests/test_progress_bar.py, bluesky/utils.py, requirements.txt
Works with https://github.com/NSLS-II/ophyd/pull/420
Looks like:
```
mtr2  9%|███▊                                       | 0.09/1.0 [00:00<00:01,  1.21s/deg]
mtr1100%|████████████████████████████████████████████| 1.0/1.0 [00:01<00:00,  1.12s/deg]
```
Closes #714
=> ENH: Add a progress bar capability

bluesky/utils.py
This will un-break all of the databroker tests
=> MNT: remove stray ophyd import

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
Test has two calls to RE but they both put out the same uid. 
@danielballan this was the minimal test you were asking for, sorry for the delay.
=> FIX: RunEngine returns uids as immutable tuple

bluesky/magics.py
=> FIX: Apply precision to limits in 'wa' magic.

bluesky/callbacks/best_effort.py, bluesky/callbacks/core.py, bluesky/plans.py
One actual bug-fix and a couple minor improvements.
=> BEC fixes from ESM

bluesky/utils.py
This _might_ fix the bug we saw at ESM. Should test in the wild before
merging.
=> FIX: Do not allow the drawn attribute to be out of sync with the drawing.

doc/source/callbacks.rst
=> DOC: Document how to use a kicker with the RemoteDispatcher.

bluesky/callbacks/broker.py, bluesky/tests/test_callbacks.py
`BrokerCallback` only will try to load external things
=> BrokerCallback only will try to load external things

bluesky/tests/conftest.py
(for those of us with small memory/paranoia)
=> TST: destroy databroker on finish

bluesky/callbacks/zmq.py
Mulligan on #811. We might eventually choose a different (and
safer) serialization method like msgpack, but that does not handle
numpy arrays out of the box, so let's start from pickle.
=> FIX: Use pickle for serialization, not repr and literal_eval.

bluesky/plans.py, doc/source/api_changes.rst, doc/source/plans.rst
Closes #808
Thanks for the feedback @kevinyager, @cmazzoli, @ambarb -- and @awalter-bnl for kicking this off.
=> API: input -> input_plan

bluesky/callbacks/best_effort.py
Fixes two minor bugs caught during the CMS deployment.
(cc @ordirules)
Tested interactively.
=> FIX: Minor fixes to BEC

doc/source/state-machine.rst
=> DOC: Fix argument error in suspenders example.

bluesky/run_engine.py, bluesky/tests/test_run_engine.py, doc/source/documents.rst
Closes #848
Based on discussion in https://github.com/NSLS-II/databroker/issues/188
=> ENH: Record the number of Events per stream in the stop document.

bluesky/plans.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_scans.py
Closes #750 
The travis logs are too noisy
=> Tst suppress warnings

bluesky/callbacks/core.py
Call show when using an internally generated figure (like the image callbacks)
=> FIX: show live figure if made internally

bluesky/callbacks/zmq.py
OCD fix
(maybe should also be `RE=RE`. also would suggest emphasizing that this is not necessary and `RE.subscribe` can be called after the fact as well)
=> docstring fix

bluesky/callbacks/core.py, doc/source/conf.py
make `Axes.imshow` reference a link.
@cmazzoli said the documentation was not clear and this being a link would have made it clearer
rendered it locally and checked that the link worked.
=> DOC: set up intersphinx and correct a link to Matplotlib

bluesky/callbacks/mpl_plotting.py
Patches to make the docs build again
=> FIX: add missing import

doc/Makefile, doc/source/state-machine.rst
=> Added generated to toctree in state-machine

doc/source/plans.rst
=> DOC: typo from plans

bluesky/tests/test_legacy_plans.py
Add a test to check for that legacy plan names exist.
=> TST: Add test to check for legacy plan names

bluesky/callbacks/best_effort.py
=> removed None

doc/source/state-machine.rst
Review/correction of the contents of the state-machine.html page.
Removed duplicating examples, corrected typos and added missing methods.
Better documentation.
=> DOC: correct state-machine.html page

bluesky/preprocessors.py, bluesky/tests/test_supplemental_data.py
Closes #931
See the new test, ``test_order``, that ensures we are all on the same page
and that we don't mess this up again.
=> FIX/TST: Apply SupplementalData modifications in a sensible order.

doc/source/callbacks.rst
oops just noticed this typo, we probably should correct this
=> DOC : fix typo

doc/source/index.rst
Add all projects toctree to the bluesky documentation.
Motivated by https://github.com/NSLS-II/docs/issues/73.
Tested locally by building the documentation.
=> DOC: added all projects toctree to bluesky

doc/source/api_changes.rst, doc/source/callbacks.rst
Corrected text to match https://github.com/NSLS-II/bluesky/releases/tag/v1.1.0
The docs were built locally.
I'm not sure why the links from docstrings of https://github.com/NSLS-II/bluesky/blob/master/bluesky/utils.py#L700 are not generated. @danielballan, any ideas?
=> DOC: update api_changes doc

bluesky/suspenders.py
should be proper warning `DeprecationWarning`
@tacaswell
=> Turned warning into DeprecationWarning

doc/source/callbacks.rst
I'm sure there could be more typos, but I just noticed this one in passing.
=> DOC: Fixed some syntax in doc on callbacks

bluesky/suspenders.py
Undoing #945 (sorry @danielballan ).
As an alternative, we can get together and vote on a force push to remove the commit but I personally don't feel comfortable with this.
=> Remove the deprecation warning

bluesky/callbacks/broker.py
=> MNT: move `doct` import from top-level

bluesky/callbacks/best_effort.py, bluesky/callbacks/mpl_plotting.py, bluesky/plans.py, bluesky/tests/interactive/best_effort_cb.py, bluesky/tests/test_callbacks.py
See issue https://github.com/NSLS-II/bluesky/issues/961
So far, this first commit fixes the inner product. It now looks like:
need to fix so that first plot is not plotted
=> BUG : Fix inner product

doc/source/callbacks.rst, doc/source/tutorial.rst
Mostly copy editing, some minor rephrasing for clarity.
=> DOC: Copy-edit tutorial.

doc/source/tutorial.rst
This incorporates early feedback from @cmazzoli. Thanks!
I don't want to get to far ahead ourselves or derail the practical demonstration by
lauding the design of bluesky, but I think Claudio's right that we should give people
a concrete idea early on of what we are trying to achieve with this whole "plan" abstraction.
Can this be made shorter? Are there other points that should be included?
=> DOC: Give a sense for why plans are useful earlier in the tutorial.

doc/source/tutorial.rst
Thanks to @awalter-bnl for detailed and thoughtful feedback. (The easy parts
are addressed here. More extensive changes will be in a separate future PR.)
=> DOC: Fix typos, clear up some confusion, and fix a broken code example.

bluesky/callbacks/fitting.py, bluesky/tests/test_scientific.py
comparison with chx work is added.
=> Comparison between current bluesky algorithm and the one from chx on peak stats

.travis.yml, bluesky/run_engine.py
This is coupled with the PR into event-model (https://github.com/NSLS-II/event-model/pull/15).
- allow both list and tuple to be accepted as json "array"
- put a list in the descriptor for the interruption event stream to allow for stricter schema (this is required for tests to pass with https://github.com/NSLS-II/event-model/pull/15).
Running the bluesky tests against a local version of event-model
=> MNT: tweak document validation 

bluesky/callbacks/core.py
Found that alongside #1024, fixed by @danielballan. The motivation is the same.
=> ENH: fix callbacks for collect_asset_docs

bluesky/run_engine.py
This PR is created on @danielballan's behalf. We found a missing piece of `collect_asset_docs` during the work with the flyers.
Implements new asset registry API for the flyer's `collect` method.
It's related to the recent asset registry refactor https://github.com/NSLS-II/databroker/pull/322.
A test to be created.
=> ENH: collect_asset_docs for flyers

bluesky/magics.py
=> More magics work

bluesky/plan_stubs.py
updating the doc links for clsoe_run and open_run
modified the documentation for close_run and open_run.
This fixes issue #1033
=> Close run docs

bluesky/magics.py
=> FIX: correct labels processing

MANIFEST.in, README.md
Fix non-existent `README.rst` in MANIFEST.in and correct the description of the development conda build.
=> BLD: fix MANIFEST.in and the contents of README.md

bluesky/run_engine.py
=> FIX: Fixed typo.

bluesky/run_engine.py
=> Fix typo 2

bluesky/callbacks/mpl_plotting.py
fixing a typo I noticed in LiveGrid during my study of possible upgrades
=> Fixing a LiveGrid typo

doc/source/msg.rst
Still needs to be elaborated on. All with push permissions on this repo, feel free to push to this branch.
=> first pass on documentation for Msg

bluesky/run_engine.py
- Add INFO messages right before the plan is executed and right after
state is cleared up in the ``finally`` block.
- Remove superfluous messages.
- Make use of `logging.exception` to show full tracebacks in error logs.
As we prepare to capture logs systematically for all beamlines, I am reviewing what information we log.
The pytest coverage of `run_engine.py` is extremely good, so I expect that will catch any typos. See interactive test below.
The output of `RE(count([det]))` with DEBUG logs on is:
```
[I 09:01:41.499 run_engine:743] Executing plan <generator object count at 0x1174a0d68>
[I 09:01:41.500 run_engine:82] Change state on <bluesky.run_engine.RunEngine object at 0x11559bef0> from 'idle' -> 'running'
[D 09:01:41.500 run_engine:1184] stage: (SynGauss(name='det', value=1.0, …
```
=> ENH/CLN: Increase and tidy logging.

doc/source/tutorial.rst
=> DOC: We need to pass a motor to scans

bluesky/callbacks/best_effort.py, bluesky/callbacks/mpl_plotting.py, bluesky/tests/test_bec.py
The big rewrite is not going to make it out for this release so
make the small fix.
=> FIX: let BEC plot integers

doc/source/callbacks.rst
=> DOC: add warning about adjusting .PREC

doc/source/api_changes.rst, doc/source/debugging.rst
A follow up edits for #1134.
See my comments at https://github.com/NSLS-II/bluesky/pull/1134/files.
=> DOC: more corrections to release notes and debugging

bluesky/tests/test_run_engine.py, requirements.txt
=> TST: collect_asset_documents_with_flyer

bluesky/callbacks/zmq.py
I made this mistake at ISS and the error message gave me a moment's
pause.
=> ENH: Raise a clearer error is prefix str is passed in.

doc/source/async.rst
Some missing import keywords in the examples.
=> missing imports.

bluesky/tests/test_bec.py, requirements.txt
- xfail a test that caught this
- pin the requirement back
=> Deal with jsonschema 3 deprecations

doc/source/async.rst
=> DOC minor, minor, minor typo

scripts/bluesky-0MQ-proxy
=> remove fstring

doc/source/api_changes.rst
=> DOC: release notes 1.5.1

bluesky/callbacks/mpl_plotting.py
=> FIX: Do not break support for mpl 2.x.

doc/source/api_changes.rst
=> DOC: Release notes for v1.5.2

bluesky/callbacks/best_effort.py
Not actually a required key in the start document
closes #1163
=> MNT: use get rather than [] to get scan_id

bluesky/callbacks/zmq.py
=> remove np sanitize from ZMQ publisher

bluesky/run_engine.py
This PR addresses issue #959.
change RunEngine.state to RunEngine._state
create a state property
=> Make 'state' externally read-only #959

bluesky/callbacks/zmq.py
=> RemoteDispatcher once

.travis.yml, dev-requirements.txt
Test OSX builds on TravisCI.
Originally it was proposed via https://github.com/danielballan/bluesky/pull/18 - a PR to a PR branch, decided in a Slack conversation with @danielballan and @tacaswell it's worth to first test on the current master, and then suck it into #1125.
```bash
$ brew install travis. # or `brew upgrade travis`
$ travis lint
```
=> CI: add OSX building support for TravisCI builds

doc/source/api_changes.rst
The release notes only addressed the event loop refactor and nothing
else. I have finished them and changed to date to "Pre-release".
=> DOC: Finish release notes.

doc/source/api_changes.rst
=> DOC: Fix a bunch of sphinx formatting.

bluesky/preprocessors.py
=> DOC: Fix xref in SupplementalData docstring.

bluesky/tests/test_persistent_dict.py, bluesky/utils.py, doc/source/metadata.rst, requirements.txt
Closes #1227. See that issue for motivation and design discussion.
This is a critical fix that should go into 1.6.0.
=> Change recommended RE.md to PersistentDict.

bluesky/callbacks/best_effort.py, doc/source/api_changes.rst
@awalter-bnl ran into this on his desktop and this bit SIX on the
first day of beam.
This commit is cherry-picked from the master branch.
=> MNT: support Matplotlib 3.1

bluesky/tests/test_transformer.py, bluesky/utils.py
Also adds a test for both IPthon APIs
This should be backported to the 1.5.x branch
Fixes the `register_transform` for ip7
It was broken due to changes in the API of IPyhton
Added tests.
=> MNT: Update register_transform for IP 7

bluesky/callbacks/stream.py, bluesky/callbacks/zmq.py, bluesky/examples.py, bluesky/run_engine.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_documents.py, bluesky/tests/test_examples.py, bluesky/utils.py
There are still some warnings in our test suite but this makes some
progress on clearing them.
=> MNT: Remove some warnings

bluesky/suspenders.py
as suggested in PR #1247, these changes missed the merge
=> MNT #1247 implement changes

.gitignore, bluesky/interactive.py, bluesky/plans.py, bluesky/run_engine.py, bluesky/suspenders.py, bluesky/utils.py
Style cleanups and gitignores from playing with vscode.
=> style and gitignores from vscode

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
RE.stop was not actually aborting the plans early when coming out of
the paused state.
Use the same logic used in abort and halt
Added a new test the verifies the correct exception type is raised out
of the paused point.
=> FIX: stop was not correctly exiting the plan early

doc/source/api_changes.rst
=> Add note about mpl 3.1.0.

bluesky/preprocessors.py, doc/source/plans.rst
=> Document contingency_wrapper.

bluesky/callbacks/best_effort.py, bluesky/callbacks/mpl_plotting.py, bluesky/tests/interactive/example.ipy, bluesky/tests/interactive/subs_decorator.ipy, bluesky/tests/interactive/subs_decorator_dynamic.ipy, bluesky/tests/test_callbacks.py
This interactive test reproduces the issue.
```
ipython -i bluesky/tests/interactive/subs_decorator.ipy 
```
The first part runs successfully; the second produces a black Figure/Canvas that never gets drawn on, just as we observed at BMM. This PR also contains an attempt to fix it, but it doesn't work yet.
=> Fix "black canvas" issue observed at BMM.

bluesky/run_engine.py
=> MNT: simplify extracting the run id in the RunEngine

bluesky/callbacks/mpl_plotting.py
=> MNT: Add no-op-QtAwareCallback

.travis.yml, bluesky/tests/test_bec.py
The PR is fixing minor CI issue related to changes in event-model v1.14.0.
=> TST: compatibility with event-model v1.14.0

.travis.yml
=> Move ophyd master build to 3.8.

doc/source/multi_run_plans.rst
stobs -> stubs is the typo, I hope the rest just improve the readability.
=> Small grammatical changes and one typo.

doc/source/api_changes.rst
=> DOC: finish writing the API change docs for the event loop refactor

.travis.yml, bluesky/run_engine.py, bluesky/tests/test_run_engine.py, dev-requirements.txt
This PR backports #1338 to the 1.5.x branch.
=> backport PR 1338 to 1.5.x branch

doc/source/api_changes.rst
This PR updates the release notes for v1.15.1.
=> update release notes for v1.5.7

bluesky/callbacks/mpl_plotting.py, bluesky/plan_patterns.py, bluesky/preprocessors.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py
New flake8 release generated new errors.
=> Address new flake8 errors.

bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py
This PR is a backport of #1351.
=> backport of PR 1351 (flyer descriptor development)

bluesky/preprocessors.py
wrong word used, one letter off
=> DOC fix typo

bluesky/callbacks/mpl_plotting.py, bluesky/plan_patterns.py, bluesky/preprocessors.py, bluesky/tests/test_run_engine.py
This PR is a backport of #1357.
New flake8 release generated new errors.
Some minor flake8 errors in the same files have been addressed.
=> address flake8 errors

doc/source/api_changes.rst
This PR adds release notes for v.1.6.2
=> release notes for v1.6.2

doc/source/api_changes.rst
This PR adds release notes for v1.5.8.
=> release notes for v1.5.8

doc/source/api_changes.rst
=> Release notes for v1.6.5

bluesky/plans.py
Current docstring led me down the wrong path as someone with no prior familiarity with the cycler package.
=> DOC: fix scan_nd docstring

doc/source/hardware.rst
closes #1393, see discussion there for motivation
=> DOC: mark position attribute optional

bluesky/callbacks/best_effort.py
This prevents tight layout from squishing the data to being too small
to see.
The hypothetical feature was merged to the Matplotlib default branch in 2015.
Reported via back channels via @cmazzoli (source of this picture)
pulled the two scans in question and pushed them through BEC locally:
=> ENH: make BEC fall back to a grid layout with lots of channels

doc/source/api_changes.rst
=> Release notes for v1.6.7

.flake8, .github/workflows/testing.yml
=> Place variable in matrix namespace.

.github/workflows/docs.yml, .github/workflows/flake8.yml, .github/workflows/publish-docs.yml, .github/workflows/testing.yml
=> Ensure that multi-step bash does not fail silently.

bluesky/tests/test_flyer.py
Noticed a small typo in the flyer tests.
=> TST: fix a typo in the flyer test

bluesky/callbacks/mpl_plotting.py
=> Bail in initialize_qt_teleporter if it is already done.

bluesky/plan_stubs.py
Minor typos in plan docstrings.
My pilot project contribution for the week. You're welcome! 😉
=> MNT: bps docstring typos

bluesky/tests/test_progress_bar.py
Fixed minor bug in the unit test for `ProgressBarManager`.
=> Fixed typo in a unit test for ProgressBarManager

bluesky/bundlers.py, bluesky/tests/test_flyer.py
Make sure that we only read the configuration values once per run rather than
once per Msg('collect').
@cjtitus noted that the configuration signals were called on every (partial) collect rather than the once per run that was expected.  The issue is that in the `async def collect` co-routine in bundlers we were reading the configuration before we sorted out if we needed to mint a new descriptor.  This moves the configuration reading into the block where we mint the descriptor to avoid wasted redundant  reads.
Test added.
=> FIX: only read the flyer configuration once per run

docs/source/contributing.rst, docs/source/index.rst
Attempting to add a how-to for releasing bluesky. Copied other content from `.github/CONTRIBUTING.md`.
=> DOC: add release instructions

bluesky/plans.py
=> DOC: small mistake in scan docstring

docs/source/api_changes.rst
Based on this list of changes: https://github.com/bluesky/bluesky/compare/v1.8.1...master.
=> DOC: release notes for v1.8.2

docs/source/hardware-interfaces.rst
Document additional hardware interface package.
=> DOC: document pycertifspec as hardware interface

docs/source/api_changes.rst
=> v1.8.3 release notes

docs/source/conf.py
To fix docs build.
As per https://github.com/sphinx-doc/sphinx/issues/10474
=> Fix language for sphinx 5.0

docs/source/api_changes.rst
=> DOC: Finish release notes for 1.9.0

bluesky/run_engine.py
This address the issue raised on slack https://nikea.slack.com/archives/C7QC41C1G/p1649160481932079 and closes #1415.
I ended up ripping out this entire cache as a) not useful b) tricky to get right
Below is the commit message:
-----
The way the bridging between ophyd objects <-> RE works for anything with a
Status object:
- ophyd returns a status object
- RE subscribes to the done callback on the status object
- that callback closes over an asyncio.Event
- RE also holds onto the asyncio.Event for use in _wait
- because the done callback runs on a different thread (the epics thread not
the RE thread) we use call_soon_threadsafe which schedules a sync functions
to be called by the EventLoop as soon as possible
- call_soon_threadsafe returns an asyncio.Handle object which _only_ lets
you …
=> Fix prompt task cleanup

README.md
Adding visibility to bluesky-base conda-forge package.
=> DOC: add bluesky base to readme

bluesky/plan_stubs.py, bluesky/preprocessors.py, bluesky/protocols.py, bluesky/run_engine.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_new_examples.py, docs/source/hardware.rst
Adds Locatable protocol
Fixes #1535 
It hasn't, see comments
=> Add Locatable

bluesky/protocols.py
=> DOC: minor typo fixed.

docs/source/tutorial.rst
Removing instruction which when performed says it is not necessary any more
Housekeeping
It's text
=> Remove useless instructions about install_kicker

bluesky/tests/test_run_engine.py
Fixes https://github.com/bluesky/bluesky/issues/1606
=> Simple fixes to placate flake8

bluesky/bundlers.py, bluesky/tests/test_run_engine.py
=> Added run_start_uid for stream_resource

bluesky/bundlers.py, bluesky/plan_stubs.py, bluesky/tests/test_external_assets_and_paging.py, bluesky/tests/test_seq_num_indices_in_sync.py
PR on top of #1651 that fixes test cases provided by @coretl 
Tests had become complex and it made sense to separate them
=> Fix Test Cases for "Enable collect for multiple detectors" (1651)

src/bluesky/bundlers.py, src/bluesky/callbacks/best_effort.py, src/bluesky/callbacks/broker.py, src/bluesky/callbacks/core.py, src/bluesky/callbacks/fitting.py, src/bluesky/callbacks/mpl_plotting.py, src/bluesky/callbacks/olog.py, src/bluesky/callbacks/zmq.py, src/bluesky/cntx.py, src/bluesky/commandline/zmq_proxy.py, src/bluesky/log.py, src/bluesky/magics.py, src/bluesky/plan_patterns.py, src/bluesky/plan_stubs.py, src/bluesky/plan_tools.py, src/bluesky/plans.py, src/bluesky/preprocessors.py, src/bluesky/run_engine.py, src/bluesky/suspenders.py, src/bluesky/tests/test_plans.py, src/bluesky/tests/test_streams.py, src/bluesky/utils/__init__.py
Fix ruff formatting bisecting strings on the same line
Fixing leftover issues from #1664
=> Fix Ruff Formatting Strings

pyproject.toml
Remove "nose" package from dev dependencies list
https://github.com/bluesky/bluesky/issues/1678
Ran "tox -e tests" in DevContainer:
1610 passed, 15 skipped, 34 xfailed in 487.71s (0:08:07) 
tests: commands succeeded
congratulations :)
=> Remove nose package from dev dependencies list

src/bluesky/utils/__init__.py
I messed up a re-base and un-fixed it.
=> MNT: (re)fix numpy2 compatibility

src/bluesky/callbacks/best_effort.py, src/bluesky/tests/test_simple_api.py
Three lines change - adding a default value for fields, and removing pytest xfail lines
=> apply suggestions to fix the xfail error and the case if no fields supplied

docs/progress-bar.rst, docs/utils.rst, src/bluesky/plans.py, src/bluesky/utils/__init__.py
Fixes #1775
Collates the documentation updates from 3 different past PRs.
=> Add collated documentation and type hints

src/bluesky/callbacks/mpl_plotting.py, src/bluesky/tests/test_callbacks.py
re-applied changed from https://github.com/bluesky/bluesky/pull/1523
=> re-apply the livescatter axes fix from PR 1523

src/bluesky/utils/__init__.py
=> Use qApp object from MPL's _create_qApp() function

src/bluesky/tests/test_tiled_writer.py
We were generate invalid descriptors in our tests, fix them.
CI should pass
CI should pass.
=> FIX: the validation on `dtype_numpy` got stricter, fix our test

src/bluesky/run_engine.py, src/bluesky/tests/test_event_loop_funcs.py
Add `bluesky.run_engine.autoawait_in_bluesky_event_loop`
Fixes #1855 
With the included test
=> Add autoawait_in_bluesky_event_loop

src/bluesky/protocols.py
=> Change to unpack arguments on `Movable.set`

src/bluesky/callbacks/best_effort.py
Extracted some logic from _setup_plots into 3 helper functions
=> Refactor the _setup_plots in BEC

src/bluesky/plans.py
=> typo - chaning / changing

src/bluesky/callbacks/stream.py
=> typo in LiveDispatcher docstring
