bluesky/tests/test_logbook.py
- Not to be confused with Python logging
- This does not actually use the olog, but it checks that a
correct message is passed to the handler that is normally
plugged into the olog.
=> TST: Test logbook

bluesky/callbacks.py
The old behavior was creating a new figure for each scan. The new behavior is using matplotlib's "current figure." Either behavior has disadvantages, but this choice makes it *possible* to plot multiple scans together. And of course it is still possible to plot scans separately -- just create a new figure in matplotlib.
Recall that we used to do it this way, which is why we show a legend with the scan ID.
The biggest downside with this new approach is that scans with different quantities with different dimensions can end up plotted together if users fail to create a fresh figure. But trying to be heuristically guess when users should have created a new figure sounds really hard to do simply or with reliable correctness.
=> API: LivePlot will use current fig, axes by default.

bluesky/global_state.py, bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/test_simple_api.py
We can do this elsewhere as well (in the RunEngine, perhaps also in the scan `detectors` setters) but this is a start.
=> Prohibit duplicates in gs.DETS and during event bundling

bluesky/run_engine.py
Bug caught today at HXN, when `register_mds` tried to call `copy.deepcopy` on an `EpicsMotor` instance. It should be been the repr of of that instance.
=> FIX: Store the repr of each scan arg, not the object itself.

bluesky/callbacks.py, bluesky/run_engine.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_documents.py, bluesky/tests/test_examples.py, bluesky/tests/test_scans.py
Internally, we pass around document names (start, stop, event, descriptor) as values of an Enum, `DocumentTypes`. This is for strictness and probably a minor performance boost. But we should not expose this to the users via subscriptions; we should expose the string names.
=> API: Expose doc names as strings, not enum values.

bluesky/callbacks.py, bluesky/register_mds.py, bluesky/run_engine.py, bluesky/schema/bulk_events.json, bluesky/tests/test_hardware_checklist.py
I spent a bit of time to see how bulk events from `collect` could be passed around, and here's what I came up with:
* Added a new document name `"bulk_events"` 
* It's a dictionary that's keyed on `descriptor_uid`, with lists of events as values
* It's verified with jsonschema (thanks @arkilic for the input)
* Individual events are by default not emitted, unless `emit_events` is set in the `collect` message (as in `Msg('collect', flyer, emit_events=True)`)
Feel free to reject it outright - I honestly have no clue how you intended to implement this. 
In any case, it works on my end and allows me to run tests. The speed-up is significant: 5000 events are stored in 3.5 seconds, giving an estimate of 45 seconds for our larger 65k event scans. I don't think that's an unreasonable number.
=> ENH: mds bulk events integration

bluesky/scans.py
lmfit raises on import in IPython 4.0. Since it's only used in one scan (`Center`) let's import it in the `__init__`. I don't usually like this pattern, but this is one time I think it's justified. I'll fix this on the lmfit side shortly.
=> REF: Do not import lmfit at the top of scans.

bluesky/run_engine.py
Like subscriptions, metadata can come from:
* kwargs to `RE.__call__` for metadata
* a special attribute of the plan passed to `RE.__call__`
* a Msg, wherein metadata can be determined after the call has begun
Unlike subscriptions, we don't need a new type of command to pass in metadata in a Msg. It is always good enough to put it in the 'open_run' Msg: we can't do it any later than that (it has to get into the RunStart) and it doesn't help to set it any earlier than that.
=> Look for metadata in md attribute of plan passed to RE

bluesky/callbacks.py, bluesky/qt_kicker.py
This code was bundled into callbacks.py, and it breaks the import if mpl is not using qt. This PR moves it into separate module. If the user is (1) using qt and (2) running mpl < 1.5, they need to import this module in order for LivePlot to work properly. Once we are in a post-1.5 world, this is vestigial and can eventually be removed completely.
=> REF: Move qt_kicker into separate module.

bluesky/callbacks.py, bluesky/scientific_callbacks.py
This adds a class for computing peak stats. It works like this:
```
ps = PeakStats(motor, det)
RE(ascan, subs=ps)  # or, in the simple SPEC-like API, ascan(motor, start, stop, interval, subs=ps)
```
When the scan finishes, the statistics are automatically computed, and the results are available via attributes of `ps`. So far, center-of-mass (`ps.com`) and min and max (`ps.min`, `ps.max`) are implemented. I need guidance from @cmazzoli or @ambarb on exactly how `cen` is supposed to work.
Since the pattern, "compute some things when a scan finishes" is likely to come up again, I implemented `PeakStats` on a base class `CollectThenCompute` which is more general. I'm interested in thoughts from non-CSX-ers on whether this is the right generalization. Notice that this does not use databroker; …
=> ENH: Add PeakStats callback

bluesky/broker_callbacks.py, bluesky/scans.py, bluesky/simple_scans.py, bluesky/tests/test_callbacks.py, bluesky/utils.py
In current master, the subscriptions attached to the simple scans are hard-coded. Customizing them is tricky because they inspect the scan to automatically do things like use `motor` attribute as the x axis in `LivePlot`.
This introduces two new user-modifiable attributes: `.subs`, which works the same way as usual, and `.sub_factories`, which expects a *function that accepts a scan instance and returns a callback*. It's the job of the function to inspect the scan and pass the right arguments to, for example, `LivePlot`. A collection of these "sub factories" is included in the PR. See for example `plot_first_motor`.
I don't imagine that users will be writing very many "sub factories," but they are crucial to providing the magical scan inspection in a way that lets users add and remove …
=> Simple (SPEC-like) scans are more customizable

bluesky/qt_kicker.py
There is now a function install_qt_kicker in qt_kicker which must be
called to install the kicker.
THIS WILL REQUIRE A CHANGE TO THE BEAMLINE CONFIG
The suggested pattern is:
from bluesky.qt_kicker import install_qt_kicker
install_qt_kicker()
closes #214
=> API/MNT: make qt_kicker not install on import

bluesky/broker_callbacks.py, bluesky/run_engine.py, bluesky/schema/run_start.json, bluesky/tests/test_callbacks.py, bluesky/tests/test_examples.py, bluesky/utils.py, doc/source/metadata.rst
This is a bit of a hodgepodge -- see commit msgs for details.
Note that `RE.ignore_callback_exceptions`, a boolean flag, has never actually worked until now. Sorry, @klauer.
=> Fix cb exceptions and tests; increase metadata test coverage

bluesky/run_engine.py
This issue was breaking `resume` when the interruption happened during the first data  point. Example Traceback:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-15-668cb5c44cab> in <module>()
----> 1 RE.resume()
/Users/dallan/Documents/Repos/bluesky/bluesky/run_engine.py in resume(self)
545         self._sequence_counters.clear()
546         self._sequence_counters.update(self._teed_sequence_counters)
--> 547         self._resume_event_loop()
548         return self._run_start_uids
549 
/Users/dallan/Documents/Repos/bluesky/bluesky/run_engine.py in _resume_event_loop(self)
558                 exc = self._task.exception()
559                 if exc is not None: …
```
=> FIX: Fix error when resuming during first event bundle.

bluesky/run_engine.py
This PR re-orders the post-run clean-up to be: stop(), collect(), deconfigure()
Fix for `deconfigure` in areadetector filestore clearing the `filestore_resource`, causing any further `collect()` calls to fail.
=> REF: post-run cleanup re-ordering

bluesky/run_engine.py
Most current scan plan metadata code is failing silently when their `md` properties are accessed prior to open_run. This should fix it. After a brief chat with @danielballan. 
I'd like to require an `md` attribute on all plans so we don't ever have missing metadata due to buggy code. However, according to @danielballan this won't work with Hugo's code...
=> FIX: plan metadata should be accessed at open_run

bluesky/run_engine.py, bluesky/tests/test_examples.py, doc/source/metadata.rst
In #240, several of us agreed that the *default* behavior should be that kwarg-based metadata should not implicitly update persistent metadata. Some advocated for a switch to turn implicit updating on and off. I came out somewhat against this. I would reconsider if users seem to want it. So far, the only users I've heard from want the explicit way, so that is what this PR does.
=> For now, don't implicitly update RE.md

bluesky/run_engine.py, bluesky/tests/test_examples.py
This addresses another subtle case that may have caused #226.
If some external code (in the case of #226, something in `pyOlog` or `requests`) takes control of SIGINT / Ctrl+C away from the RunEngine and then raises `KeyboardInterrupt`, the run will fail on a generic error. This PR captures `KeyboardInterrupt` and then calls `RunEngine.request_pause` as we normally do when we capture SIGINT.
If external code is behaving properly, a `KeyboardInterrupt` should never be raised. The external code should defer to the previously-registered SIGINT handler (that is, the RunEngine's handler) instead of raising KeyboardInterrupt. Therefore, this should be fixed upstream if the problem can be identified. At the same time, we can mitigate the issue in general --- it might come up again from other …
=> FIX: Catch KeyboardInterrupt from badly-behaving external code.

bluesky/__init__.py, bluesky/run_engine.py, bluesky/tests/test_examples.py
Add straightforward validation in `_create` and `_save` methods on `RunEngine` and tests to match. One of our *old* tests tripped the validation, exposing a pre-existing issue in the generator stack where the first Message is run twice. In every one of our built in scans, this Message happens to be 'create', so no harm was done.
Will revisit. This PR is full of debug prints and stuff to be removed before merging.
=> WIP: Validate order or create/save.

bluesky/broker_callbacks.py
@sbillinge @timoHMM This is how I would implement TIFF export.
```python
In [2]: from bluesky.broker_callbacks import exporter_factory
In [3]: f = exporter_factory('img', 'test/{h.start.scan_id}_{N}.tiff')
In [4]: header = db['0b96536a']  # example data with 20 images in a field named `'img'`
In [6]: !mkdir test
In [7]: f(header)
In [8]: !ls test
1_0.tiff   1_11.tiff  1_14.tiff  1_17.tiff  1_2.tiff   1_5.tiff   1_8.tiff
1_1.tiff   1_12.tiff  1_15.tiff  1_18.tiff  1_3.tiff   1_6.tiff   1_9.tiff
1_10.tiff  1_13.tiff  1_16.tiff  1_19.tiff  1_4.tiff   1_7.tiff
```
As you can see, it is simple to customize the filename based on any piece of metadata. It's all contained in the Header. See docstring for more.
=> ENH: Add tiff export function factory.

bluesky/run_engine.py, bluesky/tests/test_examples.py
Closes #253 
attn @ambarb -- does this message look good?
=> ENH: Better error message if 'sample' md is not a dict.

bluesky/register_mds.py
If a flyer yeilds no events, an empyt list bubbles it's way through
to pymongo which raises on a no-op bulk operation.
This is deployed as a hot fix at CSX.
=> FIX: do not try bulk insertion with no events

bluesky/scans.py
1. Fix docstrings to render sphinx correctly.
2. Unrelated cleanup in the scans.py file -- removing no-op code.
=> Scans docs fix

bluesky/plans.py
As originally conceived the D\*Plan family assumed that the motors
of interest only had 1 read key, however as implemented in the recent
versions of Ophyd EpicsMotor objects have 2 keys by
default (user_setpoint and user_readback) which causes D\*Plan to
fail (due to not knowing which of the keys to use as the 'primary' or
that semantically the those two keys are coupled).
This commit changes the plans to try to use the `Positioner` property
`position` while iterating through the Plan to extract the initial
position that should be returned to at the end of executing the Plan.
This breaks a key abstraction of the Plans (that they only interact with
the objects via the run engine), however this addresses a problem
discovered at the 11th hour without making any major architectural or API …
=> HACK: try to use motor.position in dscan

bluesky/examples.py, bluesky/plans.py, bluesky/simple_scans.py, bluesky/utils.py
Following up on #281, a little less hack-ish. Bluesky looks at the *order* of `read_attrs` and assumes the first one is the one it should use to (1) compute relative trajectories and (2) plot against in the subscription factories in `simple_scans.py`.
=> HOTFIX: Apply key-guessing heuristic to more places

bluesky/tests/test_things_that_touch_epics.py
follow-up to the py.test overhaul, which failed randomly after being merged master
=> TST: Skip unreliable epics-related test.

bluesky/run_engine.py
If the run engine has an exception raised during
- look up of the coroutine to run
- running the coroutine
throw the exception back at the generator.  This gives two
major features:
- tracebacks will include the line in the generator which yielded the
bad message
- allows generators to attempt to handle the excetion without killing
the run.
=> ENH: throw exceptions at generator

bluesky/run_engine.py, bluesky/tests/test_callbacks.py
The LiveTable test was failing because, I think, the lossy subscription was doing its job, dropping an event or two, and thus missing a row.
Also, this makes a non-breaking API change that was previously discussed: `RunEngine.subscribe_lossless` and `RunEngine.unsubscribe_lossless` are now public methods. Aliases for the private names are maintained in case someone (HXN?) is using them.
(These were originally (back in May) made private so that users didn't choke their processors by reaching for lossless subscriptions to liberally. That's not really the way private methods are supposed to be used, and in any case that imagined scenario has not been a problem.)
=> TST: Fix LiveTable test by using lossless subs.

bluesky/plans.py
This is a little piece of SPEC functionality that we are missing. The intention here is that the scan will end with a user-initiated pause + stop or abort.
@cmazzoli and @ambarb asked for `ct(num=0)`, but in Python we prefer not to use numbers as sentinel values. Instead we can use `ct(num=None)`, which is, if you think about it, a more accurate description of what is happening. I hope this is suitable for you. :- )
=> ENH: Support infinite ct: Count(num=None)

bluesky/broker_callbacks.py, bluesky/callbacks/core.py, doc/source/callbacks.rst
This PR:
* Overhauls organization of the callbacks documentation, leaving it much more readable.
* Documents "subscription factories" and `LiveRaster`, both previously unmentioned in docs.
* Provides new examples for automated data verification, automated TIFF export, and automated HDF5 export via suitcase. (cc @licode)
* Nukes `make_tiff_exporter` in favor of `LiveTiffExporter`, which (1) can write TIFFs out live, potentially letting @sbillinge's software crank in real time and (2) incorporates some of the functionality in @pavoljuhas's #263. It's still comparatively light but can be more easily extended for more specific use cases.
=> ENH/DOC: Overhaul callbacks doc, improve tiff export

bluesky/plans.py
This a change to PlanBase. ~~I'd like to get it in before users start taking data tomorrow.~~ (There are no users tomorrow after all.)
It would be nice to be able to search on object name:
```python
db(start_time='2016-01-19', detectors='fccd')
```
where mongo should interpret this as, "all of yesterday's scans that included that fccd as a detector."
This PR adds top-level fields to the Start Document for every category of object ('motor' or 'motors', 'detector' or 'detectors'). This is addition to storing the full reprs in 'plan_args', as we have been doing for some time now.
This also strips out some gratuitous complication from PlanBase. The 'derived_fields' concept is no more. It was supposed to make custom metadata "easy," but it really only made things more complicated.
=> Include object names in Start document

bluesky/callbacks/core.py
This was useful when callbacks were new but now they are gratuitous.
=> CLN: Remove logging that outputs whole documents

bluesky/tests/test_callbacks.py, bluesky/utils.py
As a reminder, when attaching subscriptions to a plan, we accept `plan.subs = cb` as a shortcut for subscribing to all documents. (The explicit way is `plan.subs = {'all': [cb]}`.) The shortcut is convenient but confusing in a couple ways. It is accomplished using a descriptor that normalizes the input.
Given the confusion this has caused, removing the shortcut altogether is under discussion. But that's not what this PR does. This PR merely makes it a little more clear what is happening with subs. Maybe it goes far enough and we will not need to to remove the shortcut?
```python
In [1]: from bluesky.simple_scans import AbsScan
In [2]: ascan = AbsScan()
```
Before:
```python
In [3]: ascan.subs
Out[3]: {}
```
After:
```python
In [6]: ascan.subs
Out[6]: {'all': [], 'descriptor': [], 'event': …
```
=> API: Subs is always a dict of empty lists, including all valid keys.

bluesky/plans.py
As discovered by @ambarb, if you include your 'motor' as one of your 'detectors' (which is a reasonable thing to do) `Plan` tries to stage it twice and blows up. This is a simple fix.
=> FIX: Avoid staging objects redundantly.

bluesky/run_engine.py
This came up during the tutorial today. When a scan is paused, all motors should be stopped.
I can't think of a reason that this would cause a problem -- if your scan can't recover from a stop, then you shouldn't be using checkpoints -- and it's easy to think of case where the current behavior causes a problem.
=> MNT: All motors should be stopped during a pause.

bluesky/run_engine.py
The data comes back from ophyd as a dict of dict keyed on 'value',
'timestamp'.  Previously this was inserting the stings 'value',
'timestamp' into the descritor, rather than the information.
=> FIX: correct inserting of configuration data

bluesky/examples.py, bluesky/utils.py
- As @klauer pointed out awhile back, read() and describe()
return OrderedDict objects, so we can figure out the first
element in read_attrs but looking at these; we don't need
to add read_attrs/describe_attrs to the list of things
bluesky has to know about.
- This commit removes all refs to `read_attrs` from the codebase.
Do not merge until https://github.com/NSLS-II/ophyd/pull/265 is merged.
Closes #333
=> REF: Do not require objs to have read_attrs.

bluesky/run_engine.py
In NSLS-II/Bug-Reports#80 Yugang posted some text which 
highlighted a typo in our Exception text. This fixes that
=> Fix typo in exception

.travis.yml, bluesky/broker_callbacks.py, conda-recipe/meta.yaml
bluesky was getting tifffile through pims making tifffile a runtime dep.  
Now that pims 0.3.3 does not have tifffile as a runtime dep, we should make
tifffile a dep of bluesky.
=> Add tifffile as a dependency

bluesky/__init__.py, bluesky/run_engine.py, bluesky/tests/test_examples.py
If a run is interrupted but not exceptions are raised (which IIRC
can only occur because the RunEngine is paused or stopped) users
can use this flag to raise a special exception, aimed at interrupting
user scripts or functions that call the RunEngine.
- Add public raise_if_interrupted flag and private _interrupted flag.
- Add `RunEngineInterrupted(Exception)`.
- Remove `RunInterrupted(KeyboardInterrupted)` which was never used.
- Test.
=> ENH/API: Add raise_if_interrupted option and new Exception

bluesky/run_engine.py
On the collection side, we make use of the fact that `describe()` returns an `OrderedDict`, but we throw that information away when we put it in MDS. I would like to store that order in MDS so I can use it on the analysis side. Specifically, the order has given us a way to inject a useful heuristic: the first key is taken to be the "primary" or default key to use in plotting, etc.
Currently, we obtain this key in various places in bluesky by calling `describe()` on the object. Obviously, on the analysis side we cannot do that. It would be better to store the order in the documents.
We are already storing the mapping of data keys to object names. (This is how configuration is grouped with the data keys that it applies to.) In this PR, I add a list of `object_keys` mapping each object name …
=> ENH: Record data key order as a list in descriptor.

bluesky/plans.py
Recall the "baseline readings" use case. Building baseline readings
in by default may wait until the next cycle, but this lays the
groundwork by making the primary event stream addressable by name.
=> ENH: Name the 'main' event stream in built-in plans.

bluesky/run_engine.py, bluesky/utils.py
Closes https://github.com/NSLS-II/wishlist/issues/105
This makes the `SignalHandler` hold onto control of the signal until the context block has exited.  Previously the handler would clean it's self up after the first signal it received which means hitting C-c three or more times could result an a KeyboardInterupt being raised deep in the code.  If this happens in the `finally` block it can leave the RE (and the hardware) in an inconsistent state.
=> Api kb interupts

.travis.yml, bluesky/examples.py, bluesky/plans.py, bluesky/tests/test_devices.py, bluesky/utils.py, conda-recipe/meta.yaml
As discovered at CSX, putting a device and a subdevice into the list of (detectors + motors) causes the RunEngine to error when it see the same reading twice. In this PR, we inspect (sub)device ancestry to make sure a device and its ancestor are not both read.
In each plan, we:
* Determine a unique list of all devices to be triggered and waited on -- that's detectors only.
* Determine a (potentially different) unique list of all devices to read -- that's detectors and motor(s).
As an aside, notice that using the convenience functions introduced in this PR, the `root` attribute of object could potentially be factored out and ultimately removed from ophyd if we want. One problem at a time.
=> FIX: Avoid reading device and its subdevice.

bluesky/callbacks/core.py
If a descriptor has not been processed some of the internal state
may not be set.
=> FIX: check assumptions in stop processing

bluesky/callbacks/core.py
This solves the first of the three problems enumerated in #391 and should make the spec file writer immediately usable.
=> Fix Bad #L line in spec callback

bluesky/run_engine.py, bluesky/schema/run_start.json, bluesky/tests/test_examples.py, doc/source/metadata.rst
We tried to encourage people to use dictionaries to record their sample information by requiring that the field called 'sample' be a dict. This has turned out to be more annoying that helpful. Sometimes you just want sample to be a string. The error is off-putting and more likely causes users to simply avoid the metadata feature than to discover the joy of dictionaries.
This would require a corresponding change in metadataservice and the (so far unused) event-model repo. Is this OK with you @arkilic?
This one's for you, @lwiegart. (But I have come to agree.)
=> MNT: Allow sample to be dict or string.

bluesky/broker_callbacks.py
caught and hot-fixed at XPD, where this was tested at users and
worked, save for this dumb typo
=> FIX: typo in LiveTiffCallback

bluesky/qt_kicker.py, bluesky/tests/test_vertical_integration.py, bluesky/utils.py
Addresses another piece of #189
Also a little test refactor suggested by @ericdill
=> MNT: Deprecated qt_kicker module; move it to utils

.travis.yml, bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/utils.py, doc/source/callbacks.rst, doc/source/metadata.rst, doc/source/state-machine.rst
- Former minimal working RunEngine instance was
`RunEngine({'owner': '', 'group': '', 'beamline_id'})`
- New minimal working RunEngine instance is
`RunEngine({})`
This is lighter for testing, debugging, teaching. It also removes
the domain-specific word "beamline" from the required lexicon.
I rewrote the metadata section of the docs, should be much
more clear.
=> MNT/DOC: No metadata fields are required.

bluesky/plans.py, bluesky/run_engine.py
This PR is based on #345 which should be merged first.
See docstring of `monitor_context` for usage and details.
=> Add monitor_context (and -- unrelated -- sundry RunEngine docstrings)

bluesky/run_engine.py
Current situation:
1. A 'monitor' Msg is processed -> `obj.subscribe(cb, *args, **kwargs)`
2. Plan is paused; monitoring is correctly suspended -> `obj.clear_sub(cb)`
3. Plan is resumed; monitoring is reapplied but *the original args and kwargs are dropped* -> `obj.subscribe(cb)`
This PR stashed those and args and kwargs and correctly reapplies them upon resuming.
=> FIX: Cache kwargs for subscribe.

bluesky/run_engine.py, bluesky/tests/test_examples.py
Previous, if interrupted before the first 'checkpoint' message, it died. Now, unless it sees a 'clear_checkpoint' message, it rewinds to the beginning if interrupted.
=> RunEngine starts in a resumable state

bluesky/broker_examples.py, bluesky/examples.py, bluesky/plans.py, bluesky/run_engine.py, bluesky/tests/abort.py, bluesky/tests/test_examples.py, bluesky/tests/test_scans.py, doc/source/api_changes.rst, fuzz/fuzz.py
* `Msg('wait_for', futures)` -> `Msg('wait_for', None, futures)`. The second position in a Msg, `Msg.obj`, is always a Device or Signal. The current implementation was just a mistake, according to @tacaswell.
* Consistency: 'trigger' and 'set' messages call it a 'block_group'; 'wait' messages called it a 'group'. Now they all call it a 'group'.
=> API: Fix wait_for signature; use a consistent name for block_group/group.

bluesky/plans.py, bluesky/tests/test_generators.py, doc/source/plans.rst
This enables usage like:
```python
@planify
def plan():
return [ct(), sleep(5), ct(), rel_set(motor, 2), ct()]
```
It's just an experiment.
One big benefit is that this provides de-facto API documentation for every kind of Msg, which has till recently been completely absent or buried in the RunEngine private method docstrings.
=> ENH: Add a stub plan for every command in the command_registry.

bluesky/run_engine.py
Closes #415
I'm not doing anything with this, but now we have the hook when we need it / want to play with it. I don't think the Devices need to distinguish between 'pause' and 'suspend', so both actions call `device.pause()`.
=> ENH: Support optional 'pause' and 'resume' methods on Devices.

bluesky/utils.py
Add a helper function that registers an IPython magics to run call
the run engine.
This function can/should be called in the beamline configuration
once the 'canonical' runengine has been set up.
This is support work for a coming PR from @danielballan
=> ENH: add MAGICs

bluesky/plans.py
This will no longer mask exceptions, but will pass bogus values
up the generator stack and will not always let plans fully handle
the exceptions.
=> FIX: plan_mutator exception handling (sorta)

bluesky/register_mds.py, bluesky/tests/test_vertical_integration.py, conda-recipe/meta.yaml
Reverts NSLS-II/bluesky#421
This makes it possbile to use mds 3.2 with bluesky master again.
=> Revert "CLN: Remove register_mds; simplified MDS interface obviates it."

bluesky/plans.py, bluesky/run_engine.py
Bug: In this scenario, the `flyer` is never staged.
```python
c = Count[])
c.flyers = [flyer]
```
Perhaps no one has encountered this bug yet because no one had written a flyer that *needed* to be staged until today. As a reminder, this will not affect any existing flyers that don't implement stage/unstage. The RunEngine checks to see if `msg.obj` has a stage/unstage method before attempting to call it.
The second commit may be fixing a nonexistent problem, but it feels like the right thing to do. Preventative medicine.
=> FIX: Stage Plan.flyers.

bluesky/plans.py, bluesky/run_engine.py
Testing raw_input in py.test is a can of worms I don't want to open this week, but this code works:
```python
from bluesky import RunEngine, Msg
from bluesky.examples import motor, det
from bluesky.plans import tweak
def plan():
p = yield Msg('input', prompt='where now?')
print('moving to', p)
yield Msg('set', motor, float(p))
RE(plan())
RE(tweak(det, 'det', motor, 1))
```
=> Add a new 'input' Msg that takes raw_input while running event loop in background

bluesky/plans.py, bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/utils.py
See commit messages for details. There are some small unrelated cleanup commits mixed in here.
Demo with DEBUG-level logging turned on:
```python
import logging
from bluesky import RunEngine, Msg
from bluesky.plans import sleep
logger = logging.basicConfig(level=logging.DEBUG)
RE.verbose = True
def plan():
while True:
yield from sleep(1)
```
Look for the `^C`s in the output below:
```python
In [1]: RE(plan())
INFO:bluesky.run_engine_id4355736240:Change state on <bluesky.run_engine.RunEngine object at 0x1039f42b0> from 'idle' -> 'running'
DEBUG:bluesky.run_engine_id4355736240:Processing sleep: (None), (1,), {}
DEBUG:bluesky.run_engine_id4355736240:Response: None
DEBUG:bluesky.run_engine_id4355736240:Processing sleep: (None), (1,), {}
^C …
```
=> Change Ctrl+C behavior

bluesky/run_engine.py
* Remove the two DEBUG-level log messages per Msg processed. The flood this produced is not often useful, and it can always be re-created using `RE.msg_hook = lambda msg: self.log.debug(repr(msg))`
* Make log entries about emitted documents more detailed, including uid and data keys where applicable.
=> MNT: Make log messages more useful.

bluesky/plans.py
First bug found in v0.5.0. Fix is tested at XPD (and presenty source-installed there).
Example of failing case:
```python
inner_product_scan([det], num, device.subdevice1, start1, stop1, device.subdevice2, start2, stop2)
```
=> FIX: stage_context neglected to separate devices

bluesky/plans.py, bluesky/run_engine.py, bluesky/tests/test_examples.py
This fixes a subtle bug where there are some messages which are
not (always) safe to replace due to being part of a context pair.
This needs testing / another set of eyes.
=> API/FIX: clear msg cache on un-cacheable msg

bluesky/plans.py
This fix only works on py3.5, on py3.4 this improves the reported name
from `__call__` to `cls_plan`.
=> FIX: improve the name reported in mds

bluesky/run_engine.py, bluesky/utils.py
It turns out that `np.ndarray` is not a subclass of `np.generic`. We need the latter to catch scalars and the former, obviously, to catch arrays.
While I'm here, I moved some stuff to utils.py.
=> Fix sanitize np

bluesky/spec_api.py, bluesky/tests/test_simple_api.py
For all of the plans is spec_api make the `plan_name` value in the
run_start metadata match the plan name.
attn @ericdill
=> FIX: correct all spec names

bluesky/plans.py, bluesky/spec_api.py, doc/source/plans.rst
- Other preprocessors (fly_during, relative_set, reset_positions, etc.) do
not have _mutator in the name -- only the mutator utils do.
=> DOC: Document `baseline` and bike-shed the name (with back-compat)

bluesky/run_engine.py
Edge case: When the RunEngine cleans up from a bad exit, it should clear the per-run caches.
=> MNT: Ensure per-run state is always cleared.

bluesky/plan_patterns.py, bluesky/plans.py
Allows motor trajectories to be determined purely from scan metadata.
Supercedes #454, which will require the tweaks mentioned in that PR - after we agree on this implementation.
=> ENH: plan patterns

bluesky/plans.py, bluesky/tests/test_simple_api.py
Yeah, at least the second time around with these motor reprs; this time in the plan pattern args.
Added bson encode test in test_simple_api. This should not add a bson dependency as it is pulled in through metadatastore (which I assume is in `nslsii_dev_configuration`)
=> FIX: plan pattern args motor repr

bluesky/plans.py, bluesky/spec_api.py, bluesky/tests/test_generators.py, bluesky/tests/test_new_examples.py, doc/source/plans.rst
* Rename all the generator instance preprocessors to end with `_wrapper`.
* Add a `make_decorator` utility function that converts a generator instance wrapper to a generator function decorator.
* Ship a `*_decorator` variant of each `*_wrapper`. These are not yet documented, but they will be once I have the time to explain them carefully.
=> Subs wrapper

bluesky/run_engine.py, bluesky/tests/test_suspenders.py
A little due-diligence testing uncovered a mistake in the deferred pause processing. This probably did not  and will not affect production; it only goes awry when the `RunEngine.loop` is not the default event loop.
=> FIX/TST: Test pausing from suspended state; fix bug in deferred pause logic

bluesky/spec_api.py
In #455, `ct` was left out. I'm not sure whether that was intentional, but I think `ct` should also implement baseline.
=> ENH: ct should also read gs.BASELINE_DETS

bluesky/global_state.py
- Remove unused gs.COUNT_TIME.
- Change default of gs.MD_TIME_KEY to a name that does not collide with any
official AreaDetector jargon.
=> API: changes to count time in global state

bluesky/plans.py, bluesky/spec_api.py, bluesky/tests/test_new_examples.py
Refactor the infinite count.
The previous implementation was
interacting badly with `planify` which resulted in the infinite loop
while building the list of plans to return (rather than an infinite
generator being handed to the RE).
Closes https://github.com/NSLS-II/Bug-Reports/issues/112
=> FIX: infinite count

bluesky/spec_api.py
The tweak/tw plan was basically written to prove the point that, yes, SPEC's concept of "tweak" is within the scope of the Python language. When I see someone actually use it at a beamline, I'll take the trouble to write a test. ;- )
Closes https://github.com/NSLS-II/bluesky/issues/483
=> FIX: Pass args through to tweak.

bluesky/plans.py
Very minor change that removed some no-op messages, just to make things cleaner in a basic example that I find myself using a lot when teaching about plans.
Before:
```python
In [2]: list(count([]))
Out[2]:
[open_run: (None), (), {'plan_name': 'count', 'num_steps': 1, 'plan_args': {'detectors': [], 'num': 1}, 'detectors': []},
checkpoint: (None), (), {},
create: (None), (), {'name': 'primary'},
save: (None), (), {},
close_run: (None), (), {}]
```
After:
```python
In [2]: list(count([]))
Out[2]:
[open_run: (None), (), {'detectors': [], 'plan_args': {'detectors': [], 'num': 1}, 'plan_name': 'count', 'num_steps': 1},
checkpoint: (None), (), {},
close_run: (None), (), {}]
```
=> MNT: Don't emit create/save with no reads between.

bluesky/plans.py, bluesky/tests/test_new_examples.py
Example of where this is useful:
```python
inject_md_wrapper(multi_run_plan, {'last_dark_frame_uid': '...'})
```
=> ENH: Add inject_md_wrapper and inject_md_decorator.

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
Move the idle -> running transition into `_run` to prevent the case
where the RE would be in a running state, but the code between where it
was flipped and where the `_run` coro was actually started raised.
This left the RE in a state where it was 'running', but had to task,
thus no part of the API (which relies on the finally block of the coro
to flip the RE back to idle) would be able to return the RE to an idle state.
attn @klauer I think this is the issue Yong had.
@cmazzoli @ambarb I think this also fixes an issue you have seen.
=> MNT: handle switching state to 'running' carefully

bluesky/examples.py, bluesky/plans.py, bluesky/run_engine.py, bluesky/tests/conftest.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_run_engine.py, bluesky/tests/utils.py
- do we want to try to reset motors on abort? The last commit makes it so that we do, but we might want to replace `CanceledError` with a custom one to catch a la `GeneratorExit` in `finalize_wrapper` to by-pass the clean up
- we probably want to re-think how pausing works.  Instead of stopping the loop in `request_pause` we stash an exception in `self._exception` and then once it bounces through the plans and then stop from with in the `_run` co-routine 
- `_exception` can now get clobbered a couple of ways, should maybe make it a stack?
=> Fix motor reset

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
When the pause method is called on a device it may raise a
`NoReplayAllowed` exception which will indicate to the RE that it
is not safe to re-issues any of the commands to it, thus we must
reset the checkpoint cache (if any).
=> ENH: signal devices are not rewindable via pause

bluesky/plans.py, doc/source/api_changes.rst
When bluesky was moving fast, we communicated API changes by word of mouth. This is an attempt to put us on track with format API changes documentation for every version.
attn @hhslepicka @yugangzhang @chiahaoliu
=> Catch up API changes documentation and fix some docstrings.

bluesky/run_engine.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_suspenders.py
This still needs 
- more evil tests
- There is now a path to `halt` and for a plan to kill the RE dead as `GeneratorExit` is not a sub-class of `Exception` for exactly this reason.
=> Enh re exception handling

bluesky/tests/test_devices.py, bluesky/utils.py
Removing an item during a list traversal is a no-no, @tacaswell
=> FIX: separate_devices iteration bug

bluesky/callbacks/broker.py
hotfixed by editing the conda-installed source in XPD's collection and collection-dev environments
=> FIX: LiveTiffExporter was missing an import.

bluesky/plans.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, doc/source/api_changes.rst, doc/source/index.rst, doc/source/plans.rst
- Add `monitor_wrapper` and `monitor_decorator`.
- Document `make_decorator` and `run_wrapper`.
- Document the difference between _wrapper and _decorator funcs.
- Rename `fly_during_wrapper` -> `fly_wrapper` but keep back-compat.
- Bike-shed order functions are listed in API docs.
- Change `make_decorator` to return proper decorators.
=> ENH/TST/DOC: Add `monitor_wrapper`

bluesky/plans.py
If an explicate group is not passed in, but we are requested to wait
generate a local one-use group.
=> FIX: actually wait in abs/rel_set if no group

bluesky/callbacks/core.py, bluesky/tests/test_callbacks.py
Example: If a user adds a field with an 'array' dtype, LiveTable silently skips it. This confused me for a minute earlier this week.
=> When LiveTable skips an unrecognized dtype, warn

bluesky/callbacks/olog.py
- Use 'plan_name', often more descriptive than 'plan_type'.
- Only assume that plan has metadata that is ensured by RE. (Do not assume
it has 'plan_args'.)
Solves issue where user makes custom plan, omits plan_args metadata, and see that olog callback is not run.
=> MNT: Tweak default log templates.

bluesky/global_state.py, bluesky/plans.py, bluesky/run_engine.py, bluesky/spec_api.py, bluesky/tests/test_simple_api.py, bluesky/utils.py, doc/source/plans.rst, doc/source/simple_api.rst
- return runstart uid from `open_run`
- bounce returned values through single_gen
- planify returns a tuple of collected results
This needs some tests and maybe a re-think of what `planify` returns.
=> ENH: return values from co-routines/generators

bluesky/run_engine.py
This makes the code work the way that @danielballan thought it
worked.
All objects that are set/trigger/kickoff/collect will have their status
objects hooked up to a an `asyncio.Event` and if the Status object
reports that it failed will cause an exception to be raised.
Before this, if there was not a non-None group, the RunEngine would not
check the success or failure of the action.
=> FIX: allow `None` to be a valid group for waiting

bluesky/callbacks/core.py, bluesky/register_mds.py, bluesky/run_engine.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_run_engine.py, bluesky/utils.py, doc/source/callbacks.rst
After a discussion with @tacaswell. Anything that's slow should be subscribed on a separate process somehow (outside of the scope of this PR).
Proof-of-concept / seeing what this looks like / seeing what tests fail
=> SNIP: remove lossy subscriptions

.gitignore, bluesky/plans.py, bluesky/tests/test_new_examples.py, doc/source/api_changes.rst
Discussed offline. To summarize, `finalize_decorator` accepted generator *instance* and did not accept a generator *function*, which means it would work only the first time it was used. After that, the `final_plan` generator instance would be exhuasted, and the decorator would silently do nothing.
It turns out that no other preprocessors we have written so far have this problem, so the cleanest fix is just to write out a special `finalize_decorator`, not using `make_decorator(finalize_wrapper)`.
Obviously, this is thoroughly tested.
=> Fix finalize dec

bluesky/broker_examples.py, bluesky/examples.py, bluesky/global_state.py, bluesky/plans.py, bluesky/tests/conftest.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_ramp_plan.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_scans.py, bluesky/tests/test_simple_api.py, bluesky/utils.py, doc/source/api_changes.rst, doc/source/callbacks.rst, doc/source/documents.rst, doc/source/hardware.rst, doc/source/index.rst, doc/source/metadata.rst
Two motivations for this change:
1. It is now easy to make simulated hardware that returns realistic data for testing analysis workflows when the beam is down. See docstrings for suggestive examples.
2. The `examples.py` has built up a lot of cruft as did not serve as a nice entry point for developers trying to understand the bluesky interface.
Still to do (in a later PR): unify the three different implementations of simulated flyers.
=> Overhaul examples

bluesky/examples.py, bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py
These relies on changes to ophyd to allow a `success` kwarg in stop.
=> MNT: stop all movable objects as successful

bluesky/examples.py, bluesky/tests/test_scans.py, bluesky/tests/test_simple_api.py
* Add a setpoint to the motor instances. This makes it easier to see the difference between `.name` and `.describe().keys()`. It's confusing when there is only one key.
* Refactor how read vs. conf works to make it more like ophyd.
=> Make example hardware more realistic

bluesky/run_engine.py, bluesky/tests/test_suspenders.py
Just a convenience. It's annoying to have to write a loop over `RE.remove_suspender` every time you want to turn suspenders off.
=> ENH: Add RE.clear_suspenders()

bluesky/run_engine.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py
Stop-stopping bug in the RunEngine monitoring code organized the configuration into the descriptor with the wrong layout. The currently-deployed code acquired data without complaint but the databroker errors (rightly) when it can't find the keys it expects.
In addition to this PR, which should probably be merged and deployed ASAP, we should:
* add more tests that exercise configuration (I will add at least one to this PR later today, but I have to teach first.)
* make the event_model stricter (mentioned way back in https://github.com/NSLS-II/bluesky/issues/134) -- this should have produced an error at acquisition time!
Can you look into this next, @licode? Reference for how the Event Descriptor is organized: http://nsls-ii.github.io/bluesky/event_descriptors.html
=> FIX: _monitor was packing configuration wrong.

bluesky/plans.py, doc/source/api_changes.rst
- The docstring states that it does not wait by default. This changes makes the
docstring correct.
- All other plans that have a `wait` keyword set to False by default, except
`mv` which is a convenience.
=> FIX: complete should *not* wait by default

bluesky/run_engine.py, bluesky/tests/test_callbacks.py, doc/source/callbacks.rst, doc/source/debugging.rst
We should have done this back when we removed the lossy/lossless exceptions distinction. In the current code, if MDS fails to insert your documents, all you get is a warning.
attn @gjwillms
=> API: Change default to ignore_callback_exceptions=False.

bluesky/run_engine.py
For better or worse, the convention we have adopted (I think in deference to SPEC?) is that seq_num starts at 1. Callbacks like LiveRaster rely on this.
=> FIX: monitor seq_num should start 1 for consistency

bluesky/plans.py, bluesky/tests/test_generators.py
If the flag is true, yield a pause() message before finishing the clean up.
Does this seem useful @NSLS-II/dama ?
=> ENH: add pause_for_debug flag to finalize_wrapper

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
This PR does not change the default behavior of the RunEngine.
But if `RE.max_depth` is set (say, in the beamline config), `RE.__call__` will check the current stack depth and error out if it think it is being called from inside a function. The error message includes the URL of the specific docs section addressing why this is harmful and what to do instead.
There is no good non-null default for `max_depth` because Python and IPython operate with different base stack depths. And I would guess that different versions of IPython vary in this respect.
In the built-in interpreter:
```
>>> RE = RunEngine({})
>>> RE.max_depth = 2
>>> RE([])  # allowed
[]
>>> (lambda: RE([]))()  # disallowed
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 1, in <lambda> …
```
=> Allow optional max_depth to error when RE is called in a function

bluesky/callbacks/broker.py, bluesky/callbacks/core.py, bluesky/callbacks/olog.py
For the plotting callbacks, here `event` just performs the document munging and calls `update(...)` to update the caches and line objects do the redraw. The arguments to `update` are just numbers, and this provides a good hook for subclasses that want to alter those numbers without mutating the document.
Also, all callbacks that inherit from `CallbackBase` now call super() to play well with multiple inheritance. We don't actually *use* MI anywhere in the package, but now we play nicer with user MI code.
=> REF: Make callbacks call super(); split plot drawing into update().

.travis.yml, bluesky/callbacks/__init__.py, bluesky/callbacks/core.py, bluesky/tests/test_callbacks.py, doc/source/callbacks.rst
In summary:
``` python
cb = LiveFit(lmfit_model, 'det', {'x': 'motor'}, init_guess)
cb.result  # an lmfit.ModelResult
```
See documentation in this PR for details.
`LiveFit` itself does not introduce an lmfit dependency or any other new dependency -- it expects the user to pass in an lmfit model (or anything that provides that interface) -- so I put it in `bluesky/callbacks/core.py`.
Includes a test and minor adjacent code and docs cleanup.
=> ENH: Add LiveFit, a callback that integrates with lmfit.

bluesky/plans.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_ramp_plan.py
Change the default stream name for monitors from `<signal_name>-monitor` to just `<signal_name>`. The original default was both unnecessarily verbose and not a valid Python identifier (due to the `-`), which is fine but less convenient to access within a document / document stream because it is not a valid attribute name.
Since monitoring was completely broken in the last tagged release, this is a cost-free API break. We just need to notify CSX and SRX where fixed versions of monitoring are source-installed. They can keep the old names (it's configurable through the 'monitor' plans) or transition to the new ones at their preference.
attn @cmazzoli @ambarb @gjwillms @imrealkaren
=> API: Change default monitor name.

bluesky/callbacks/core.py, bluesky/examples.py, doc/source/callbacks.rst, doc/source/cookbook/index.rst, doc/source/cookbook/scan_gaussian.py, doc/source/cookbook/scan_gaussian.rst, doc/source/index.rst
There a couple ways that projects automate generating examples. I looked at a couple and didn't see a clear winner, so I'd like to stick to a basic manual approach until it's more clear which solution best fits bluesky.
=> Improve LiveFit examples (use noisy data) and add new Cookbook section

bluesky/examples.py
Need this to test `db.export` and it's good to advertise this best-practice anyway.
=> MNT: Specify a root in FileStore resource generated by example.

doc/source/debugging.rst
Content rescued from rewrite of top-level docs' examples (a.k.a. cookbook) section. This was not really much of an "example," more like a wall of text. It belongs here in bluesky.
=> DOC: Move debugging details from top-level docs.

bluesky/plans.py, bluesky/spec_api.py, doc/source/plans.rst
We got carried away with our love of `ChainMap` and made the plans code more complicated than it needs to be. We only need `ChainMap` in places where we want to avoid mutating the lowest-precedence dict. So, we *do* need it in the RunEngine, where we want to compose with `RE.md` without mutating it. But we *don't* need it inside plans, where we are composing with a hard-coded, single-use local var that we can always safely mutate.
=> Simplify md composition

bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py, bluesky/utils.py
If the handler has accumulated 10 sigints without it being cleared by
the RunEngine, something is going very wrong.  Let python raise a
KeyboardInterupt.
This needs a bit of consideration to make sure that we are properly resetting the count from the RE.
=> ENH: add hard-kill option to SignalHandler

bluesky/run_engine.py, bluesky/suspenders.py
* Nice repr renders `RE.suspenders` easier to understand.
* The message when suspension is requested now includes a time.
* A new message comes out when conditions return to nominal and suspender begins sleeping, giving the time when that particular suspender will release its hold. (Other suspenders may continue to have a hold, and that will be clear from these messages.)
=> MNT: Add repr and additional prints to suspenders.

bluesky/utils.py
Gives time stamps, uses the object name and keeps things alligned
```
In [121]: RE.msg_hook = ts_msg_hook
In [122]: RE(bp.count([det], num=5, delay=1))
11:02:55 stage             -> det             args: (), kwargs: {}
11:02:55 open_run          -> None            args: (), kwargs: {'num_steps': 5, 'plan_name': 'count', 'plan_args': {'detectors': ['SynGauss(name=det)'], 'num': 5}, 'detectors': ['det']}
11:02:55 checkpoint        -> None            args: (), kwargs: {}
11:02:55 trigger           -> det             args: (), kwargs: {'group': 'trigger-f4a928'}
11:02:55 wait              -> None            args: (), kwargs: {'group': 'trigger-f4a928'}
11:02:55 create            -> None            args: (), kwargs: {'name': 'primary'}
11:02:55 read              -> det             args: (), …
```
=> ENH: add nicely formatted msg_hook hepler

.travis.yml, bluesky/run_engine.py
We are never actually creating extra tasks so this is useless and the
traceback object is keeping the failed task alive so we see it every
time.
We are creating handles, not Tasks, elsewhere in the code.
If we do start to create other tasks, we must keep track of them to
clean them up rather than relying on a global weak-ref dict in the
Task class.
attn @ambarb
=> FIX: do not keep old exceptions around

.travis.yml, bluesky/plan_patterns.py, bluesky/plans.py, bluesky/spec_api.py, requirements.txt, test-requirements.txt
Use `toolz.partition` instead of `boltons.chunked`.
Also, remove doct as a core dep (it's only use in `bluesky.callbacks.broker`) and matplotlib.
We don't need both toolz and boltons, and it seems more likely we'll want more things from toolz in the future. I also have the impression it's more widely used than boltons.
There is good test coverage of the relevant sections of bluesky.
=> REF: Drop boltons dependency by using toolz (already a dep).

bluesky/plans.py, doc/source/api_changes.rst
Of the options discussed in #652, I vote for removing the ambiguously-named 'num_steps' from metadata altogether. I volunteer for cleanup of any breakage in BL configs.
Closes https://github.com/NSLS-II/bluesky/issues/652
```
$ git grep -A 1 num_points
bluesky/callbacks/core.py:    num_points : int, optional
bluesky/callbacks/core.py-        number of points to sample when evaluating the model; default 100
--
bluesky/callbacks/core.py:    def __init__(self, livefit, *, num_points=100, legend_keys=None, xlim=None,
bluesky/callbacks/core.py-                 ylim=None, ax=None, **kwargs):
--
bluesky/callbacks/core.py:        self.num_points = num_points
bluesky/callbacks/core.py-        self._livefit = livefit
--
bluesky/callbacks/core.py:            x_points = np.linspace(xmin, xmax, …
```
=> API: num_steps -> num_points; add num_intervals as well.

bluesky/plans.py, bluesky/tests/test_plans.py, bluesky/tests/utils.py
closes #680
Fix bug where the motors in inner and outer scans were randomized
Added motors in order when we add extents friends to the start document
See #680 
New tests added
=> FIX: make sure motors are in the right order

bluesky/tests/__init__.py, bluesky/tests/test_devices.py
This relies on a not-yet-merged change to ophyd
=> TST: do not skip ophyd tests if libca is not installed

bluesky/callbacks/scientific.py
Subtracting booleans (via numpy.diff) raises an error in numpy 1.13:
https://docs.scipy.org/doc/numpy/release.html#deprecationwarning-to-error
=> FIX: Compatibility with numpy 1.13

bluesky/examples.py
This way `trigger_read` can be overridden to deal with more complex readers
eg readers with shutters
This allows for a more flexible setup, where the data can be modified from the `Reader` after the read but before the data is stashed into FS
I ran the existing tests.
=> ENH: ReaderWithFilestore uses its own read

bluesky/tests/test_run_engine.py
We need to ensure that time < 50 seconds. We have been checking that time < .2
seconds. We might well as well check that time < 5 seconds because Travis can
be slow to process RunEngine interruptions sometimes.
=> TST: Adjust tolerance to reduce random test failures.

bluesky/run_engine.py, doc/source/api_changes.rst
*The original usage, RE.subscribe(name, func), is supported with a warning.*
All tests pass, unchanged.
This is a case of the adage, "You design the most important part of your
software at the beginning, when you understand it the least." The switch on
'name' is rarely used.
=> API: Support RE.subscribe(func).

bluesky/callbacks/broker.py
Check if event doc is filled before trying to fill it in `LiveImage` callback
Data analysis pipelines will hand down filled documents, this change allows data to be poured into this callback
=> ENH: check if events are filled before asking filestore for the data

bluesky/qt_kicker.py
The usage:
```python
from bluesky.qt_kicker import install_qt_kicker
```
has been issuing a warning since April 2016. The new usage is:
```python
from bluesky.utils import install_qt_kicker
```
I propose removing the old shim module now.
=> API: Remove shim module deprecated in April 2016.

bluesky/callbacks/broker.py, bluesky/examples.py, bluesky/tests/test_examples.py
Changes to Bluesky due to changes in Databroker
We are re-working how the internal of `Registry` (nee `FileStore`) objects work.  The bluesky examples will need to keep up.
The working branch on databroker has been changed to install from this branch which will take care of testing the interaction.
=> TST: change example code to match new Asset naming

bluesky/callbacks/zmq.py, bluesky/run_engine.py, bluesky/tests/test_callbacks.py, bluesky/utils.py
Remove `sanitize_np` everywhere it is used in run_engine.py.
We are currently 'sanitizing' numpy arrays returned by devices into lists (or lists of lists, etc.) so that they can go safely into pymongo (which doesn't know what to do this numpy arrays). This should done on the databroker/metadatastore side, not in bluesky, because some callbacks need numpy arrays and it's wasteful to convert to lists and then back to arrays.
**This should not be merged until there is a corresponding PR in databroker providing this functionality there.**
Closes #636 
This will definitely fail tests until databroker is updated.
=> API: Do not 'sanitize' numpy arrays into lists.

bluesky/callbacks/broker.py, bluesky/run_engine.py, bluesky/tests/conftest.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_vertical_integration.py
This is the final step in making a RunEngine and a Broker
(configured with a suitable prepare_hook) return identical
documents. It should remove some annoying edge cases for
consumers that want to receive from both.
This also includes some commits to update bluesky to the new
databroker API.
=> ENH: Include 'filled' key in events.

bluesky/tests/test_callbacks.py
This test, added yesterday during the period where 3/4 Travis builds were
failing due to conda building issues, consistently fails on 3.5 and passes
on 3.6. It covers a new feature so it is not a show-shopper. I propose
known-failing this test so it does not jam up the rest of the PRs in the
pipeline and revisiting after the rc is out.
=> TST: xfail test_broker_base for now

bluesky/examples.py, bluesky/plans.py, bluesky/run_engine.py, bluesky/tests/test_bec.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_simple_api.py
There are no plans to pass it anything to control what is returned
and by making it an attribute it makes configuration easier.
=> API: make hints an attribute / property instead of method

bluesky/magics.py, bluesky/tests/test_magics.py, doc/source/magics.rst
Meetings with beamline staff raised concerns that IPython magics for
data-taking plans like '%ascan' were more confusing than helpful.
On the other hand, magics like '%wa' and '%mov' seem harmless.
'%wa' just reads hardware and prints to the screen. '%mov' touches
hardware, but it does not generate any documents.
We realized that the important distinction is that these magics
do not save data. The ones that save data ('%ascan', '%mesh', etc.)
are more troubling because they do not combine well and could easily
lead users astray. This PR removes them.
We have kept '%ct' but changed what it does: instead of executing
`RE(count(dets))` with the user's RunEngine, it uses a private
RunEngine that is not subscribed to the databroker; thus it does not
save data. It just prints results to the …
=> API/DOC: Rethink magics.

bluesky/callbacks/core.py
Closes #759
LivePlot now supports plotting against `event['time']`. By
default, it sets t=0 to the beginning of the run rather than
the UNIX epoch. This PR provides an optional to turn off
that nicety.
This approach --- adding a separate flag --- avoids squatting any names that
might show up in an event's data keys, and it also opens the possibility of
accepting other epochs or a floating point number.
=> ENH: Add 'epoch' option to LivePlot.

.travis.yml, requirements.txt
Our dependency on traitlets went about with global state. We do not used it anywhere
(confirmed with `git grep traitlets`).
This removes it from requirements.txt and .travis.yml.
=> BLD: Remove traitlets from requirements; it is not used at all.

bluesky/tests/test_callbacks.py
Now the test ensures that event and descriptor documents go
through 0MQ successfully. As far as we can tell nothing is
broken, but this is a better test for future-proofing the code.
=> TST: More realistic zmq test.

bluesky/tests/test_progress_bar.py, bluesky/utils.py
- Handle case where current, initial, total are tuples.
- Handle case when 'name' is not provided by status obj.
- Handle case where 'unit' is not provided by status obj.
- Use status.done rather than fraction to check completeness.
- Note that 'time_elapsed' and 'fraction' are not yet used by this
implementation of a progress bar.
=> FIX: Make progress bar work when position is a tuple.

bluesky/callbacks/best_effort.py, bluesky/callbacks/core.py
The fixed aspect + shared axis where producing sub-optimal plots for multiple detectors plotted with BEC.
BEC now also guesses if the image should have equal aspect ratio (for example scanning two motors in the same units) or automatic aspect (which makes sense for motor vs E or something like that).
```python
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
plt.ion()
from bluesky.examples import motor, motor1, det, det1
import bluesky.plans as bp
from bluesky.utils import install_qt_kicker
install_qt_kicker()
RE = RunEngine()
```
```python
RE(bp.outer_product_scan([det1, det], motor, -1, 1, 5, motor1, 10, 20, 3, False))
``` …
=> Mnt bec 2 d plotting

bluesky/utils.py
Allow users to select the update_rate of either the `nb_kicker` or `qt_kicker` at call time. 
Doesn't seem like it could hurt anything. Main motivation is we are experimenting with putting the RunEngine behind a PyQT UI and 0.03s between updates is too unresponsive
Have you experimented with controlling the RunEngine through Qt? We might end up just launching multiple threads to have completely separate event loops, so this may end up being moot. However, the option seems like it would be nice to have.
=> ENH: Add update_rate as kwarg in kicker utils

bluesky/callbacks/best_effort.py, bluesky/tests/test_bec.py, doc/source/callbacks.rst
A commonly-used callback prints the scan IDs and timestamps
above the LiveTable. This pulls that upstream into BEC
and adds switches for toggling it on and off.
=> ENH: Include heading with IDs, times in BEC.

bluesky/callbacks/core.py
Solution for issue #684. Reference the length of the stored `ydata` instead of the sequence numbering before updating the `lmfit` model
* Instead of referencing the sequence number we see check the `ydata` array directly
* I replaced the `RuntimeError` with a print statement. It seems to me the operating model is that even when they are misconfigured the callbacks should not raise exceptions. For example, if you enter the wrong key name in `LivePlot` it doesn't break your scan, it just doesn't display well. 
There are a number of situations where checking the sequence number is less advantageous. For instance, if you have multiple groups being read out and your y data is not present in every emitted event document. If the first sequence number you see the y data key is document five the …
=> MAINT: LiveFitPlot should reference ydata before updating

bluesky/plans.py
Closes #732
See there for discussion on why we would do such a thing.
=> Add mov as synonym for mv; likewise for movr, mvr.

.travis.yml
We currently run some test builds by using pip and others by using conda.
We originally used conda because it was much faster than pip. Now that
we have pip wheels, pip is as fast or faster. It is also empircally more
reliable and results in a simpler .travis.yml file.
The main reason for continuing to test with conda packages is to make
sure our public conda channels are up to date. This can be done using
a single integration test. There is no need to do it separately for
every package (bluesky, databroker, ophyd).
=> CI: Simplify build process by using pip only.

bluesky/plans.py, bluesky/tests/test_generators.py
A simple plan preprocessor called `stub_wrapper` that strips `open_run`, `closed_run`, `stage` and `unstage`. 
I think of this as the inverse method for `run_wrapper`. There is a lot of logic built into the complete plans, but these are slightly awkward to stitch together. This allows you to remove all of the run control and staging functionality and just use the scanning logic.
This opens up a simple way to stitch plans together without having to rewrite things from scratch. For instance, this implementation seems pretty intuitive
```python
list_scan([det], motor, [1,2,3,4,5], per_step=stub_wrapper(count([det], num=5, delay=3)))
```
We have been using this at SLAC in a few places so I figured I would throw it back and see if you found it useful. The nice thing is as a developer you can …
=> ENH: Plan preprocessor to remove run_control

bluesky/run_engine.py
Make ``RE`` pause message configurable
Adding an attribute ``pause_msg`` to ``RE`` (default to ``bluesky.run_engine.PAUSE_MSG``), so that the message printed when a run is interrupted can be modified if needed.
As the discussion [in an issue from separate repo](https://github.com/xpdAcq/mission-control/issues/52), it might be good if the pause message is configurable. Here is summary of this PR:
1. The name of ``RunEngine`` instance might not always be ``RE``. If the name of this ``RE`` instance is ``foo`` then the user would need to do ``foo.abort()`` to about the run from ``foo``. However, current pause message instructs the user to do ``RE.abort()`` regardless the name of ``RE`` instance.
2. It's likely that people might want to customize the pause message even more heavily (or omit it …
=> ENH: make RE pause message an attribute.

bluesky/magics.py, bluesky/run_engine.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_devices.py, bluesky/tests/test_documents.py, bluesky/tests/test_examples.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_scans.py, bluesky/tests/test_suspenders.py, bluesky/tests/test_vertical_integration.py
~There are couple more tests to fix before this is done, but let's kick off discussion in the meantime....~ Update: tests pass.
When the RunEngine is paused by Ctrl+C or by a plan (using `Msg('pause')`) it does not raise an exception by default. This is usually "nice" for interactive use (no ugly tracebacks!) but it is bad behavior as a library. This kind of thing is dangerous:
```python
def f():
RE(plan1)  # if this catches Ctrl+C and goes into a paused state
RE(plan2)  # this will immediate start running! bad!
```
Even here at NSLS-II where @tacaswell and I prowl the ring with clubs and bludgeon scientists about avoiding this, it happens all the time. It is just too obvious of thing to do, and users naturally discover it. We should continue to tell them not to. (Don't worry, @tacaswell, …
=> API: Always raise when interrupted. Reserve no kwargs in RE.__call__.

bluesky/plans.py, bluesky/run_engine.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, bluesky/utils.py
`run_wrapper` and friends ensure that the plan always yields a run_stop which means the fall through in the RunEngine which sets the exit_status before hitting the run_close of lost resort.
fixs #847 
added a test
=> Fix mark success on abort

bluesky/run_engine.py, bluesky/tests/test_devices.py
We have always said that an event stream is homogeneous in terms of data keys.  We had been enforcing that this was true per descriptor, but not per stream name. 
This was noted during review of #853
Had to update a few tests that were verifying the behavior on a per-descriptor level.
Fixed some tests that are broken by ophyd changes to Device.
=> Fix validate uniform eventstream

bluesky/plans.py, bluesky/tests/test_plans.py
They were being implicitly set in scan_nd in the opposite order.
closes #874
=> FIX: dimension hints on outer_product_scan

bluesky/plans.py, bluesky/tests/test_scans.py, doc/source/plans.rst
tune a motor to the centroid of signal(motor) with progressively smaller range and step size
Move the motor to the final centroid at the end
adds `tune_centroid()` plan to bluesky.plans
This algorithm has been used at APS (in SPEC macros) for some years.
Unit test contributed.  Also tested in ipython session using:
motor = Mover('motor', {'motor': lambda x: x}, {'x': 0})
det = SynGauss('det', motor, 'motor', center=-1.3, Imax=1e5, sigma=0.05)
RE(tune_centroid([det], "det", motor, -1.5, -0.5, 0.01, 10))
Also tested (not shown here) using EpicsMotor and EpicsSignalRO with an `swait` record configured as a pseudo-detector.
```
In [1]: bluesky.__version__
Out[1]: '0.10.2.post17+g770df4e'
In [6]:     motor = bluesky.examples.Mover('motor', {'motor': lambda x: x}, {'x': 0})
...:     det = …
```
=> #875 introduce tune_centroid() plan

.coveragerc, bluesky/plans.py, bluesky/tests/conftest.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_plans.py, bluesky/tests/test_utils.py, bluesky/utils.py, test-requirements.txt
- merge_cycler attempts to find PseudoSingle devices (in a duck-type
way) that are from the same device and merge them into a single
cycler entry.
- after we set up the meta-data in scan_nd, merge the cycler!
=> ENH: Merge PseudoPositioner children in plans automatically 

bluesky/tests/conftest.py
With this last fix, the tests will run with 0 warnings.
We were getting a warning from matplotlib that more than 20 figures
were open.
This borrows an idea from matplotlib's test suite, automatically
applying a pytest fixture to _all_ tests that closing any figures
when the test completes.
=> TST: Close any matplotlib figures that were opened during a test.

bluesky/__init__.py, bluesky/cntx.py, bluesky/magics.py, bluesky/object_plans.py, bluesky/plan_stubs.py, bluesky/plans.py, bluesky/preprocessors.py, bluesky/simulators.py, bluesky/tests/test_bec.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_devices.py, bluesky/tests/test_examples.py, bluesky/tests/test_generators.py, bluesky/tests/test_magics.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_progress_bar.py, bluesky/tests/test_ramp_plan.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_simulators.py, bluesky/tests/test_supplemental_data.py
This will be force-pushed to
The nominal goal is to get all of the local imports into plans.py namespaced so tab-complete only gives you fully boxed plans.
@teddyrendahl @ZLLentz I suspect this will cause you a lot of breakage.
cntx.py is likely to be deleted, all of it's contents were already deprecated.
closes #850
=> API: re-organize / split plans.py for developer convenience 

doc/source/api_changes.rst
As with ophyd, we plan to tag v0.11.0 tonight, run some final tests tomorrow morning (and improve the docs if there is time), and then tag v1.0.0 tomorrow to meet a deadline specified by upper management.
=> DOC: v0.11.0 release notes

bluesky/plan_stubs.py, bluesky/preprocessors.py, bluesky/tests/test_plans.py
If parent is in the set of things to be reset, do not reset the
children too.
closes #905
=> FIX: pseudo reset wrapper

bluesky/tests/conftest.py
This will make matplotlib optional for databroker tests again.
=> TST: move matplotlib import to inside of fixture

bluesky/tests/test_new_examples.py
This fixes a random test failure that occurs on 3.5 only
(because dict iteration order inside cycler in randomized).
=> TST: order of 'set' messages does not matter in mvr, mv

bluesky/callbacks/best_effort.py, bluesky/plans.py
Some issues with best effort callback. Used a hint in the `relative_inner_product_scan` to help guide the best effort callback.
Sample code to run (toggle `False` to `True` to test between the outer and inner product scans):
(Note this is a copy and paste from documentation)
```python
from bluesky.plan_stubs import abs_set, wait
from bluesky.plans import (relative_outer_product_scan)
from bluesky.plans import relative_inner_product_scan
from bluesky.preprocessors import (run_decorator, stage_decorator,
subs_decorator)
from bluesky.callbacks import LiveTable, LivePlot
from ophyd.sim import det4, motor1, motor2
from bluesky.utils import ts_msg_hook
def grid_in_grid(samples): …
```
=> Added hint to inner_prod scan

bluesky/suspenders.py, bluesky/tests/test_suspenders.py, doc/source/state-machine.rst
The "band" suspenders were counter-intuitive and confusing. This PR should resolve the confusion by deprecating `SuspendOutBand` and renaming `SuspendInBand` -> `SuspendWhenOutsideBand`.
Better user experience.
The corresponding test was updated.
=> ENH: clarify band suspenders

bluesky/plans.py
Fixes #919: 
* change `step_factor` (keep the name) to be *the factor to reduce the range of each successive iteration*
* enforce bounds on motion
* determine the centroid from each pass separately
#919
`coverage run run_tests.py`
=> ENH #919, passes unit tests

bluesky/plan_stubs.py, bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, doc/source/msg.rst, doc/source/plans.rst
Add and register a `drop` message to cancel bundled readings, allowing us to call `create` and try again.
There are use cases for plans with live feedback where you want to take some number of “good” events. When the quality of a `read` command is known at runtime and is clear, calling for a `drop` is a convenient way to curate the stream of event documents so that only certain events make it to the subscribed callbacks. This allows us to avoid duplicating event filtering code in every single callback.
The `drop` message was added to any parametrized test that also had the `save` message. A new test was added that drops events and counts emitted event documents.
- I’ve taken the same approach as in `save` to only allow a `drop` after a `create` message. This isn’t strictly needed because …
=> ENH: Add ‘drop’ Message

bluesky/utils.py
Usually users need to call either ```install_qt_kicker``` or ```install_nb_kicker``` in order to get the live plots and other callbacks to work properly. The idea of this PR is to add a functionality that I added to LIX while working there to make it easier for the user by just installing the correct one based on how they are running the code.
Added a method at utils.py named ```install_kicker``` which based on the environment will install either qt_kicker or nb_kicker.
It simplifies the setup of the kicker.
Locally tested.
=> ENH: Simple install_kicker()

bluesky/suspenders.py
The `warning` for the suspender should be in the `__init__` not the class declaration, is that correct?
Right now I get warnings whenever I import anything from `bluesky.suspenders`
=> Moved suspenders into init, not class declaration

bluesky/callbacks/core.py, bluesky/tests/test_callbacks.py
Closes #914, related to #912 originally reported by @chiahaoliu.
The first commit adds a test demonstrating the problem: if a datum_id works its
way into LiveTable, LiveTable can fail in this confusing way:
```py
cols = [f.format(**{k: data[k]})
if k in data else ' ' * self._format_info[k].width
>           for k, f in self._data_formats.items()]
E   ValueError: Unknown format code 'f' for object of type 'str'
```
It's expecting a number -- the externally-stored data -- but it gets a string UUID.
The second commit fixes the problem by skipping any data that both externally
stored and unfilled. One can always fill the data first and _then_ send it
to LiveTable, in which case LiveTable will be satisfied.
=> FIX: Skip unfilled externally-stored data in LiveTable.

bluesky/plan_stubs.py, bluesky/plans.py, bluesky/tests/test_new_examples.py, doc/source/plans.rst
Quick implementation of the `repeat` plan previously described in #929, with a refactoring of `count` to use `repeat`.
There are cases where we want to have a repeatable plan where we can leverage the kind of looping and delaying from `count` without rewriting the control flow. The logic in that plan isn't just a trivial `for loop`.
`count` still works after being reimplemented using `repeat`
- I'm not in love with this implementation because I feel like it's cleaner to make a new plan with a simple `for loop`
- This is better for the health of the library than implementing a `per_step` kwarg in `count`, and it accomplishes almost the same thing
- It is up to the user to define a descriptive metadata dict and provide `start` and `stop` documents because the `repeat` plan doesn't do …
=> ENH: Implement repeat plan

bluesky/callbacks/stream.py, bluesky/tests/test_streams.py, dev-requirements.txt, doc/source/callbacks.rst
The goal of this addition is to provide an outline for doing streaming analysis and feed this information to other out of the box `bluesky` callbacks. The callback uses the `streamz` module to send the event documents through an arbitrary graph network. Each document is then repackaged and sent to subscribers. 
This solves a number of problems we have at SLAC where we want to process data as it is emitted and not necessarily wait for those things to propagate through a databroker. In order to not confuse event streams, the `LiveStream` mimics the document creation in the `RunEngine`, it creates its own sequence numbering, descriptors e.t.c. Here is an example below of running `bluesky.examples.stepscan`, and having two plots; one averaging every two shots, one showing the raw data. …
=> ENH: LiveStream

bluesky/callbacks/best_effort.py, bluesky/tests/test_bec.py
Closes #955
Notice TDD commit history, verifying that the test hits this bug and the
next commit fixes it.
=> Make BEC more tolerant of under-hinted plans.

bluesky/plan_stubs.py, bluesky/tests/test_new_examples.py, doc/source/api_changes.rst, doc/source/plans.rst
The notion of repeating a literal sequence of Msgs is problematic,
because some Msgs' contents depends on replies from the RunEngine.
For example, `Msg('unsubscribe', ...)` contains a ``token`` that
comes from the RunEngine's reply to `Msg('subscribe')`. Therefore,
it does not really make sense to support the usage, "Repeat this
literal sequence of Msgs." Repeater utilities should require
callables, so that adaptiveness can be fully supported.
attn @ZLLentz
=> API: Deprecate caching_repeater; limit 'repeat' plan to callables.

bluesky/plans.py, bluesky/tests/test_new_examples.py
This fixes a regression in the backward compatibility of `scan`. If
a user passes in a ``per_step`` parameter with has a 1D signature
(a signature like ``one_1d_step``) this PR uses a local "adapter"
function to translate this into ``one_nd_step``.
It also adds validation and user-friendly error messages in the event
that the ``per_step`` parameter provided by the user does not have one
of the expected signatures.
There is still a potential for breaking user code: we now insist that
the parameter *names* in ``per_step`` functions match the ones we expect
-- either ``one_1d_step`` and ``one_nd_step``. Before, users could technically
get away with a ``per_step`` function that had different parameter names
because we called the ``per_step`` function with positional arguments.
However, I …
=> FIX/TST: Accept one_1d_step or one_nd_step-like signatures in per_step.

doc/source/metadata.rst
- Use `RE.md = ...` in all examples (instead of creating a fresh RE instance).
- Document that RunEngine(md) is possible but put it in a warning box with a
a warning about "data loss" and a link to the section of the tutorial that
explains this issue.
- Copy-editing
- Improved formatting
Thanks to @jrmlhermitte for flagging the potential for costly confusion here.
=> DOC: Use 'RE.md =' instead of 'RE = RunEngine(...)'

bluesky/run_engine.py
Implements bluesky's piece of https://github.com/NSLS-II/databroker/pull/322. This is fully backward-compatible with old releases of ophyd. If it is new with a device that implements the new `collect_asset_docs` method, then event model v1.5.0 is required and, if a Broker is subscribed, databroker v0.11.0 is required.
=> ENH: Emit Resource and Datum documents.

bluesky/plan_stubs.py, bluesky/preprocessors.py, bluesky/run_engine.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_suspenders.py, doc/source/plans.rst
Adds messages and preprocessor to install and remove suspenders during a plan.
```
Msg('install_suspender', None, my_suspender)
Msg('remove_suspender', None, my_suspender)
suspend_wrapper(my_plan, my_suspender)
```
We've found times where we would like to associate a suspender with a particular plan, rather than with the `RE` instance. These are the sort of things that we might want for only a subset of plans in a particular experiment, so switching between them is awkward. This seems like a logical extension of the existing API.
This seemed simple enough to implement in a very basic way, so I decided to hash it out.
closes #998 
I've inserted the messages into the tests where it seemed appropriate and added a test for the preprocessor at the end of the suspender tests.
=> ENH: Add suspender messages

.gitignore, bluesky/run_engine.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_suspenders.py
The suspenders where calling the obj.pause() upon being triggered, but were not calling the obj.resume() when they resumed.
Added a coroutine `_resume()` and then registered (And called) a `Msg` called `resume` to run it.
The FastCCD detector on CSX turns off the HDF5 file capture when paused, and as resume is not being called on the suspender resume, the detector never starts writing data to a file again.  
For the Ctrl-C type pause/resume everything works as expected.
We (myself and @jrmlhermitte) ran numerous tests on the beamline to make sure this fixed the observed issue on CSX.
=> BUG: Suspenders now call .resume() upon resuming

bluesky/callbacks/best_effort.py, bluesky/tests/test_bec.py
This PR should fix the issue with a BestEffortCallback LiveGrid plot failing for the `grid_scan` plan for a motor with one step.
Steps to reproduce:
```python
import matplotlib.pyplot as plt
from bluesky.utils import install_qt_kicker
from bluesky.run_engine import RunEngine
import bluesky.plans as bp
from ophyd.sim import det4, motor1, motor2
plt.ion()
install_qt_kicker()
RE(bp.grid_scan([det4], motor1, 0, 1, 1, motor2, 0, 1, 2, True))
```
This will fail with an error like:
```
In [26]: RE(bp.grid_scan([det4], motor1, 0, 1, 1, motor2, 0, 1, 2, True))
Transient Scan ID: 6     Time: 2018/04/07 00:48:56
Persistent Unique Scan ID: '23353b56-06cd-4827-abb6-79a472c29736' …
```
=> FIX: fix BEC LiveGrid plot for a motor with one step

bluesky/run_engine.py, bluesky/tests/test_run_engine.py, bluesky/utils.py
An alternative to #1007, this allows the user to add or remove context managers for the run loops as they see fit.
Unlike #1007, this pulls us away from the path of having many different `RunEngine` classes in some awful inheritance hierarchy, and gives us clear ways to run without the sigint handler or with extra locks as we need them.
This still passes the `bluesky` tests. Additional tests were added to make sure having no context manager and many context managers worked as expected.
This can probably be cleaned up more, but it seems to do the job.
=> ENH: Allow configuring RunEngine context managers

bluesky/preprocessors.py
Add a warning when the relative wrappers are used in 'simulation' mode and are assuming an initial position of `0` along with some clean up
Fixes quality of life issue / possibly dangerous situation they had at CSX.
```
In [3]: import bluesky.plans as bp
...: from bluesky.simulators import print_summary
...: from ophyd.sim import motor1
...: from ophyd import Signal
...: 
...: motor1.set(5)
...: s = Signal(value=0, name='s')
...: print_summary(bp.rel_scan([], motor1, -1, 1, 10))
...: print_summary(bp.rel_scan([], s, -1, 1, 10))
=================================== Open Run ===================================
motor1 -> 4.0
Read ['motor1']
motor1 -> 4.222222222222222
Read ['motor1']
motor1 -> 4.444444444444445
Read ['motor1']
motor1 -> 4.666666666666667
Read ['motor1']
motor1 -> …
```
=> Rel warning

bluesky/plans.py, bluesky/tests/test_scans.py
This is a generic version of a theta-2theta scan.
Watching @ambarb do scans while testing the tardis at CSX she typed this signature into `relative_inner_product_scan` as a bit of wishful API.
@ambarb Did I understand this correctly and is this useful?  Do you have a better name?
Still needs test
=> ENH: add a x2x_scan

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
Move the logic to re-set the internal state of the RE to not bundling
to above where we do anything with descriptors.
=> FIX: clean up the internal state of the RE earlier in _save

bluesky/run_engine.py
Tested by running the databroker test suite, which has a lot of tests involving ophyd's simulated area detector, against this branch.
=> FIX: Do not collect asset docs on read if we are not bundling.

bluesky/plan_patterns.py, bluesky/plans.py
Combines ~~#653,~~ #655, #656. Completes the 'spiral' plans by allowing the user to control all the degrees of freedom.
@awalter-bnl Thanks for this contribution to bluesky. I know we've said it before, but it bears repeating: it's great to see beamline scientists contributing upstream!
I merged your two commits (from your `patch-1` and `patch-2` branches) into this one PR and made the following revisions on top:
* Fixed a place where the 'asym' argument was accepted but then not used.
* Renamed 'asym' to 'aspect_ratio' (as discussed [previously](https://github.com/NSLS-II/bluesky/pull/656#issuecomment-284383082)) because Tom and I agree that that is more clear to general users. In the event of ambiguity, the docstring clarifies the exact meaning.
* Addressed minor style and whitespace …
=> Spiral aspect

bluesky/magics.py
WIP : Adding some ipython magics for bluesky for better diagnostics.
This is a WIP adding a series of bluesky magics that will allow the user to find what Devices they have available.
Users often need to see a list of defined ophyd devices. This will help with that.
Tested at PDF beamline so far:
```py3
In [1]: %detectors
Python name              Ophyd Name          
========================================
Test_Cam1                Test_Cam1           
Cam2                     Cam2                
camera                   Cam2                
stats_plugin             Cam2_stats5         
pe1                      pe1                 
```
This is currently just searching the user name space. It might be potentially useful to search all `Signals` (children of `Devices`).
=> Added magics

.travis.yml, bluesky/preprocessors.py, bluesky/run_engine.py, bluesky/tests/test_plans.py, bluesky/tests/test_ramp_plan.py, bluesky/tests/test_simple_api.py
Hey, look a RunEngine bug!
In current master, it possible for a monitored signal
to emit an Event document from its subscription thread before
the corresponding EventDescriptor document is emitted by the
RunEngine's thread, thus confusing consumers who see a descriptor ID
referring to an EventDescriptor that they have not yet received.
=> FIX: Monitor must emit descriptor before event.

bluesky/run_engine.py
This typo is only hit if using a Flyer than implements `collect_asset_docs()`.
Are there any on the ring other than the one that @mrakitin are setting up with @dhidas
for HXN?
=> FIX: Show-stopping typo in flyer asset collection.

bluesky/callbacks/best_effort.py
If over-constrained tight_layout may raise `ValueError`.  Catch that
and move on assuming that an ugly plot is better than blowing up.
https://gitter.im/NSLS-II/DAMA?at=5b12a1ba4eaffb692d76db00
=> FIX: catch tight_layout errors

MANIFEST.in
Most importantly, include requirements.txt, which is opened by
setup.py.
In current distribution, installing from a downloaded source tarball
does not work!
h/t @mrakitin for noticing the missing requirements.txt file.
=> BLD: Include more files in distribution.

bluesky/plan_stubs.py, doc/source/plans.rst
Take the `move` plan embedded into `one_nd_step` and bring it out to the module level, renaming to `move_per_step` (name negotiable)
The first step to writing a custom `per_step` hook if you don't want the default `trigger_and_read` is copying and pasting this `move` block so that the motors move as expected, and then adding your custom logic afterwards. It'd be much better to be able to import this and reuse elsewhere.
I'm assuming the tests still pass
=> MNT: Refactor the motion part of one_nd_step into importable plan

doc/source/tutorial.rst
As noted in #1086, the tutorial instructs users to pip- or conda-install
a set of packages but omits matplotlib. Since matplotlib is only an
optional dependency of bluesky, it has to be explicitly installed.
=> DOC: Include matplotlib in list of packages to install in tutorial.

bluesky/callbacks/zmq.py, bluesky/tests/test_zmq.py, dev-requirements.txt
For #1065 atn @CJ-Wright 
Note the prefix is not serialized using the serializer. This piece is interpreted internally by the zmq `Publisher` and `RemoteDispatcher`.
=> Add Serializer to zmq callback

bluesky/callbacks/mpl_plotting.py, bluesky/magics.py
Add the kwarg 'axes_positive' which is a list in the form ['x_direction', y_direction']. x_direction can take the values 'right' or 'left' and y_direction can take the values 'up' or 'down'. These values define the positive direction of the corresponding x or y axis.
At SRX they scan the sample in order to produce 'images'. This scanning process leads to the y axis being inverted, as the moving the sample 'up' moves the beam 'down' on the sample. This will allow them to flip the direction of y_axis in order to have LiveGrid display the image correctly.
=> Live grid image mirroring

bluesky/examples.py, bluesky/run_engine.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_devices.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_streams.py, dev-requirements.txt, doc/source/magics.rst, fuzz/fuzz.py
This should address the issue that has broken the bluesky CI since 29
August.
The "name" (i.e. stream name) item in Event Descriptors was introudced
in bluesky 0.4.x in February 2016. In the latest release of event-model,
1.6.0, we ensure that _if_ "name" is present its value must be a string.
This requirement breaks some old tests in bluesky, which generated Event
Descriptors with ``{'name': None, ...}``. We still allow name to be
absent, so that old data will still validate successfully.
It is not expected that much (or maybe any) production data has this
problem, because getting ``None`` requires manually spelling out
``Msg('create')``. The default name from ``bluesky.plan_stubs.create``
or high-level plans that call it is ``'primary'``.
=> FIX/TST: Update RunEngine._create and tests for event-model 1.6.0.

bluesky/run_engine.py
ENH: Allow RunEngine customize scan_id calculation
Before the RunEngine will increase 1 each time for
scan_id. There isn't each way to change this scan_id
calculation method.
Since scan_id was created as a user-friendly number,
Now there is a callable argument scan_id_source to
allow user pass in a bespoken calculation method for
scan_id.
By pytest with /tests and bluesky tutorial example
The change is very limited and inside run_engine.py. It doesn't affects other code
====================================================== test session starts =======================================================
platform darwin -- Python 3.6.6, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
rootdir: /Users/kz2249/bluesky, inifile:
collected 399 items …
=> Customized scan_Id calculation method allowed 

bluesky/callbacks/best_effort.py, bluesky/plans.py
Fix invalid escape-sequence warnings from Python 3.6.
=> MNT: fix invalid escape sequences in strings

bluesky/log.py, scripts/bluesky-0MQ-proxy
Add --verbose and --logfile feature to bluesky-proxy
User friendly 
In terminal, run ipython
$ ipython --matplotlib=qt5
In ipython, run scirpts which will start proxy and RemoteDispatcher, in_port and out_port needed
%run -i bluesky-0MQ-proxy 5577 5578
If we add --verbose and --logfile=temp.log
%run -i bluesky-0MQ-proxy 5577 5578 --verbose --logfile=temp.log
=> Bluesky proxy verbose

bluesky/tests/test_bec.py
The `set` method on Signal uses a background thread to actually set
the value.  This was leading to race conditions on travis where
sometimes the value would not actually be set before we check it.
Use set_and_wait instead.
=> FIX: eliminate race condition in bec test

doc/source/api_changes.rst, doc/source/debugging.rst
Includes an update to the logging documentation, reflecting the recent
changes to logging. Note that ``msg_hook`` and ``state_hook`` are
separately documented in the "Run Engine API" page, so that
documentation has been removed from the logging page now that we can get
the same information more easily and more readably from loggers.
=> DOC: Release notes v1.5.0

bluesky/callbacks/mpl_plotting.py
This fails with AttributeError on Matplotlib master and will fail on
3.1 (coming next month).
=> MNT: stop using deprecated API in matplotlib

bluesky/callbacks/best_effort.py
ISO8601 date delimiter is "-", not "/"
space between date and time is now accepted as modification of ISO8601 standard so no change there
Existing: `Transient Scan ID: 17     Time: 2019/02/22 14:22:52`
Revised: `Transient Scan ID: 17     Time: 2019-02-22 14:22:52`
Cosmetics:  why not use ISO standard format here?
=> ENH: use the ISO8601 delimiters for date

.codecov.yml
This configuration file, which we have recent adopted on several other
projects retains the codecov X/checkmark in the "merge" box but
suppresses the large comment.
=> CI: Add codecov config.

bluesky/plans.py
Seems the `fly_during()` plan was dropped sometime in late March-early April of 2016.  It had moved from `plans.py` to `plan_tools.py` and later moved again in a code cleanup.  I just spent time looking for it.  Time to identify its new location.
=> DOC: remove reference to relocated code

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
This would have lead to a much clearer traceback at a beamline.
Ran into this working with @EliotGann If `read` returned `None` you got an exception in `save` when we try to collate the results.  This moves the failure to much when it happens and provides better exception (I ended up doing a binary search on a long list of baseline devices to find the problem).
If other also think this is a good idea I'll throw a test onto it.
=> MNT: add more helpful error message if obj.read returns None

bluesky/tests/test_run_engine.py
A unit test verifying RunEngine.state is not assignable.
def test_state_is_readonly(RE):
with pytest.raises(AttributeError):
RE.state = 'running'
This is in support of #1188.
=> add test_state_is_readonly

.travis.yml, bluesky/callbacks/stream.py, bluesky/run_engine.py, bluesky/tests/test_documents.py, requirements.txt
This PR depends on https://github.com/bluesky/event-model/pull/79.
Replace calls to deprecated jsonschema.validate() with sanctioned jsonschema.Validator.validate().
Use a dict of jsonschema.Validator imported from event-model.
Remove jsonschema<3 pin from requirements.txt.
This change is simply to get away from the deprecated jsonschema.validate().
Existing tests pass.
=> New jsonschema types api #1197

setup.py
This field in `setup(...)`, now part of our standard cookiecutter for
new projects, was never added to bluesky.
=> BLD: Add python_requires.

bluesky/plan_patterns.py, bluesky/plans.py
It appears that elliptical spiral scan capability was added to both ``spiral_pattern`` and ``spiral_fermat_pattern`` but only then propagated up to the ``spiral`` plan. This PR adds the required ``kwarg`` to ``spiral_fermat`` to complete this fix.
Added the ``kwarg`` `dr_y=None`` to  ``rel_spiral``, ``spiral_fermat`` and ``rel_spiral_fermat`` which is passed down to to the associated plan or plan_pattern (where it was already included). It also makes a few 'pep-8' style changes.
This adds elliptical fermat spiral capability to the ``spiral_fermat`` plan
fixes #648 
This has been tested manually and passed (locally) the CI testing.
=> small update to spiral_fermat and rel_spiral_fermat to add ellipticty

bluesky/plans.py, bluesky/tests/test_scans.py
Add some validation for argument `num` in `bluesky.plans.scan()` and a unit test.
@danielballan proposed this addition to scan() in response to issue #1198:
```python
if not (float(num).is_integer() and num > 0):
raise ValueError(f"The parameter `num` is expected to be a number of steps (not step size!) "
f"It must therefore be a whole number. The given value was {num}.")
```
After making this change and running a test with `num=1.0` this warning was issued:
```
======================================= warnings summary =======================================
bluesky/tests/test_scans.py::test_scan_num
/home/jlynch/host/project/bluesky/bluesky/plan_patterns.py:293: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
steps = np.linspace(start, stop, …
```
=> validate num argument in scan() (fixes issue #1198)

README.md
Update link to Travis-CI build badge. This fixes issue #1210.
Changed https://travis-ci.org/NSLS-II to https://travis-ci.org/bluesky.
Are there other links on this page in need of update?
=> change https://travis-ci.org/NSLS-II to https://travis-ci.org/bluesky

bluesky/plan_patterns.py, bluesky/plans.py, bluesky/tests/test_scans.py, doc/source/plans.rst, doc/source/tutorial.rst
modifying list_scan to accept multiple motor/list pairs
Current API:
```
list_scan(dets,` motor, [...])  # supports one motor only
scan(dets, motor, start, stop, motor2, start2, stop2, num_steps)  # "inner product" over motors
```
Proposed API:
```
list_scan(dets, motor, [...], motor2, [...])  # If list lengths are unequal, blow up.
list_grid_scan(dets, motor, [...], motor2, [...], motor3, [...], snaking=True|False|tuple)
```
fixes #1144 
has not yet been tested
=> modifying list_scan to accept multiple motors

.travis.yml, bluesky/callbacks/best_effort.py, bluesky/callbacks/mpl_plotting.py, bluesky/run_engine.py, bluesky/tests/conftest.py, bluesky/tests/test_examples.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_scans.py, bluesky/tests/test_streams.py, bluesky/tests/utils.py, bluesky/utils.py, dev-requirements.txt, doc/source/api_changes.rst, setup.py
Do not merge. Needs work.
Closes #1062
Closes #1087
TODO:
=> FIX: improve how we interact with the asyncio event loop

bluesky/plans.py
The ``LiveGrid`` callback (and presumably other consumers yet to be
written) makes use of the ``'extents'`` metadata from ``grid_scan``. The
new plan ``list_grid_scan`` should include ``'extents'`` as well.
Follow up on #1190.
=> FIX: Include 'extents' in list_grid_scan md.

bluesky/tests/test_run_engine.py
It was noted that we would sometimes see rouge SIGINTs escaping from
the test suite which would pre-maturely exit the tests.  On further
investigation we found
1. there was a race condition in the tests that gave a window for the
killer threads to fire when our context manager was not in place
and hence the SIGINT would raise a KeybroardIntreupt someplace
else in the test (sometimes in the pytest / coverage machinery)
2. the file descriptor wake-up machinery does not work on OSX on
travis (see #1215 for attempts to debug this).  It works exactly
as expected on linux on travis and locally and locally on OSX.
This PR cleans the test up and skips it on OSX on travis.
=> Clean up sigint test and skip on OSX on travis

doc/source/plans.rst
Answer two common questions.
Rendered here for easier reading:
=> DOC: Answer two common questions.

bluesky/tests/test_new_examples.py
One test has started failing consistently on the OSX builds, and the
cause is a pytest major release that dropped on June 28. Travis' Ubuntu
virtual machines come with an older version of pytest included, and we do not
force it to upgrade, so we have only encountered this on the OSX builds
so far.
The usage
```python
with pytest.raises(Exception) as exc
```
puts an [``ExceptionInfo``](https://docs.pytest.org/en/latest/reference.html#exceptioninfo)
object into ``exc``, not the exception itself. We were trying ``exc``
like an exception object and relying on the fact that
``ExceptionInfo.__str__`` returned the same thing as ``exc.__str__``
would. The
[pytest 5.0.0 release](https://docs.pytest.org/en/latest/changelog.html#pytest-5-0-0-2019-06-28)
broke that assumption. See …
=> TST: Fix our usage of pytest ExceptionInfo.

bluesky/callbacks/best_effort.py
**Fix to BestEffortCallback function.** 
As a result of recent changes, Bluesky stopped printing the table during acquisition. For example, the following code (part of the basic Bluesky tutorial) would not print the table if run with python or ipython:
```
from databroker import Broker
db = Broker.named('temp')
RE.subscribe(db.insert)
from bluesky.utils import ProgressBarManager
RE.waiting_hook = ProgressBarManager()
from ophyd.sim import det1, det2
from bluesky.plans import count, scan
dets = [det1, det2]
RE(count(dets, num=5, delay=1))
```
After the proposed change, the table printing code is executed even if there is no useful data …
=> Fix: BestEffortCallback - table is always printed

bluesky/callbacks/best_effort.py, bluesky/callbacks/mpl_plotting.py
** Fix for segmentation fault while plotting with BestEffortCallback in IPython **
If run in IPython, the following code would cause segmentation fault during execution of BestEffortCallback. It was found that the Qt backend is not identified by QtAwareCallback.__init__(). As a result, Teleporter object is not created and Qt is called directly from background thread. Converting Qt backend name ('Qt5Add') to lowercase ```use_teleporter = 'qt' in matplotlib.get_backend().lower()``` fixed the problem. 
```
from databroker import Broker
db = Broker.named('temp')
RE.subscribe(db.insert)
from bluesky.utils import ProgressBarManager …
```
=> Fix: segmentation fault while plotting from BestEffortCallback

doc/source/metadata.rst
Minor correction to the example from #1228.
=> DOC: remove duplicate import in PersistentDict example

bluesky/tests/conftest.py
=> use tmpdir for ophyd sim path so pytest cleans up properly

bluesky/callbacks/best_effort.py, bluesky/callbacks/core.py, bluesky/callbacks/mpl_plotting.py, bluesky/tests/test_callbacks.py
This adds two decorators (one function level, one class level) to use to make callbacks "safe" and wrap all of our built-in callbacks with them.
We have had too many cases of bugs in callbacks crashing runs.  This should prevent that at the cost of debugging _why_ plots or tables are not working.
=> Paranoid decorator

bluesky/tests/test_callbacks.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py
This will reduce the number of warnings from the test suite.
The deleted test is explicitly testing the old "internal mode" which
if we continue to test it, should be tested in ophyd or databroker,
but not in bluesky.
We want to push the test suite to be fail-on-warning.
It is changes to the tests
=> TST: don't set the register on test devices

bluesky/tests/test_callbacks.py, bluesky/tests/test_new_examples.py
Two small changes to unit tests for compatibility with updated ophyd simulated hardware.
This is really the work of @tacaswell, in case that is not obvious.
This PR corresponds to the larger PR for ophyd #762, which aligns simulated hardware classes with "real" ophyd objects. This resolves an issue in suitcase-utils, which currently depends on an ophyd branch.
The bluesky tests pass with ophyd PR #762.
=> Unit test updates for ophyd simulated Devices

bluesky/callbacks/best_effort.py, bluesky/callbacks/fitting.py
fixes #1263 
The nlls attribute in `PeakStats` is for a planned, undocumented, and unimplemented feature.  Since it has not been implemented, its presence invites questions from new users as to why `nlls` is defined in the results but always `None`.
=> remove nlls from PeakStats

bluesky/plan_stubs.py, bluesky/tests/test_new_examples.py
The `bps.abs_set` plan accepts `**kwargs` and passes them through to
`obj.set(..., **kwargs)`. This PR makes `bps.mv` do so as well. I
suspect that we might have omitted it this on purpose because, unlike
`abs_set`, `mv` accepts *multiple* devices and there is no way to
express specific `kwargs` for each device without making the signature
complex. However, for common `kwargs` like `timeout` this might be nice
to have.
=> Accept kwargs in bps.mv

doc/source/tutorial.rst
Thanks to @petercj reporting the issue. The `lightsource2-tag` channel
is now deprecated.
=> Update tutorial from lightsource2-tag -> nsls2forge.

bluesky/utils.py
If the motors over-shoot then `n > total` which eventually causes an
assertion failure in tqdm due to `n / total > 1`.
Closes https://github.com/aps-8id-trr/ipython-8idiuser/issues/126
Closes #1278
=> FIX: make sure we never tell tqdm values it considers invalid

.travis.yml
The workers we are getting on travis seem to be significantly throttled and
we are getting persistent failures due to some of the timing tests.
Also add linux py38
=> CI: disable OSX testing on travis

bluesky/plan_stubs.py, bluesky/plans.py, doc/source/plans.rst
Adds the `per_step` kwarg to count
I have added the `per_step` kwarg to the plan `count` mirroring the way it is done for other built-in plans like `scan`. To do this I also had to add the new default `per_step` function `coutn_step` to `plan_stubs`.
At one of the beamlines at NSLS-II they are interested in taking one, or more, 'spectra' at each step in a plan, which can be defined as a scan over a single axis. To do this for  the plan `scan` I created a `per_step` function that collects the `spectra` at each point. To be able to use the same `per_step` function with 'count' plans it required this change.
It has been manually tested, as well as getting the existing pytests to pass locally. I will ensure that the tests also pass on Travis prior to merging.
=> ENH: adding the `per_step` kwarg to the `count` plan

.travis.yml, bluesky/preprocessors.py, bluesky/run_engine.py, bluesky/tests/test_multi_runs.py
This PR includes fix for the existing issue with management of run names in multirun plans. If the plan includes nested runs, the implementation of ``set_run_name_wrapper`` would always overwrite the plan name in the message (``Msg.run``) so that the message returned by the plan would always contain the name assigned to the outermost run. The modified wrapper overwrites the run name only if it has the default value. If the name is modified in the inner run, it passes through the wrapper of the outer run unmodified.
The default value for the run name is a fixed reference to an instance of ``object()``. The reference remains constant for the whole instance of the run engine. If the name is assigned to the run using ``set_run_name_wrapper`` or ``set_run_name_decorator``, it always has …
=> FIX: setting run name for nested runs (`set_run_name_decorator')

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
Adds a new message 'RE_class' which defaults to being on the RE to
query what the class of the RE running the plan is.
This is useful in at least two cases:
- identify if we are being listified
- determine if we are running in a RE-subclass
Added a test.
This can be used to reliably determine if we are in "simulation mode"
or if the RunEngine has been sub-classed etc.
=> ENH: add message to query the type of the RE

bluesky/plans.py, bluesky/tests/test_plans.py
closes #1295
Fixes a regression in how we validate the per_step functions
Added tests of both passing and failing signatures
=> FIX: regression in validating the per_step signature for 1d case

bluesky/callbacks/best_effort.py, bluesky/callbacks/core.py, bluesky/callbacks/mpl_plotting.py, bluesky/run_engine.py, bluesky/tests/test_bec.py, bluesky/tests/test_callbacks.py, bluesky/utils.py
The change in the PR allow to use existing callbacks, including ``BestEffortCallback``, `LivePlot` and `LiveTable` with plans that contain nested runs. Following is the example of such scan, which starts and completes separate run `sim_plan_inner` from `sim_plan`: 
```
@bpp.set_run_key_decorator("run_inner")
@bpp.run_decorator(md={"run_key": "run_1"})
def sim_plan_inner():
@bpp.set_run_key_decorator("run_outer")
@bpp.run_decorator(md={"run_key": "run_1"})
def sim_plan(npts):
yield from sim_plan_inner()
```
Regular subscription to RunEngine can not be used with nested plans, since it provides no mechanism for routing data to different callbacks or different instances of the same callback based on ID of the run producing the data. Instead, the callbacks should be subscribed to the RunEngine …
=> Using existing callbacks with nested multirun plans

bluesky/utils.py
In this PR, the code of `ts_msg_hook` is changed to print the value of the run key along with the rest of data in the Msg object.
Run key is printed in quotes (e.g. `run: 'run_#1'` or `run: '500'`) if it a string, otherwise it is printed without quotes (e.g. `run: 500`, `run: None` or `run: <object object at 0x7f629948aa70>`). Knowing whether run key is a string or not may be useful during debugging of plans.
Information on the message run key is necessary while debugging multirun plans.
Example of the message data printed while running a simulated scan.
```
09:41:12.405496 open_run          -> None            args: (), kwargs: {'run_id': 'run_1'}, run: 'run_1'
09:41:12.409168 set               -> motor           args: (0,), kwargs: {'group': '74a1b030-acc3-4719-9d9d-efef61948936'}, run: …
```
=> Print run key as part of message data in 'ts_msg_hook'

.travis.yml, bluesky/tests/test_callbacks.py, bluesky/tests/test_examples.py, dev-requirements.txt
Fixed CI for v1.5.x branch:
- removed `test_reg_reader` test (uses deprecated feature of Databroker);
- fixed `test_table` test.
=> Fix for CI in 1.5.x branch

.travis.yml, bluesky/callbacks/zmq.py, bluesky/run_engine.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, bluesky/utils.py
This PR is expected to make the branch compatible with Python 3.8. The changes include:
- removal of use of deprecated feature (exactly the same change was applied in v1.6.0);
- replaced all occurrances of `@asyncio.coroutine` by `async def` (optional change, does not influence the build)
=> Support for Python 3.8

bluesky/tests/test_persistent_dict.py, bluesky/utils.py, requirements.txt
Backport the feature of using `PersistentDict` for `RE.md`. The changes include the code copied from Bluesky v1.6.0.
=> Backport of PersistentDict

doc/source/tutorial.rst
Closes #1085 by adding jupyter-specific instructions.
Also adds qt5 to installation instructions, which we discovered during
the last User Meeting were missing.
=> Update tutorial installation instructions

requirements.txt
Follow on to #1317 to make sure the tests don't break due to an old version of event-model
Update the pinned version requirement floor.
We rely on an API change in 1.14 in the tests
CI
=> BLD: require event-model 1.14 or better for RunRouter changes

.travis.yml, bluesky/tests/conftest.py, bluesky/tests/test_plans.py
Formerly we *always* used ophyd `--pre`. Intead, use ophyd stable for
most builds, and use ophyd `master` for one build.
Justification:
* `master` provides an earlier warning than `--pre` about any changes to
ophyd that break bluesky tests
* We should have been testing against the latest stable release of ophyd
to ensure bluesky is not relying on unreleased changes to ophyd.
=> Rework which version of ophyd to use in CI.

doc/source/debugging.rst, requirements-dev.txt
This borrows substantially from caproto, but it's different enough
that it cannot practically share source with it.
=> Rewrite logging docs.

doc/source/api_changes.rst
Caught in post-merge review of
https://github.com/bluesky/bluesky/pull/1323 by @mrakitin
=> Fix out-of-order lines in release notes.

bluesky/utils.py
This PR replaces `tqdm._utils` with `tqdm.utils`.
Made the following replacements:
+ replaced `tqdm._utils._environ_cols_wrapper` with `tqdm.utils._screen_shape_wrapper`
+ replaced `tqdm._utils._term_move_up` with `tqdm.utils._term_move_up`
+ replaced `tqdm._utils._unicode` with `tqdm.utils._unicode`
`tqdm._utils` has been deprecated and will be removed in version 5.
The unit tests are passing in CI.
=> replace deprecated tqdm._utils with tqdm.utils

bluesky/utils.py
This fixes a critical typo in f69709890020241a9d7c500e175908cb87e7b07f
that was merged in https://github.com/bluesky/bluesky/pull/1334. The
typo failed many tests, so I do not think any additional tests are
needed. I think #1334 was merged by mistake.
=> Fix critical typo in Movable.

bluesky/callbacks/mpl_plotting.py
The current error message misstates the module and name of the
function that needs to be called to initialize the Qt teleporter
=> Fix error message when teleporter is not running.

bluesky/run_engine.py, bluesky/tests/test_run_engine.py, requirements.txt
Accept an optional `status` kwarg in the callbacks defined inside of the RunEngine coroutines.
There were so many warnings coming out, travis was giving up on us
Test suite locally.
=> Account for change to expected signature in Status done callback

bluesky/bundlers.py, bluesky/tests/test_run_engine.py
This PR modifies`RunBundler.collect` to call `read_configuration`, if it exists, on the `collect` message object and the results are included in *all* descriptors.
This PR resolves #1337.
`test_flyer_descriptor()` in `test_run_engine.py` checks for the presence of key `configuration`.
=> Include configuration in flyscan EventDescriptor

bluesky/tests/test_run_engine.py
the `'wait'` message must be passed a group to wait for.
I think there is a race condition in if the status object does not fail fast enough from the background thread, the wait message gets processed.  The message was added in  0fab64ac8a8a8c5fa7a98158dd97190b774616f1 but without the group so attempting to process it fails.  This should remove at least one of the flaky tests on travis.
=> TST: Use legal wait message

bluesky/plans.py, bluesky/tests/test_plans.py
verify the signature of the per_step function meets requirements for back compatibility from 1.5.5 to 1.6.0.
in discussions with @tacaswell 
still to be tested.
=> verify nd step for scan_nd back compatibility

bluesky/plans.py
This PR make fly function return uid instead of None
https://github.com/bluesky/bluesky/issues/1332
In the context of bluesky tutorial  binder`Fly Basic` section  https://try.nsls2.bnl.gov
Script:
```
import bluesky.plans as bp
def custom_fly(flyer):
uids = (yield from bp.fly(flyer))
print('uid: ',uids)
return [uids]
def get_data_using_uid(uids):
for uid in uids:
print(db[uid].table(db[uid].stream_names[0]))
def big_plan(flyer):
uids = (yield from custom_fly(flyer))
get_data_using_uid(uids)
RE(big_plan([ifly]))
```
Output:
```
uid:  d5466512-b070-438a-8643-39ec6fe58ee4
time         x
seq_num                                        
1       2020-04-30 21:56:19.784460068  0.003487
2       2020-04-30 21:56:19.784499884  0.003527
3       2020-04-30 21:56:19.784512043  0.003539
4 …
```
=> ENH: fly will return uid

bluesky/bundlers.py
While reviewing code with @jklynch we found this loop that looks like it is a no-op.  I suspect that this is part of a re-factor that didn't get cleaned out.
This should make the RE marginally faster by not doing un-needed work
Should have no affect on the current test suite.
=> PERF: remove a no-op loop

bluesky/utils.py
Doing the init at import time is breaking xi-cam (which is a Qt
application and does many of its imports in a background thread).
This was here for back-compatibility to replace a function by the same
name, but because we went with a `block` method rather than a
`__call__` method if anyone was relying on this they are already
broken so remove with no attempt to shim it back.
=> FIX/API: do not create a DefaultDuringTask on import

bluesky/plan_stubs.py, bluesky/run_engine.py, bluesky/suspenders.py, bluesky/tests/test_examples.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_scans.py, bluesky/tests/test_suspenders.py, bluesky/tests/utils.py
This shims it out in our core code, there is still some usage in the
tests that will be trickier to remove.
This will become critical for the first facility that moves to py38 (it is _super_ noisy).
=> MNT: passing `loop=` to asyncio.Event is deprecated in py38

bluesky/callbacks/core.py, bluesky/tests/test_callbacks.py
Internally hash the keys we use to format the LiveTable rows.  This ensure that the value of the data keys can not corrupt the formatting.  Opted to go with a hash (because this is completely internal) rather than trying to sanitize the input as it seemed simpler.
fixes a bug that @stashlukj  ran into when trying to use ``:' ` as signal names.
Added another test of LiveTable.  Re-arranged the tests a bit.
=> FIX: allow ':' to be used in keynames and still format LiveTable

doc/source/hardware.rst
This PR fixes an inconsistency between docs [1] and schema [2] by updating the docs.
closes #1374 
see also https://github.com/bluesky/event-model/pull/180
[1] http://nsls-ii.github.io/bluesky/hardware.html#ReadableDevice.describe
[2] https://github.com/bluesky/event-model/blob/f33e54ac88ca7fa8588acd41a1f7e41b7610c269/event_model/schemas/event_descriptor.json#L23-L28
=> DOC: shape cannot be None

bluesky/tests/test_utils.py, bluesky/utils.py
The purpose of this PR was to demonstrate how CallbackRegistry works with different types of callables. This PR contains tests for CallbackRegistry class and some minor comments to the code of `CallbackRegistry` and `_BoundMethodProxy` classes. There are no changes to Bluesky code, so the PR should be safe to merge.
Main results:
- callbacks could be automatically unsubscribed (disconnected) only if they are bound methods. The following code will cause the callback to be removed from callback registry:
```
class AA:
def func(self):
<some code>
a = AA()
cid = cb.connect("sig", a.func)
del a 
```
No other type of callables that were tested is automatically disconnected: CallbackRegistry.disconnect(cid) must be explicitly used to remove them from the registry. For example, if the code above …
=> CallbackRegistry: tests and some code comments

bluesky/plan_patterns.py, bluesky/tests/test_utils.py, bluesky/utils.py, doc/source/hardware.rst
This PR changes the way that bluesky checks if an argument is "movable". Before: `isinstance(obj, Movable)`, now: `is_movable(obj)`.
Current behavior requires all of the expected attributes to be implemented as class attributes. With this PR, bluesky now checks instance attributes. For example, a class that defines `name` as an instance attribute at init time would have failed in old state but now passes. All objects that passed before should still pass.
closes #1377 
As an example of where current state gets weird, try running the following cell in a new notebook on https://try.nsls2.bnl.gov/
```python
from bluesky.utils import Movable
from bluesky.plans import grid_scan
%run scripts/beamline_configuration.py
motor = motor_ph
det = ph
RE(grid_scan([det], …
```
=> ENH: allow "movable" objects that match bluesky interface with instance attributes

bluesky/callbacks/mpl_plotting.py
Previously we were relying on the qt kicker to trigger the re-draws,
move the logic into the callbacks instead.
This is both more robust (it is still safe for something external to
check the stale status and trigger e re-draw) and more-correct (the
callback object knows when it is back to a consistent state and should
be re-drawn).
Issue of LiveGrid not updating reported via informal channels from CSX
Tested manually.
```python
import bluesky.plans as bp
from ophyd.sim import *
import matplotlib.pyplot as plt
plt.ion()
RE = RunEngine()
motor.delay = 1
motor2.delay = .1
RE(bp.rel_grid_scan([det], motor, -5, 5, 25, motor2, -4, 4, 16))
```
=> FIX: add draw_idle to LiveGrid and LiveScatter

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
Now `threading.current_thread()` will show a Thread with the name
bluesky-run-engine instead of something like Thread-1.
=> Give the RunEngine thread a useful name.

bluesky/utils.py
I am not sure why I made `_dump` a `staticmethod` but not `_load`.
Neither of them use instance state; they are just included in the class
for organizational reasons.
=> Minor refactor for internal consistency

bluesky/plan_stubs.py, bluesky/tests/test_plans.py
Simplify the logic in rd for Signal objects (objects without read_attrs)
Fixes a UnboundLocal error when used, discovered by @mygsage at FXI at NSLS-II
Extended existing test case to exercise this.
=> FIX: make sure bps.rd works with Signal (aka leaf) objects

bluesky/tests/test_persistent_dict.py, bluesky/utils.py
**WIP -- does not quite work yet**
Fixes #1388.
_"Those who do not study history are doomed to repeat it."_
We had an identical issue on https://github.com/Nikea/historydict/pull/27 which, funnily enough, was _also_ reported by @ambarb and _also_ fixed by me, back in 2016.
=> WIP: Add flush and flush upon gc/exit.

bluesky/utils.py, doc/source/hardware.rst
Currently bluesky requires objects to implement `stop` to pass the `is_moveable` check [1]. However if you look at RunEngine behavior it's clear that you expect devices that cannot be stopped to _not_ implement a stop method [2]. This PR attempts to clean up this discrepancy by making `stop` optional explicitly.
[1] https://github.com/bluesky/bluesky/blob/master/bluesky/utils.py#L1608
[2] https://github.com/bluesky/bluesky/blob/master/bluesky/run_engine.py#L1219-L1230
=> mark stop as optional for settable hardware

bluesky/plans.py
`x_start` and `y_start` are not legal arguments to `rel_spiral`
=> DOC: remove extra arguments from rel_spiral docstring

LICENSE, README.md
Updated links to point to current locations, and the LICENSE file to be more standard so that it is more easily recognized as the 3-clause BSD license.
Make it easier to install the latest version from the current Conda channel, and make the licensing clearer in the GitHub UI.
LICENSE update won't be definite until merged, but verified recognition in other repositories. Checked new links and channels in the browser and on the command line.
=> Readme and license updates

bluesky/bundlers.py
Log a debug-level message when resource and datum documents are emitted.
Documentation has been expanded and variables renamed for clarity in the affected method `save`.
Closes #1404.
All tests pass. No new tests added.
=> log when emitting resource and datum documents

bluesky/simulators.py, bluesky/tests/test_simulators.py
Fixes #1411 which provides details.
Revise to call each object's `check_value(pos)` method.  Removed local check of `msg.obj.limits`.
Note that `check_limits()` cannot know if same limits are a problem.  Also it cannot know if limits are exceeded if the object does not raise.
see #1411
Tested this code with the `hklpy.diffract.Diffractometer` class.  Other projects may also need to be tested with this code.
=> check limits should call objects' check_value() method

doc/source/hardware.rst
In #1412 we effectivley made ``check_value(...)`` an optional part of
the "bluesky interface" that movable devices should implement. This adds
it to the documentation on Movables and makes a couple other refinements
in the process.
=> Mention check_value() in bluesky interface docs

doc/source/tutorial.rst
Thanks to Will Smith from BESSY-II for pointing this out.
We could alternatively depend on caproto because it is easier to install
cross-platform, but since ophyd currently does not test against it,
that feels risky.
=> Add pyepics to tutorial dependencies.

.github/workflows/python-publish.yml
Adds a github action which builds and uploads sdist and wheel to pypi.
With this applied, a release can be initiated using the github release in the web ui (or api, eg the `gh` cli).
I do _not_ think pushing a tag alone triggers this, but have not actually tested that.
This does require someone with proper permissions adding Secrets via github settings for PYPI_USERNAME and PYPI_PASSWORD (I use a pypi token with limited scope for such things).
Since bluesky is pure python, universal wheel (well, py3 only, but noarch, no abi specified) should work, and matches what is uploaded currently (though this could be modified should that change).
This follows on from some conversations in the slack with @danielballan with an eye towards making releasing more automated.
That said, this does a real …
=> Add github action for autorelease via CI

bluesky/tests/test_persistent_dict.py, bluesky/utils.py
Critical bug fix
The `PersistentDict.update(..)` method writes updates to disk but does not update the in-memory cache. When the `PersistentDict` is finalized, the copy of disk is overwritten by the copy in the cache, so the update never takes effect at any point.
This bug occurred because methods of base class `zict.Func` were being called without updating our intermediate layer, `self._cache`. It seems to be the best way to avoid this kind of bug is to use composition instead of inheritance. `PersistentDict` now inherits from `collections.abc.MutableMapping`, and we can ensure that all updates flow through our code.
Unit tests added for each of the mutating methods (update, pop, popitem, setdefault, clear)
=> Fix persistent dict

bluesky/callbacks/core.py
The inline comment had drifted away from the relevant line.
=> DOC: attach comment to correct line again

bluesky/commandline/zmq_proxy.py
Minor changes that fix the issue of missing logging output for CLI ZMQ proxy. Addresses the issue https://github.com/bluesky/bluesky/issues/1438.
Logging output functionality may be manually verified by starting ZMQ proxy in a terminal as
```
bluesky-0MQ-proxy 5577 5578 -v
```
or
```
bluesky-0MQ-proxy 5577 5578 -vvv
```
and running the following code in IPython session another terminal:
```
from bluesky.plans import count
from ophyd.sim import det
from bluesky.callbacks.zmq import Publisher
publisher = Publisher('localhost:5577') 
RE = RunEngine()
RE.subscribe(publisher)  
RE(count([det])) 
```
The logging output in the terminal running proxy should display the contents of 'start' and 'stop' documents if the proxy was started with `-v` and all documents …
=> FIX: logging for CLI version ZMQ Proxy

bluesky/commandline/zmq_proxy.py
Followup to PR https://github.com/bluesky/bluesky/pull/1439.
The parameter `logfile` in `bluesky.commandline.zmq_proxy.start_dispatcher` has no effect now. It is unlikely that this function is used anywhere except internally in `bluesky.commandline.zmq_proxy` module, but it could be a good idea to raise an exception with meaningful deprecation message.
Changes in this PR include: 
- default value `logfile=None`.
- raise exception with deprecation message if `logfile` is not `None`.
=> Deprecating parameter 'logfile' in 'start_dispatcher' function

docs/source/hardware-interfaces.rst, docs/source/hardware.rst, docs/source/index.rst, docs/source/tutorial.rst
Add hardware interfaces page to docs.
As discussed with @danielballan I am trying to update the docs to be more useful to small labs (and non-EPICS users in general). My next step is to flesh out `hardware.rst` to give much more concrete advice about how to implement Bluesky interfaces. In the long run I hope to reach out to some of the existing hardware support libraries and try to see if they would be willing to add Bluesky Hardware Interface compliance to their "device" classes.
I'm aware that some of these linked packages aren't polished, but I feel like if we're going to start building an ecosystem we have to start by at least advertising what we have.
=> add hardware-interfaces page

bluesky/callbacks/zmq.py
This adds a number of try-except blocks to the 0mq RemoteDispatcher to not silently fail when un-expected messages come across the socket.
This fixes failures of the xpdan servers at XPD/PDF that we believe are caused by the network scanners pushing random byte strings into the zmq proxy.  The proxy is OK with this, but the subscribed clients are not.
This can be tested by starting up the proxy, starting a dispatcher as
```python
from bluesky.callbacks.zmq import RemoteDispatcher
RemoteDispatcher('localhost:5578').start()
```
and in another terminal
```python
import zmq
url = 'tcp://localhost:5577'
context = zmq.Context()
socket = context.socket(zmq.PUB)
socket.connect(url)
socket.send(b' \x80abc ')
socket.send(b' start ')
socket.send(b' start abc')
socket.send(b'')
```
=> Tolerate garbage on zmq

docs/source/api_changes.rst
I've not included documentation changes. I've probably missed changes and described things poorly, so a careful eye is warranted for whomever reviews.
https://github.com/bluesky/bluesky/compare/v1.6.7...master
=> release prep: document API changes

.github/workflows/python-publish.yml
Automatic release action failed. Note this is the first time we are actually trying to do an auto-release.
```
twine upload: error: the following arguments are required: dist
```
https://github.com/bluesky/bluesky/runs/3068462859?check_suite_focus=true#step:5:86
=> forgotten argument dist to twine upload

docs/source/index.rst
Changes the bluesky, ophyd, databroker, and suitcase links in the bluesky documentation sidebar/table of contents to point to the blueskyproject.io pages, not the old nsls-ii.github.io pages. This should reduce confusion as people won't be linked to out-of-date docs. Closes #1451 
Only docs/source/index.rst was modified. I verified that the HTML still builds fine, and the new links work.
The links to repositories could probably also stand to be updated, but I wasn't sure if there is a new global issue tracker, or if I should link directly to bluesky/issues. I would be happy to change these links as well.
=> DOC: Update TOC links to blueskyproject.io

.github/workflows/testing.yml, setup.py
Already use Bluesky with Python 3.9, but don't currently test against it or officially document that support. I hope this doesn't make tests any slower.
=> MNT: making 3.9 support official

bluesky/protocols.py
Working further, and having been schooled by @ksunden in #1466, I'm now on the exact opposite side of the problem. The current implementation of `Status` does not work with our existing classes because we _do_ use `@property`. Error given is "expected settable variable, got read-only attribute".
Current behavior does not pass existing Status objects.
Passes on yaqc_bluesky after this change.
=> BUG: done and success should not be class attributes of Status protocol

bluesky/tests/conftest.py, bluesky/tests/test_callbacks.py
In the test suite, we currently reach into databroker's test fixtures and make a databroker using its deprecated sqlite backend. In this PR, we use `databroker.temp()` instead, which currently generates a msgpack-backed catalog.
=> Use databroker.temp instead of sqlite databroker.

bluesky/plans.py
Update function always returns None, thus the expected dictionary was not actually included
Rework plan pattern args to not use `update`, as that does not return the dictionary it is updating.
Ran a list_grid_scan, ensured that the plan_pattern_args were not null.
=> Fix list_grid_scan md for plan pattern args

.github/workflows/testing.yml, bluesky/bundlers.py, bluesky/run_engine.py
The loop parameter on many asyncio functions was deprecated in py38 and
removed in py310.
The solution we had implemented was to pass None on py38 and above, however in
py310 the parameter is removed and passing `loop=None` is a TypeError.
This switches to unpacking a dictionary (which is empty on py38+)
This also removes an used loop parameter and attribute on RunBundler.  This was
a vestigial attribute from when the RunBundler logic was pulled out of the
RunEnigne and was never used.
Without this change we have will-not-start errors on py310 pre-releases, tested locally and passes.
=> API/MNT: do not pass loop kwarg if we do not have to

bluesky/bundlers.py, bluesky/tests/test_flyer.py, bluesky/tests/test_scientific.py, bluesky/tests/utils.py
Fix descriptors for flyers that do not implement read_configuration.
Previously if `read_configuration` was not defined we would not put an entry in the configuration key in the descriptor.  While the RE would run OK, this would case issues on data access with newer versions of databroker. 
I do not think we want to make a distinction between in the documents between "the device reported configuration and it was empty" from "the device did not report any configuration".
Added new test
=> Fix descriptors for flyers that do not implement read_configuration

.gitignore, requirements-dev.txt
The assumption about general issues with `sphinx_rtd_theme` turned out to be incorrect and the package does not need to be pinned to the previous version.
The issue was observed while building the documentation for `bluesky-queueserver` project, which is using custom CSS files for formatting the tables (e.g. https://blueskyproject.io/bluesky-queueserver/re_manager_api.html#environment-open). The issue was fixed in PR https://github.com/bluesky/bluesky-queueserver/pull/193
=> Unpin 'sphinx_rtd_theme'

bluesky/run_engine.py
I do not understand why this is not failing on CI as we are passing a dictionary instead of an event loop!
We need to unpack the loop kwargs dictionary.
This fails many many tests on py310, but I am very confused why this is not failing on older verisons of Python as well.
Run locally.
=> FIX: catch last py310 issue

.gitignore, bluesky/callbacks/fitting.py, bluesky/tests/test_bec.py
Implements human-readable `__repr__` for the `PeakStats` (continuation of improvements of #1478).
This PR adds the `__repr__` and `__dict__` methods to easily see the data for the stats and derivative stats.
Used a hint from https://stackoverflow.com/a/34166604 regarding `._asdict()` for namedtuple objects.
The previous way of reporting the PeakStats information was hard to use. Example from @gfreychet:
```py
bec._peak_stats
Out[29]: {'bd52e883-7422-4b3b-94a4-a4b5adbaaebc': {'pil1M_stats1_total': <bluesky.callbacks.fitting.PeakStats at 0x7f046f6b9850>}}
```
With this update:
```py
In [15]: bec._peak_stats
Out[15]:
{'f38cbe6a-029f-493a-a07c-73c4eb45a799': {'det': {'derivative_stats': {'cen': 0.0999999999999998,
'com': -0.8,
'crossings': array([0.1]),
'fwhm': None,
'lin_bkg': None,
'max': …
```
=> ENH: implement human-readable repr for `PeakStats`

docs/source/hardware.rst
Just want to write this down for my own future reference, if nothing else.
I haven't thought about it in detail, but perhaps tests or assertions would help enforce expectations here---something for a later PR.
Document intended behavior of `fraction` argument.
See https://github.com/bluesky/ophyd/pull/1022.
Documentation.
=> DOC: write down intended behavior of fraction

setup.py
Adds all of the extra dependencies used in the conda-forge recipe to setuptools.
I've grouped them arbitrarily here based on my simple understanding. Other grouping suggestions would be appreciated :smile:.
Closes #1408.
Add `extras_require`. Can install with bracket syntax using pip. For example, from source:
```bash
$ python -m pip install -e .[all]
```
Here are the dependencies in full (as resolved on my machine):
```bash
$ pipdeptree --freeze
bluesky==1.6.4.post262+ge8a7f495
cycler==0.11.0
event-model==1.17.2
jsonschema==4.4.0
attrs==21.4.0
pyrsistent==0.18.1
numpy==1.22.2
historydict==1.2.3
msgpack==1.0.3
msgpack-numpy==0.4.7.1
msgpack==1.0.3
numpy==1.22.2
numpy==1.22.2
super-state-machine==2.0.2
six==1.16.0
toolz==0.11.2
tqdm==4.63.0
zict==2.1.0
HeapDict==1.0.1
colorama==0.4.4 …
```
=> ENH: add extra dependencies

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
Some of the device objects we are passing into bluesky happen to have an attribute `stage` that has nothing to do with Bluesky's concept of `Stageable`. Since we already have protocols, we can use them to make the run engine smart enough to not attempt calling `stage` on our objects.
There are other places in the run engine where protocols could be used, but I'm going to ignore those in favor of solving the problem in front of us now.
As always, feel free to reject or propose alternative solutions. If the answer is "please don't ever pass anything with attribute `stage` this is expected behavior" we can work with that.
Replace `hasattr(obj, 'stage')` with `isinstance(obj, bs_protocols.Stageable)`.
See https://gitlab.com/yaq/yaqd-attune/-/issues/6
Tests written.
=> ENH: don't call stage unless stageable

bluesky/callbacks/best_effort.py, bluesky/tests/test_bec.py
Closes #1508 
1. Add a unit test for the desired behavior. 
2. Refactor plotting set up from the processing of descriptor documents in BEC to a private function. This allows a premature return in the plotting to not stop the descriptor processing. 
3. Add a warning and explanation at the premature return. 
https://github.com/maffettone/bluesky/blob/145dea576cc992a4e7fefe63ad9655f1bb4d1bf4/bluesky/callbacks/best_effort.py#L199-L203
The BEC prints no LiveTable, produces no Figures, and doesn't tell the user why.
This largely happens because of this return statement in the descriptor processing
An additional unit test was added `test_bec.test_many_motors` to ensure that no plot gets made with higher dimensional motors, a warning is issued that recommends adjusting the hints for BEC if plots …
=> Many motor BestEffortCallback

bluesky/plan_stubs.py
The docstring had things from the Parameters in the Yield section.
=> DOC: fix docstring on plan_stubs.close_run

.github/workflows/testing.yml, bluesky/tests/conftest.py, bluesky/utils/__init__.py
This is the start of work to support future versions of Python + QT + databroker
=> Future support

bluesky/run_engine.py, bluesky/tests/test_examples.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_suspenders.py, docs/source/api_changes.rst
While looking at the #1501 and friends we had questions about if we needed to protect possible I/O with locks.  This refactors that code so that we do not need a lock.
Suspenders work by injecting (a bunch of ) plans onto the plan stack (why not just one you ask....that is a very good question...~for a later date~ the last commit in this PR).
Previously the sync function (called from the Suspenders classes from a background thread (in the case of ophyd the ophyd trampoline thread)) would create a task that would then muck about to add the plans to the plan stack, do any rewinding, set up the wait etc.  If we were to put any awaits in this coroutine than there is a chance that the `_run` task would get time again and we would end up in a possibly inconsistent state!
This refactor moves all …
=> MNT: clarify how suspenders get evaluated

bluesky/callbacks/best_effort.py
Change the logic to create enough axes but not too many in the grid. `>=` instead of `>`. 
The logic here produces a 3x3 grid for 6 plots instead of a 2x3 grid. This is exceptionally problematic for these intervals, because there will be no x-axis labels with the shared axes, since the entire bottom row will have `visible = False`.
Adjusting the logic will create enough plots. 
I am guilty of not using the `tests/interactive/best_effor_cb.py` because of errors with old versions of databroker. 
I did run this sanity check to make sure the logic would always produce enough axes, and that removing a full row would create an invalid figure with not enough axes (therefore is necessary). 
```python
import numpy as np
for l in range(5, 20):
nrows = ncols = int(np.ceil(np.sqrt(l)))
while …
```
=> Bad comparison created too many axes for plots

bluesky/plan_stubs.py, bluesky/tests/test_plans.py
Previously we would get confusing errors when:
- event had been opened
- read or describe raise any errors once
- a wrapper (such as the baseline pre-processor) tries to take a reading as
part of plan clean up
The error would be that you could not open an event with an event open which
would effectively drop the original error (the one you actually need to debug
the issue!) on the floor.
This could also be fixed by improving the multi-exception handling in the RE,
but this is a simpler fix.
These errors are among the most confusing.  I helped @maffettone debug one of these today and finally got my act together to write this patch.
The fix is to make sure that `trigger_and_read` never leaves an event "open" when it returns control to its caller.
Added a test.
=> FIX: make trigger and read careful

bluesky/plan_patterns.py, bluesky/tests/test_examples.py
Fixes new style checks.
Due to changes in linting tools these are now being flagged.
=> STY: fix whitespace around keywords

bluesky/run_engine.py
In `RunEngine`'s `__init__`, make sure a user-supplied event loop is also registered.
Some utilities in `bluesky` like `check_limits` require the `bluesky` event loop to be set, but it doesn't get set for users who supply their own event loop. A user who does this will get a cryptic "Bluesky event loop not running" error in these cases.
Makes my repo's tests pass again (was passing pre-v1.9.0), I didn't check against bluesky's internal tests.
=> FIX: register the user's passed in event loop

bluesky/tests/conftest.py
Don't need to call `set_bluesky_event_loop` in test fixture anymore
#1539 sets the bluesky event loop to the user supplied one, so the fixture no longer needs to
CI
=> Tidy test fixture

bluesky/utils/__init__.py
This short circuits the `snake_cyclers` method in `utils` to use the equivalent multiplied cyclers when there is no snaking.
This is primarily a memory usage consideration.
The cycler object represented by multiplied cyclers is much smaller than the fully expanded cycler (which is equivalent) that this method currently produces.
Even for some modestly sized scans such as (11, 101, 101), the full cycler produced was eating hundreds of MB of RAM when all of the data was repeated anyway.
The existing snaking tests already do exactly what I would want to do to test this: ensure that the output is as expected.
=> Use multiplied cyclers for non-snaked axes

bluesky/callbacks/best_effort.py, bluesky/tests/test_bec.py
Making sure each column of live grids in the BEC have x-tick labels. This is not an issue for rows since the plots in the square grid are filled top to bottom, left to right. 
Add a section on sanity checking for 2d grids of plots. This prevents the bottom row from producing an invisible axis, then leaving a column with no x-tick labels. 
Followed the documentation suggestion from https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html, and made the adjustments post-hoc using `tick_params`. 
CSX beamline likes to plot lots of detectors at once. 
https://jira.nsls2.bnl.gov/browse/SXSS-205
Unit tests were added for checking the number of total visible plots and the axis tick label visibility.
=> FIX: LiveGrids placing x-axis tick labels on all columns

docs/source/documents.rst
The word `containing` was not spelled out on this page: https://blueskyproject.io/bluesky/documents.html#overview-of-a-run
=> DOC miniscule typo, hardly worth a bother

bluesky/suspenders.py
Adds more context to the justification emitted by the suspenders.
Not including the resume condition lead beamline staff to become concerned we were doing "new math".
Covered by existing test cases, however we do no check the contents of stdout, disabling capture and running the tests locally gives
```
.Suspending....To get prompt hit Ctrl-C twice to pause.
Suspension occurred at 2022-12-08 13:25:32.
Justification for this suspension:
Signal bool_sig = 0 fell below 0.5 and has not yet crossed above 0.5.
Suspender SuspendFloor(Signal(name='bool_sig', value=1, timestamp=1670523933.1577613), sleep=0.2, pre_plan=None, post_plan=None,tripped_message=) reports a return to nominal conditions. Will sleep for 0.2 seconds and then release suspension at 2022-12-08 13:25:33.
0.9057326316833496 …
```
=> ENH: add resume thresholds to suspender justification message

bluesky/run_engine.py
Removing deprecated get_event_loop() as py3.6 has been dropped 
get_event_loop() changed to get_running_loop()
py3.6 has been dropped 
All unit tests pass locally. In a python 3.9.1 venv.
=> DEP: remove deprecated get_event_loop()

bluesky/protocols.py, bluesky/tests/test_new_examples.py
Made protocol methods abstract. Added missing method definitions in protocol subclasses defined in unit tests.
We'd like to use abstract classes for protocols as discussed here #1547 
Closes #1547 
Tested inside `test_new_examples.py` using initialisation of classes `Jittery` (subclass of  `(Readable, Locatable)`) and ` AsyncLocatable` (subclass of `Locatable`).
=> Made protocol methods abstract

bluesky/plan_stubs.py, bluesky/protocols.py, bluesky/run_engine.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_run_engine.py
Let stage and unstage return Status objects, so multiple objects can be staged at once.
I have made changes to  `_stage` and `_unstage` to allow Stageables to return status objects from their stage and unstage methods. The changes mimic `_trigger`. 
I have changed the type hints on the Stageable protocol.
I have created a test for staging 2 Stageables at once.  
I have also changed the plan stubs accordingly.
resolves #1559 
This change will allow the run engine to stage multiple devices without blocking. And these can then be awaited but a wait message.
These changes have been tested by a new test `test_stage_and_unstage_status_objects()`.
Which stages/unstages 2 dummy Stageables then awaits their completion.
The new `_stage` and `_unstage` methods use `isinstance()` to check to see if …
=> ENH: make stage and unstage return status objects

bluesky/plan_stubs.py, bluesky/tests/test_plans.py
This removes the  explicit default `trigger_and_read` from the function definition signature.
Instead of the callable in the signature, the default is set to `None`, and then checked to replace with `trigger_and_read`. 
This issue pops up when importing these plans into the startup files used by the queue-server. 
- `one_nd_step`
- `one_1d_step`
- `one_shot`
```
```
Copied these new plans into a queserver test environment.
=> FIX: Remove callable from plan signature for qserver

bluesky/callbacks/best_effort.py
Move the resolution of the default figure factory in BestEffortCallback to the `__init__` from its call site.
General cleanup, doing this early is better than doing this late (and every time).
CI
=> MNT: move fig_factory default resolution in BestEffortCallback

bluesky/bundlers.py, bluesky/examples.py, bluesky/plan_stubs.py, bluesky/plans.py, bluesky/preprocessors.py, bluesky/run_engine.py, bluesky/tests/test_bec.py, bluesky/tests/test_callbacks.py, bluesky/tests/test_devices.py, bluesky/tests/test_examples.py, bluesky/tests/test_multi_runs.py, bluesky/tests/test_new_examples.py, bluesky/tests/test_plans.py, bluesky/tests/test_ramp_plan.py, bluesky/tests/test_run_engine.py, bluesky/tests/test_scientific.py, bluesky/tests/test_supplemental_data.py, docs/source/conf.py, docs/source/examples/multi_run_plans_nested.py, docs/source/examples/multi_run_plans_recursive.py, docs/source/examples/multi_run_plans_select_cb.py, docs/source/examples/multi_run_plans_sequential.py, docs/source/tutorial.rst
In discussions with PSI (SLS2) at NSLS-II today it became clear that we need the ability to pre-declare what the streams will be before we create the first event.  This will have at least three and a half major benefits
1. it makes the first measurement less special as we can ensure that the describe / read_configuration / describe_configuration happen when we think they wil
2. they will enable the bundler to live in a different process and still correctly accumulate all of the notifications it will need
3. it is now possible to get the descriptor is a custom plan without subscribing to the output stream
4. the RunBundler class is now pluggable by class level monkey patching or thin sub-classing (could be convinced to make it init time configurable...)
In local testing I added a "strict …
=> Add ability to pre-declare a stream

docs/source/conf.py
When event model started writing versioned docs the path for intersphinx changed, this fixes it
Let's see if CI passes...
=> Point at newly versioned event model docs

bluesky/run_engine.py
Previously we had an exception being raised like so:
`raise FailedStatus(ret).with_traceback(ret.__traceback__) from exc`
It's been brought to my attention that this is redundant, so I've just removed the dunder method here.
=> removed with_traceback call

docs/source/tutorial.rst
Next section of the tutorial uses 3 motors and fails, so we should import the third here. In running a session based on the tutorial users were confused about why they saw no plot from the 3D grid so added an explination.
Help avoid confusion
=> DOC: Tidy up tutorial around gridscans

bluesky/protocols.py, requirements.txt
Use a softer import mode for protocols
The `Protocol` class is available in `typing_extensions` until Python3.8, when it becomes part of `typing`.
Currently, we try to import from `typing_extensions` and, if there is an error, assume we are in Python3.8 or higher and import from `typing`. This presents a problem if you are using Python3.8+ and still using `typing_extensions` for another purpose, then the import from `typing_extensions` will succeed. This can be a problem if you wish to subclass one of the protocols. This PR enforces always using `typing` if the Python version is greater than 3.8.
Checked protocol still imports.
CI passes
=> Use Python version check rather than import error check to import Protocol

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
We were not removing the old public tokens on subscribe so the internal state would grow without bounds.
@dmgav Noticed that the internal mapping between the public and private subscription tokens was never reduced in size
We should not have unbounded caches!
Added a test.
=> FIX: do not leak public token maps

bluesky/callbacks/best_effort.py, requirements-dev.txt
Fixes a documentation failure due to mpl 3.7.2 warning on repeated calls to `fig.tight_layout` (https://github.com/matplotlib/matplotlib/issues/26290 / 
https://github.com/matplotlib/matplotlib/pull/26300).
This drops our use of `fig.tight_layout()` in favor of using constrained layout.
This puts a floor on our Matplotlib support at 3.5.0 (Nov 2021) when the `layout` kwarg was added.
Fixes a doc build failure found by @evalott100 .  The docs build is failing on the current default branch, this fixes the docs build.
existing tests + docs pass.
=> MNT: use constrained rather than tight layout

bluesky/protocols.py
Make it return `Optional[BaseException]` like `Future.exception()`
So it's easier to make `ophyd.v2.core.AsyncStatus.exception` (as this is what `Task.exception()` returns)
=> Tweak Status.exception() protocol

bluesky/preprocessors.py, bluesky/tests/test_preprocessors.py
Add an option to contingency_wrapper to not automatically re-raise if the except plan returns a value rather than raising its own exception.
We have to do this with a flag like this for back-compatibility reasons
We made a design mistake with contingency_wrapper because there is no way to actually suppress the exception. The reason we wrote this wrapper (and finalize wrapper) is to keep users from having to understand the extra set of constraints around the cancel and generator exit exceptions so this omission defeats the point.
Added unit tests that should cover all functionality. The first unit test added ensures backwards compatibility and also passes on `master`
Built on original PR https://github.com/bluesky/bluesky/pull/1526
=> ENH: Allow the contingency wrapper to eat exceptions

docs/source/tutorial.rst
The `exit_status` value of an aborted run is recorded in the stop doc as `abort`, make it match here in the docs.
Just a typo correction.  The CI fail is not related.  (It failed when the branch was first created with no changes.)
=> Fix a typo in the tutorial.

bluesky/bundlers.py
The comparison in https://github.com/bluesky/bluesky/pull/1615 is erroneous:
```
>>> DocumentNames.stream_datum
<DocumentNames.stream_datum: 'stream_datum'>
>>> "stream_datum" == DocumentNames.stream_datum
False
>>> "stream_datum" == DocumentNames.stream_datum.value
True
```
=> Fixed error

bluesky/protocols.py
When developing ophyd-async I found a problem with the return type of WritesExternalAssets, so this PR is simply to fix that.
collect_asset_docs should definitely not return nested iterators.
=> Modify return type of WritesExternalAssets.collect_asset_docs

bluesky/bundlers.py
If a collect message returns nothing, this is not an indicator of a failing plan. So we should not raise an error/exception.
At the moment, we are raising a `RuntimeException` if a collect message does not return stream datums/events/event pages. But for the case of fly scanning, a collect message (e.g. queried every so often) could return nothing, and the bundler should be able to handle this case.
A plan with a flyer can look something like:
```
yield from bps.kickoff(flyer)
complete_group = group_uuid("complete")
yield from bps.complete(flyer, group=complete_group)
done = False
while not done:
try:
yield from bps.wait(group=complete_group, timeout=flush_period)
except TimeoutError:
pass
else:
done = True
yield from bps.collect(
flyer, stream=True, return_payload=False, name=stream_name …
```
=> Update bundlers.py to not raise RuntimeError for empty collect

bluesky/preprocessors.py, bluesky/tests/test_new_examples.py
Use stage_all and unstage_all to wait for staging to complete when stage returns a Status rather than blocking
When we added async stage we didn't update all the plan preprocessors to `Msg('wait', group=g)` after a series of`Msg(`stage`, group=g)`. This is the cheapest change, although we will have to also fix `lazy_stage_wrapper` in another PR, and there may be other places emitting `Msg('stage')` directly rather than using `bps.stage()`. 
Is this correct? Or should we make the run engine wait for stage/unstage always unless it gets a group in the stage message?
Locally, no additional tests written yet
=> Wait for async staging in stage_wrapper

bluesky/run_engine.py, bluesky/tests/test_run_engine.py
RunEngine._wait now waits until wait_for message has been produced before removing futures from groups/status objects
=> Remove group from groups after Msg('wait_for'), not before, in RunEngine._wait

bluesky/plans.py, bluesky/tests/test_plans.py, bluesky/tests/test_run_engine.py
This is the code + testing part of making stream pre-declaration opt-in, it still needs documentation.
Pre-declaring streams seems like a good idea in general (and it solves some problems) so in #1542 we made the built in plans do so by default.  However this exposed some ophyd objects (notable AD) that were using the `trigger` method to sort out what the keys will be.  If you call `describe` before `trigger` you get different answers so going all-in on this by default is a bit too aggressive.
closes #1609 
Added tests and modified two test that assumed the existence of pre-declare a bit too hard to easily un do.
=> API: add ENV to opt-in to automatic stream predeclaring

requirements.txt
In most of the build testing, `typing_extensions` has been satisfying this requirement. We found some edge cases in using a ROS2-Humble dev container that breaks this for system python. 
Following information here: https://typing-extensions.readthedocs.io/en/latest/#
> NotRequired
> See [typing.NotRequired](https://docs.python.org/3.12/library/typing.html#typing.NotRequired) and [PEP 655](https://peps.python.org/pep-0655/). In typing since 3.11.
> New in version 4.0.0.
ROS development comes with lots of dependencies, and the build tools add an older version of `typing_extensions`. 
Tested in two containers. The base images here introduce the complexity when installing ament build tools. 
```RUN apt install ros-humble-ament-*`
This works:
```docker
FROM althack/ros2:humble-dev
RUN mkdir …
=> BLD: typing_extensions needs NotRequired (new 4.0.0)

bluesky/bundlers.py, bluesky/plan_stubs.py, bluesky/protocols.py, bluesky/run_engine.py, bluesky/tests/test_flyer.py, docs/source/hardware.rst
resolves https://github.com/bluesky/bluesky/issues/1637
=> Add prepare command to RunEngine and bundler, as well as protocol

docs/source/debugging.rst
Examples in the debugging section had some typos and so would not run. Now they should run.
=> DOC: Fixed examples in debugging docs

bluesky/bundlers.py, bluesky/tests/test_run_engine.py
The issue is that:
- we track the event count (for seq_num which is non-monotonic and
can repeat if rewound) in `Bundler._sequence_counters`
- we snapshot the counters at checkpoints
- on rewind we clear the _event_counters dictionary and then .update it
from the copy
In the case of implicitly creating a stream between a checkpoint and a
pause (so there is `declare_stream` message) the above process effectively
drops our tracking in the event counters.
In `_prepare_stream` we ensure that the needed counter exists (and starts at 1)
so replicate that logic here.
We should not crash this way.
Manually + adding a test
=> FIX: handle case of rewinding to before the beginning of a stream

bluesky/bundlers.py, bluesky/plan_stubs.py, bluesky/protocols.py, bluesky/tests/test_external_assets_and_paging.py, bluesky/tests/test_seq_num_indices_in_sync.py, bluesky/utils/__init__.py
Changes the collect method in bundler to handle the collection of multiple detectors. Contains the logic to collect stream resources using the maximum common number of frames written, determined by the minimum index.
`Asset` has been altered to only address a `resource` and `datum` and a new `StreamAsset` has been created to address `stream_resource` and `stream_datum`.
This enables logic to be moved out of Ophyd-async, generalising the process
Fixes #1649.
TBC.
=> Enable collect for multiple detectors

src/bluesky/plan_stubs.py, src/bluesky/tests/test_flyer.py
This adds the multiple object functionality to the kickoff and complete plan stubs. This will neaten up the plans.
=> Alter ko and complete plan stubs to take multiple flyables

.github/workflows/ci.yml, Dockerfile, docs/run_engine.rst, src/bluesky/callbacks/best_effort.py, src/bluesky/callbacks/zmq.py, src/bluesky/run_engine.py, src/bluesky/tests/conftest.py, src/bluesky/tests/test_bec.py, src/bluesky/tests/test_callbacks.py, src/bluesky/tests/test_examples.py, src/bluesky/tests/test_plans.py, src/bluesky/tests/test_run_engine.py, src/bluesky/tests/test_zmq.py, src/bluesky/tests/utils.py, src/bluesky/utils/__init__.py
Fixes two issues with numpy 2.0
- use `np.prod` instead of `np.product`
- simplify a test (that it was not really clear what it was testing ... or why that was being tested _here_)
=> MNT: numpy 2.0 compatibility

.devcontainer/devcontainer.json, Dockerfile
This is a  fix for the tests failing in the developer container.
To reproduce the issue open the repo in vscode and choose 'reopen in container' then run pytest (or tox -p).
The fixes are:
- rebase over https://github.com/bluesky/bluesky/pull/1672 to fix "main thread is not in main loop"
- add qt library into system depenedencies
Note that this still has pop ups for the interactive tests but that will be looked at in a separate issue https://github.com/bluesky/bluesky/issues/1689. The devcontainer supports X11 for this purpose.
=> Fix for #1693 - tests failing in devcontainer

pyproject.toml, src/bluesky/__main__.py, src/bluesky/tests/test_cli.py
Adding `__main__.py` with simple main entrypoint that prints version, update `pyproject.toml`.
Solves #1667
```
(venv) [jwlodek@vdi-10-65-15-187 bluesky]$ which python
~/Workspace/bluesky/venv/bin/python
(venv) [jwlodek@vdi-10-65-15-187 bluesky]$ python --version
Python 3.11.5
(venv) [jwlodek@vdi-10-65-15-187 bluesky]$ python -m bluesky --version
1.13.0a4.dev31+g6168e9d0.d20240415
```
=> [ENH] Add __main__.py and entrypoint for checking version info.

pyproject.toml
This fixes #1689.
In vscode pytest collection is run every time changes are made in the test folder and this was causing MPL windows to pop up. This was disruptive.
The change tells pytest not to collect from the interactive subfolder of tests. This has no effect on the number of pytest tests collected as there are no pytest functions in the folder. However, it does take away some checks as exceptions happening when loading these modules would previously have caused pytest to abort and report the issue (thus not running the remaining tests).
@tacaswell was the intention for these tests to be executed in CI - if so a different approach is required.
One thing to note: there are still a couple of popups when executing the tests but this could be suppressed using `MPLBACKEND=agg pytest`. This …
=> Dont collect interactive tests

pyproject.toml
7.3 appears to be breaking the build, this PR pins it to unblock people. Issue to investigate further: https://github.com/bluesky/bluesky/issues/1716
=> Pin Sphinx to <7.3

pyproject.toml
Include python3.12 classifier in pyproject.toml
Leftover work from #1672 and #1683
=> Include Python3.12 Classiefier

src/bluesky/callbacks/mpl_plotting.py, src/bluesky/tests/test_callbacks.py
Add a keyword argument `title=""` to `LiveGrid.__init__` that allows overriding the default title generated from the scan number.
Fixes #1396 
```
from ophyd.sim import det4, motor1, motor2
from bluesky.callbacks.mpl_plotting import LiveGrid
from bluesky.plans import grid_scan
RE = RunEngine()
RE(
grid_scan([det4], motor1, -3, 3, 6, motor2, -5, 5, 10, False),
LiveGrid((6, 10), "det4"),
)
```
```
from ophyd.sim import det4, motor1, motor2
from bluesky.callbacks.mpl_plotting import LiveGrid
from bluesky.plans import grid_scan
RE = RunEngine()
RE(
grid_scan([det4], motor1, -3, 3, 6, motor2, -5, 5, 10, False),
LiveGrid((6, 10), "det4", title="MY PLOT"),
)
```
```
from ophyd.sim import det4, motor1, motor2
from bluesky import …
```
=> Expose API to set title on LiveGrid plots

src/bluesky/tests/conftest.py
Addresses #1727. This was the only occurrence of the `tmpdir` fixture in the `tests` directory currently.
Tests seem to run OK.
=> Use tmp_path instead of tmpdir fixture

pyproject.toml, src/bluesky/tests/test_zmq.py
8 tests in the test_zmq.py has been failing on MacOs system and it seems like there is a problem in pickling done in the `multiprocessing` module. The problems seems to be resolved by importing `multiprocess` which seems to be using dill  instead as suggested in [this example](https://stackoverflow.com/questions/72766345/attributeerror-cant-pickle-local-object-in-multiprocessing)
We run all tests both on Linux and MacOS after this change and problem seems to be solved.
=> MacOS fix for failing tests in the test_zmq.py 

src/bluesky/callbacks/tiled_writer.py
In the latest Tiled release, `get_data_sources()` changes its return type from `list[dict]` to `list[DataSource]` (a `dataclass`). Correspondingly, here in the `TiledWriter`, we need to update the usage from `data_source["id"]` to `data_source.id`. With the change, tests pass.
=> Update for Tiled API change.

pyproject.toml, src/bluesky/tests/test_seq_num_indices_in_sync.py
The release of event-model 1.21.0 changed the schema of the experimental StreamResource document. This PR updates the tests to match.
This PR also fills in more realistic values for the dummy documents and switches to using keyword arguments. Neither of these changes affect how the code runs, but aim to make it a little easier to follow.
=> Update test for revised StreamResource.

docs/msg.rst, src/bluesky/plan_stubs.py, src/bluesky/run_engine.py, src/bluesky/tests/test_run_engine.py
Also updated docs to reflect this, and added a test.
=> returned the results of `asyncio.wait` in `bps.wait_for`

src/bluesky/consolidators.py, src/bluesky/tests/test_tiled_writer.py
During testing of ophyd-async devices, I was seeing a traceback caused by a KeyError on the `path` key. This is because in newer versions of ophyd-async the stream resource uses `dataset` as the parameter key name, rather than `path`: https://github.com/bluesky/ophyd-async/blob/5ac94e283b170b603df42a7d5fe33fd7f2786524/src/ophyd_async/core/_hdf_dataset.py#L64
```
doc = {'uid': '17a66a91-2b4a-40ae-b9be-97921a94bcd1', 'data_key': 'manta-cam1', 'mimetype': 'application/x-hdf5', 'uri': 'file://localhost/ns
ls2/data/tst/legacy/mock-proposals/2024-1/pass-000000/assets/proj_1b2430d3-2c75-48c2-8267-7bab4e20d63f.h5', 'parameters': {'dataset': '/entry
/data/data', 'swmr': False, 'multiplier': 1}, 'run_start': '98494492-75ff-49f2-a332-41d8e3fcd065'}                                           
``` …
=> Update the name of the path in HDF sres parameter

src/bluesky/consolidators.py, src/bluesky/tests/test_consolidators.py, src/bluesky/tests/test_tiled_writer.py
Allow for using dtype_numpy keyword as specified in ophyd async
Decision was made to use `dtype_numpy` for the machine data type of resources in `ophyd_async` this change allows for using it alongside the older `dtype_str`
=> Update to allow for using dtype_numpy key alongside old dtype_str

src/bluesky/tests/test_utils.py, src/bluesky/utils/__init__.py
Adds helper functions that can identify if a function is either a generator co-routine, or has been marked with the `@plan` decorator.
Addresses need for checking whether or not a function is a plan as described in: #1779 
Added a parametrized unit test that passes & checks both positive and negative expected results. All other tests pass without issue (locally, waiting on CI).
```
(venv) [jwlodek@dell-rhel8 bluesky]$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
(venv) [jwlodek@dell-rhel8 bluesky]$ python
Python 3.11.9 (main, Jun 19 2024, 10:02:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> from bluesky.plan_stubs import mv
>>> …
```
=> Add private attribute for aiding in identifying if a function is a bluesky plan

src/bluesky/consolidators.py, src/bluesky/protocols.py
Closes #1800
I believe this means `Reading` will be typed as `Reading[Any]` but will double check.
Ah pyright sees an unannotated `Reading` as `Reading[Unknown]` which is actually very nice. Whatever `Reading`'s are allowed.
=> made `Reading` generic on the type of `Reading.value`

src/bluesky/tests/test_plans.py, src/bluesky/tests/test_utils.py, src/bluesky/utils/__init__.py
Implement `AsyncInput` using `run_in_executor`, as `loop.add_reader()` is not available for `stdin` on either of the standard windows event loop implementations.
`run_in_executor` may add a small amount of overhead (it uses a thread pool under the hood), but since we're then immediately asking for user input I do not think that is significant (if other facilities feel it _is_ a problem, we can split the implementation into windows-specific and linux-specific versions, but I don't feel it's worth the complexity cost personally...)
At ISIS we're using bluesky on windows. On windows, `bps.input_plan()` doesn't currently work with either the proactor or selector event loop implementations. See https://docs.python.org/3/library/asyncio-platforms.html#asyncio-platform-support for details about …
=> Windows: allow use of `bps.input_plan()`

pyproject.toml
Question: Should we double our CI matrix to test against numpy 1.x and 2.x? I lean "no", it is good enough to test against latest numpy, particularly because bluesky itself does not have any deep numpy integrations or compiled code.
=> Unpin numpy: support numpy 2.

docs/callbacks.rst, docs/state-machine.rst
Fixes https://github.com/bluesky/bluesky/issues/1772
As described in #1772, `LiveTable` does not work if you pass in an `ophyd-async` device object.
Although some other possible approaches were discussed on the issue (e.g. guaranteed sync protocols to get column names), the least invasive approach seems to be to just document the limitation and stop _recommending_ passing a device object to `LiveTable` in the docs, but without actually changing the implementation at all.
No code changes.
=> DOC: Discourage passing a device object to LiveTable

.github/workflows/ci.yml, src/bluesky/tests/__init__.py, src/bluesky/tests/test_examples.py, src/bluesky/tests/test_magics.py, src/bluesky/tests/test_new_examples.py, src/bluesky/tests/test_run_engine.py, src/bluesky/tests/test_scans.py, src/bluesky/tests/test_tiled_writer.py, src/bluesky/tests/test_zmq.py
- Fixes a number of unit tests which were either failing, inconsistent, or killing the pytest runner under windows
- Enable `windows-latest` as part of the testing CI matrix.
At isis we're running on windows, we'd like to be able to run the unit tests.
Enabled CI on windows runners to prevent regressions, but if we feel this is adding too many builds, then from our perspective we'd probably be happy with just a python 3.11/12 windows build at the moment (we don't use 3.10 or lower at isis).
See the CI runs.
=> Windows: fix unit tests & enable CI

.github/workflows/ci.yml, docs/tutorial.rst, pyproject.toml
Python 3.8 reached its end-of-life (per [Python upstream](https://devguide.python.org/versions/)) on October 7, a week ago today.
=> Drop Python 3.8 from CI matrix.

src/bluesky/tests/test_tiled_writer.py
Useful for testing bluesky on versions of Python where all of the tiled dependencies do not yet support.
tests pass without tiled installed locally.
=> TST: make tiled optional

src/bluesky/preprocessors.py, src/bluesky/tests/test_multi_runs.py
closes #1529
in baseline wrapper use the `msg.run` from the open/close for the inserted messages.
The baseline wrapper was written before we adding the "run key" support for muliti run it was naive to it.  This means that the baseline wrapper always tries to put events into the "None" run (default) which is either not what you want or fails with invalid sequence orders.
Added test based on @lsammut 's reproducer.
=> FIX: support baseline when using run keys

src/bluesky/plan_stubs.py, src/bluesky/run_engine.py, src/bluesky/tests/test_new_examples.py
This change updates the bps.wait plan stub by replacing the `move_on=False` argument with `error_on_timeout=True`. This aligns the parameter with its intended behaviour and makes the functionality clearer and more intuitive for users.
The move_on keyword argument in the bps.wait plan stub was undocumented, leading to confusion about its purpose and usage. By renaming it to error_on_timeout and clarifying its behaviour, this update improves the usability and discoverability of this feature. close #1824 
The changes were tested using the `ophyd-async` branch from PR [#691](https://github.com/bluesky/ophyd-async/pull/691) in a Linux environment with Python 3.11.3 and the provided dependency stack. The fly_and_collect plan was executed via a `RunEngine`, incorporating devices like `HDFPanda` …
=> 1824 bpswait move on kwarg is undocumented

docs/api_changes.rst, docs/metadata.rst, pyproject.toml, src/bluesky/tests/test_persistent_dict.py, src/bluesky/utils/__init__.py
Also xfail the one bad test based on version gating.
closes #1577
zict 3 has a behavior change that breaks one of our tests (and using two bsui sessions), see #1577 for details (thank you @dmgav for sorting out the problem!).
Pinning back zict is causing other conflict with dask and we should start to move away from it all together.
@genematx I know you are working on document RedisJsonDict, hopefully this does not step on what you are doing too much.
locally running tests
=> API: make zict an optional dependency and update docs

src/bluesky/utils/__init__.py
The docstring to the utility function ``make_decorator`` provides the example of ``customized_count = some_decorator(count)``. However, the correct usage should be ``customized_count = some_decorator()(count)`` otherwise we actually get ``dec(gen_func)`` as the decorated function, rather than ``dec_inner(...)`` as intended.
The equivalent syntactic-sugar version of ``customized_count = some_decorator(count)`` would be
```python
@some_decorator
def customized_count(...):
...
```
This is a common python pattern for decorators that do not require arguments.
However, the wrappers that are turned into decorators **may** accept additional arguments and so what comes back from ``make_decorator`` needs to be a decorator factory. The syntactic-sugar version would then be something like:
```python …
```
=> DOC: Updated example usage in the docstring for ``make_decorator``.

src/bluesky/tests/test_persistent_dict.py
The issue is that:
- zict3 adds an incrementing number to the file names
- each instance manages its counts independently
- the test tend to create 2 instances looking at the same files
- on object delete (via a weakref callback) the contents are flushed to disk
- the second one to fire fails because it can not remove a file already removed by the first
- this happens when gc runs so the failure shows up in some later test
Not completely clear why this does not _always_ happen, however because we are planning to move away from suggesting using these classes, it is not worth the effort to re-write the tests.
This pulls the zict related changes out of #1857 which can hopefully be merged with less review.
=> TST: skip all of the PersitentDict tests

src/bluesky/callbacks/tiled_writer.py
Watching @jwlodek demo Area Detector integration with ophyd-async, bluesky, and Tiled, I notice that
```py
c.values().last()["primary"]["data"][{field}].metadata
```
contained the Stream Resource. I believe that
```py
c.values().last()["primary"]["data"][{field}].data_source()
```
is the canonical location of this information. I think it should be preferred because:
1. It contains the complete filepaths, not templates (as in TIFF).
2. In the future we will add support for moving assets. (You could do this today with a SQL query; in the future I expect we'll add an HTTP API for it.) When we do, `data_sources()` will automatically reflect the new location. But `metadata` would need to be updated separately, and I think it would be easy for this to drift out of sync.
I propose leaving the …
=> Do not leak StreamResource in metadata.

pyproject.toml, src/bluesky/protocols.py, src/bluesky/utils/__init__.py
Drop dependencies requiring `Python < 3.9`, use `TypeIs` in `utils.maybe_await` and use `sys.version_info` to import `ParamSpec` in `protocols`.
- Since Bluesky supports `Python >= 3.9`, I removed some dependencies from `pyproject.toml` required for lower versions.
- [PEP 742](https://peps.python.org/pep-0742/) introduced `TypeIs` to narrow types and addresses the [issue](https://github.com/python/mypy/issues/15520) originally mentioned in `utils.maybe_await`. For `Python < 3.13`, this is backported in `typing_extensions >= 4.10.0`, which is bumped in `pyproject.toml`.
- Rather than using `try-except` to import `ParamSpec`, I used `sys.version_info` which is suggested in [this guide](https://learn.scientific-python.org/development/patterns/backports/#conditional-usage) from the Scientific …
=> [MNT] Remove non 3.9 dependencies and adjust some typing mechanisms

src/bluesky/plans.py
This updates the rel_adaptive_scan docstring to make it clearer that the start and stop are relative to the current position. This might be obvious as the name of the class starts with `rel`, but i think it doesn't harm to make it clear. 
We wanted to use a relative adaptive scan but weren't 100% on the behaviour just based on the docstrings. 
No functional changes here.
=> make rel_adaptive_scan docstring a bit clearer

src/bluesky/callbacks/mpl_plotting.py
Removes some debug-style prints from `plot_peak_stats` - I can't see that these would be useful for a typical end-user?
Example of what it would have printed:
```
{'color': 'k'} cen
{'color': 'r'} com
{'color': 'b'} max
{'color': 'm'} min
```
Cleaning up the output for an interactive session, after `PeakStats` have been plotted using `plot_peak_stats`
Tested interactively. Unit test not added for a `print` statement deletion.
=> Remove debug(?) print statements from `plot_peak_stats`

src/bluesky/run_engine.py
As we start using ophyd async more in prod, it would be good to include its version in the start doc metadata.
Ran scan with change:
```
========= Emitting Doc =============
name = 'start'
{
"uid": "3f79be77-edb9-4410-90bf-c24b0a9a3674",
"time": 1744208682.0387623,
"versions": {
"ophyd": "1.10.0",
"ophyd_async": "0.8.0a7.dev54+g46be3bf",
"bluesky": "1.13.2.dev44+g0ed50c97"
},
"scan_id": 1,
"plan_type": "generator",
"plan_name": "software_flyscan"
}
============ Done ============
```
=> Include ophyd_async version in start doc version metadata

src/bluesky/callbacks/core.py, src/bluesky/tests/test_callbacks.py
Resolves #1900 
Without this change, attempting to use an in-process live table callback with ophyd async Enum or bool signals would not process correctly due to the document not being entirely serialized to a string. The existing `LiveTable` would print enum data as just the first three characters of the enum's class name, and boolean signals would not print at all.
Enum & boolean signals should be printed correctly in `LiveTable` output.
* Included unit test
* Against a real ophyd async device.
=> Handle enum and boolean values passed via event data to `LiveTable`

src/bluesky/bundlers.py, src/bluesky/tests/test_run_engine.py
Doing it in the opposite order results in the old configuration value going in the new descriptor.
I broke this in f1b3179329f7af91acc3846b805a47f3403308f0 .  It would have been caught by tests in databroker (which the new test is a modified version of), but it was xfailed due to other the temorary too-strict rules for pre-declare and it was never un-xfailed.
Found a bluesky regression while working on tiled/databroker support
Added a test adapted from databroker tests.
=> FIX: regenerate the configuration cache before the descriptors

src/bluesky/plan_stubs.py, src/bluesky/tests/test_new_examples.py
This change is intended a shorthand for the following operation (and for `rel_set` / `mvr`):
```python
yield from bps.abs_set(obj, X, group=Y)
yield from bps.wait(group=Y, timeout=Z)
```
, so we can instead simply write
```python
yield from bps.mv(obj, X, timeout=Z)
```
I've come across many cases like this, where I'm moving regular signals (i.e not Positioners or anything of that sort), but the IOC or the hardware sometimes gets stuck, usually during some pre-scan configuration. In these cases, having a timeout is useful to give the user a meaningful indication of what has failed.
=> Add `timeout` argument to `mv` and `mvr`

src/bluesky/callbacks/tiled_writer.py
This uses Tiled `access_tags` to configure access policy to nodes created with TiledWriter.
=> Configure Access Policy for Tiled Nodes

src/bluesky/callbacks/buffer.py, src/bluesky/run_engine.py, src/bluesky/tests/test_buffering.py
Add buffering capability to Bluesky callbacks
An implementation of a simple wrapper for general bluesky callbacks that allows the downstream processing to happen in a separate thread without blocking the `RunEngine`. This could be useful for slow I/O operations (e.g. `TiledWriter`).
Intended usage:
```
tw = TiltedWriter(client)
buff_tw = BufferingWrapper(tw)
RE.subscribe(buff_tw)
```
Note that the `BufferingWrapper` must be used with great caution: the wrapped callback should be thread-safe and must not be subscribed to the RE directly. The errors encountered in the wrapped callback will not be propagated to the RE, and hence there is a possibility for data loss.
This is mainly a development feature to allow subscribing (potentially many) experimental callbacks to a `RunEngine` without …
=> Threaded Buffer to Allow Non-Blocking Callbacks

docs/tutorial.rst
Changed the bluesky tutorial documentation to include conda-forge instead of nsls2forge.
Max noticed a slightly outdated command when preparing the conva environment. 
Followed bluesky tutorial and was able to successfully create the conda environment. Ipython terminal opened without previous issue of incompatible types with qt5 and matplotlib.
=> DOC: updated tutorial doc to use conda-forge

docs/api_changes.rst, src/bluesky/run_engine.py, src/bluesky/tests/test_run_engine.py
Allow scan_id_source functions to be async
If the scan id is determined by an external service (as is the case at DLS), it
would be useful to not block on the request.
See #1895
New tests asserting scan id is updated correctly on `open_run` with both sync
and async source functions
=> ENH: Support async scan_id_source functions

src/bluesky/bundlers.py, src/bluesky/tests/test_run_engine.py
Do not randomize object order when creating implicit descriptors
closes #1930 , alternative to #1931 .
Added unit test
=> FIX: do not re-order the objects when creating implicit descriptors

src/bluesky/tests/test_tiled_writer.py
This fixes regressions in tests for TiledWriter after Tiled has been updated to v0.1.0-b38 and `Composite` structure has been replaced with "composite" spec. Specifically:
1. `.parts` replaced with `.base`
2. x-failing the test counting the number of `GET` requests: this will require changes to Tiled and will be fixed in the upcoming releas.
=> Fix TiledWriter Tests after Tiled v0.1.0-b38 release
